### ISSUE TITLE
decision on version control standards

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#11]
add to readme
policies on forking and merging pull requests

**Comment by colinxfleming** [comment]
I'll add a draft policy on this over the weekend.

**Comment by colinxfleming** [comment]
Putting a nail in this -- our draft policy is as follows from the readme. We can iterate on it as appropriate. 

## How Do I Contribute? 
This project runs on Github forks and pull requests, so we can be sure to make changes incrementally and keep everything clean. For an introduction to github, check out (this guide on github.com)[https://guides.github.com/activities/hello-world/]. 
* To contribute, visit [the main project page](https://github.com/colinxfleming/dcaf_case_management) and fork from the master branch by pressing the `fork` button near the top right.
* Do any work in your local environment and commit it to your fork in github.
* Once you have finished your changes and have confirmed they're all working, make a pull request by pressing the Pull Request button.
* At least one other person (probably @colinxfleming) will review and comment on code changes, and work with you to resolve issues, and merge the pull request when it's ready.
