### ISSUE TITLE
Set up continuous deployment

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#110]
When master bumps and tests pass, send it off to heroku!

Don't have a particular recommendation for how this gets done as long as it's free.

**Comment by mchelen** [comment]
maybe https://circleci.com/docs/continuous-deployment-with-heroku ?

**Comment by colinxfleming** [comment]
Good call! Thx @mchelen , will take a look at that this week.

**Comment by colinxfleming** [comment]
Fixed in #117 . Thanks for the rec @mchelen !
