### ISSUE TITLE
Time out urgent pregnancies after five days

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#119]
(note: starting to create issues not associated with sprints for backlog issues. hope that's okay @adinneen , let me know if I should do this different)

@lwaldsc flagged that there's a scenario where urgent cases shoud probably eventually fade out, so that we avoid having a big backlog that nobody ever cleans up except like one superstar. (see also "the time the voicemail didn't get cleaned out for like a month", says @lwaldsc .)

So we have an open question of how to handle this. Should we have people time out after a week or two of being urgent and not being able to reach a patient, or not have them time out at all, or some other behavior? 

cc @NerdyGirl537

**Comment by colinxfleming** [comment]
Raised in #405 -

> 4 - Automatically flag patients who have been in the system for a long time as urgent [1 user]

**Comment by colinxfleming** [comment]
Topping this. @lwaldsc @NerdyGirl537 what should the rule around this be? Maybe someone can only live on the urgents list for two weeks without a call being placed before they get removed from the urgents roll, or maybe after two weeks they get highlighted in red in the table? 

What do you think will keep the urgents list clear, but also not kick people off who we're still actively working with?

**Comment by NerdyGirl537** [comment]
Thoughts:  what if we made a toggle like OK to leave VM?  Then a CM could turn it on and off.  Also, this reminds me that last I looked updating the PT to urgent required adding a note.  I was expecting to be able to just check the box and have it update.  I thinking having to add it with a note might get unwieldy.

For me, using this flag would be for the duration of my shift and at hand-off for the next CM.  If we're just going to have it cleared, maybe at 5 days.  Again, some of this can be managed with training.  We set expectations that 5 days after a CM adds a PT to the urgent list, the PT will fall off that list.

**Comment by colinxfleming** [comment]
@NerdyGirl537 I hear you on the toggle, but I worry about the level of complexity there. 

Having to add a note to hit urgent is a bug that we've filed in #486 . So that'll come around sooner rather than later. 

I like the idea of urgents as a handoff mechanism, and setting that expectation. @mebates please flag if you object.

Let's plan on this as the plan of action:

* Write a method for the `Pregnancy` object that sets the `urgent` flag to false if they've been urgent for 6+ days. (Gold medal is doing it via audit trail data. A new form field is also okay in a pinch.)
* Write a rake task that iterates through users with urgents flags and runs that method
* Flag for @colinxfleming to hook that into the scheduler run nightly

**Comment by NerdyGirl537** [comment]
@colinxfleming another thought: a PT should also drop off the urgent list if the status changes to either "Pledge Sent" or "Resolved By Not DCAF" (or whatever we've decided for that one).

**Comment by colinxfleming** [comment]
@NerdyGirl537 let's punt on that for now while we get the general task for urgents cleanup in place, if that's cool with you. I want to get the minimum viable version of this in place before we get this really going and carve out the exact stuff.

**Comment by charleshuang80** [comment]
I will start on this issue

**Comment by colinxfleming** [comment]
Hey @charleshuang80 , just wanted to give this a tug for tomorrow
