### ISSUE TITLE
Discuss what path to take for app development: Vallejo fork or separate deal?

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#12]
Vallejo is a django tool that Mollie found out about at CFA which solves a similar problem (managing a variety of contacts and cases, logging touches with them, and then marking them complete):  https://github.com/codeforamerica/vallejo-css-toolkit

(The alternative is whipping up something from scratch, most likely.)

I think this requires a conversation with some django-comfy folks about adapting this to our needs and how much of the core engine and wiring we'd have to replace. 

If it IS adaptable to our needs, it's a great head start!

**Comment by mebates** [comment]
Or is the District Housing something worth forking? Agree that this should be a priority.

**Comment by colinxfleming** [comment]
After chatter with @cmgiven @stvnrlly @drownedout @chieflotsadoe we've decided to go with a fork of `districthousing` -- our reasoning is that code for dc sees slightly more rails people than django people, and it would be cool to have a successful code for dc project beget another project.

**Comment by mebates** [comment]
So you're not going to fork, you'll start from scratch?

**Comment by colinxfleming** [comment]
Right now I think I'm leaning slightly toward rolling our own -- Charles pointed out that districthousing is capital b big, and so there might be a lot we would need to shave off and it might wind up being a heavier lift in the long run. 

I don't think we should make a final call on this yet though -- interested in what @stvnrlly @cmgiven Charles and Marcus from districthousing think.

**Comment by colinxfleming** [comment]
Spoiler alert, we're rolling our own. Closing since we're well into rails-ing now.
