### ISSUE TITLE
Call log modal broken by JS

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#121]
Sad to say, the modal JS stopped working when the search bar went in. 

Need to fix so we can continue to log calls, but not a huge deal.

**Comment by ajohnson052** [comment]
PR #129 addresses this, but it seems strange that it broke when the search bar went in. Makes me wonder if there's something else wrong...

**Comment by colinxfleming** [comment]
There was some hardcore wrenching on the partials in my integration tests PR to dry everything up, so I think likely that's what screwed it up. At any rate, really appreciate your fixing it.

**Comment by ajohnson052** [comment]
Sure thing!
