### ISSUE TITLE
Patient dashboard partial: Enforce date format (YYYY-MM-DD) on appointment date string

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#132]
The view currently looks like so: 

![screen shot 2016-03-10 at 11 38 47 pm](https://cloud.githubusercontent.com/assets/3866868/13693446/40ad8dec-e719-11e5-8a75-9159fdf73477.png)

The appointment date down in the right corner should be a datepicker module with the option to type in the date, rather than three separate drop-downs. This is to reduce the number of clicks/keyboard strokes a CM will need to update an appointment date. 

( @adinneen  @mebates please let me know if I'm off base!)

**Comment by colinxfleming** [comment]
This is partially bumped but the click-to-datepicker functionality isn't set up quite yet.

**Comment by colinxfleming** [comment]
Adding to sprint 6!

**Comment by colinxfleming** [comment]
This is an example of what I have in mind here: 

http://eternicode.github.io/bootstrap-datepicker/

We're using a different library at the moment but it's clunky, so we should feel free to change it up if it suits our needs.

**Comment by mebates** [comment]
Let's try this instead? US Web Design Standards discourage the date picker especially for memorized dates like your birthday. They do have this caveat "If users are trying to schedule something, a calendar picker might make more sense. Be sure to also provide an option for text entry as well." But, our cm's won't be scheduling, they'll just be recording what the patient tells them, right?
https://standards.usa.gov/form-controls/#date-input

**Comment by colinxfleming** [comment]
@lwaldsc @NerdyGirl537 thoughts on the above? Do you find you're doing much scheduling (e.g. 'this weekend'), or is it more along the lines of entering dates ('my appointment is on the 26th')?

**Comment by colinxfleming** [comment]
(Also we'll want to bump the `update_patient_info_test` integration test when we tackle this.)

**Comment by NerdyGirl537** [comment]
@colinxfleming @lwaldsc 
My experience is usually that they either have a specific date or no date.

**Comment by mebates** [comment]
A vote for a date input, then!

**Comment by colinxfleming** [comment]
Question is resolved, but I'm out of gas and too tired to write down detailed instructions at this time so I'm not marking as beginner friendly at this time. The tldr is that we need to have this function as a regular text field but enforce the styling of a datepicker, and when we get a clean, design-team approved solution to that we should apply it to both the pregnancy edit page and the new pregnancy partial.

**Comment by colinxfleming** [comment]
Changed title of issue. Should be possible with some regex validation in the Pregnancy model.
