### ISSUE TITLE
Table content partial: Change call to a glyphicon

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#133]
Line 11 of `app/views/pregnancies/_table_content.html.erb` currently reads as follows:

`<td><%= link_to "Call", "#call-#{p.patient.primary_phone}", data: {toggle: "modal"} %></td>`

Should read something more like so:

`<td><%= link_to '<span class="glyphicon glyphicon-earpiece" aria-hidden="true"></span>', "#call-#{p.patient.primary_phone}", data: {toggle: "modal"} %></td>`

Couldn't figure out the HTML escaping while resolving conflicts in #113, so creating an issue and moving on.

**Comment by cmgiven** [comment]
`.html_safe` for the win. Also added a label for screen readers.
