### ISSUE TITLE
Move external assets into vendor/assets/

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#134]
We currently have three external assets that we should move into the vendor directory. They are as follows:

* - [ ]  app/assets/stylesheets/application.css.scss: `@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,200italic,300,300italic,400italic,600);` (should be moved into stylesheets so it's accessible)
* - [ ] app/views/layouts/application.html.erb: `<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,200italic,300,300italic,400italic,600' rel='stylesheet' type='text/css'>`
* - x app/assets/javascripts/bootstrap_toggle.js and app/assets/stylesheets/bootstrap_toggle.js

Should be moved to their respective directories in the `vendor` directory, and then should confirm that they're still loading as normal.

**Comment by ewiggins** [comment]
@colinxfleming I'll take this. Seems like an easy win :100: :+1:

**Comment by colinxfleming** [comment]
Thanks Elisheba!  Let me know if you hit any snags!
