### ISSUE TITLE
Standardize bootstrap col attributes

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#144]
We should standardize our `col` classes to either all `sm` or all `md`. Thanks @charleshuang80 for flagging this.

**Comment by colinxfleming** [comment]
After some comparison of what we have rolled up now I think we're looking for `sm`. I think we can roll this into a beginner friendly task.

**Comment by colinxfleming** [comment]
The task here: In files ending `.html.erb` within the `app/views/` directory (so, all the stuff in subdirectories), we need to standardize the way things snap to grid using the bootstrap grid system.

There are a number of HTML elements with the class `col-(a size)-(a number)` (for example, `col-sm-6` or `col-md-3`. Up to now we have been using both `sm` and `md`, but now we want want to standardize the size to `sm` across everything. Edit the view files one by one to get everything on `sm` where it's currently `md`, and submit your changes in a pull request.

(Note: Don't worry about files that end in `.js.erb`!)

**Comment by clarissastark** [comment]
Hey @colinxfleming, I'll take this one to start!
