### ISSUE TITLE
Clinic modeling

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#146]
We have a limited number of clinics that doesn't change much, that should be admin-editable. It's not optimal behavior to edit this from 

IDK what the UX component of this looks like, but the proper data model is probably a `has_one :through` between pregnancy and clinic, so we can assign an identifier from a list of clinics.

**Comment by colinxfleming** [comment]
I have no idea whether or not there's a more mongo way to do that. I assume there is, since documents and all.

**Comment by colinxfleming** [comment]
Promoting from backlog since we'll have to figure this out soon.

**Comment by mebates** [comment]
Tonight our test user was slowed down by having to enter the Clinic name and full address (this is more than the current spreadsheet asks for). For MVP, should we drop in a list of clinic names and eliminate the address part? Does the CM need to know the address in the system or can they can that info somewhere else?

**Comment by eheintzelman** [comment]
Based on the testing yesterday, the clinic address isn't essential.  One CM said that she sometimes googles a clinic's address to pass it onto the patient.  So it would be helpful, but not essential for MVP.

**Comment by colinxfleming** [comment]
I think that taking out clinic address is right on and moving this to a dropdown is right on. I think long term I'd like to have some kind of reference file where this kinda stuff will autopopulate as a read-only field, but that's probably a release 2 or 3 kinda thing.

I'll spin up a new issue for 'select clinic from dropdown for mvp', and change this to a backlog issue like 'load clinic info from yaml file' or something boring and technical like that.

**Comment by colinxfleming** [comment]
There we go, nice and boring and technical. Steps here are: 

* Figure out a YAML/JSON format  for clinics that reflect information worked out in tandem with CM team (starter kit: Address, spanish speaking-ness, costs)
* Make available as a general reference in the app
* Have clinic in the pregnancy edit form consume that YAML file to populate the dropdown

Tagging as admin and backlog.

**Comment by colinxfleming** [comment]
Observation from #405 - 

>Alternatively, create a dropdown for clinic selections since typically CMs work with a fixed set of clinics.  Address and zip could automatically populate when the clinic is selected.  It is useful for CMs to have this address info on hand because they sometimes provide this address information to patients.  Include an option to enter the name of a clinic manually, since this does sometimes (though rarely) come up. [2 users]

**Comment by colinxfleming** [comment]
At some point we need to roll out a full object model for clinics. Other conversations have more or less made this gel into something fairly complete, as follows:

```
Clinic:
  name:
  addr:
  zip:
  phone:
  fax:
  primary contact for billing:
  primary contact for acknowledging pledge receipt:
  gestational limit:
  do they accept medicaid:
  medical limitations (no anemic patients, no c-sections, etc):
  fund discount:
  ultrasound discount:
  languages spoken:
  accessibility:
  costs by lmp:
  accepts naf money:
  protesters:
  requires escorts:
  does naf intake on site:
```

**Comment by lwaldsc** [comment]
@vtmeghan should have this information in a handy dandy chart, I believe.

**Comment by colinxfleming** [comment]
@jingpei for an MVP, here's the fields we can add to the model: 

  accepts_naf: boolean
  gestational_limit: number
  costs_9wks: int
  costs_12wks: int
  costs_18wks: int
  costs_24wks: int
  costs_30wks: int

**Comment by mebates** [comment]
@colinxfleming - can we draw a little map of how the Analysts get to this view? Where is this fitting in the information architecture? Are there permissions about who can edit the clinics, and who can't? Also want to make sure that we use plain language for the input labels in our final version.

**Comment by colinxfleming** [comment]
Postscript in case we ever refer to this again, as of 5/5/2017:

* Permissioned for admins only, for both viewing the roll and editing/creating/updating/removing clinics
* Accessible from top navbar (via #1036 )
* Usable by CMs in the dropdown

Other stuff to be handled in other PRs.
