### ISSUE TITLE
Set up MongoidHistory for Pregnancy object and associated embedded docs

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#149]
One of the things we're interested in is tying particular changes to particular users. To do that, we should set up MongoidHistory so that we can see what users were making what changes. 

https://github.com/aq1018/mongoid-history#usage

It looks like it requires some additional setup to link actions to a given user -- control-f 'adding userstamp on history trackers' for more info.

**Comment by colinxfleming** [comment]
Underway via @charleshuang80 and @Kevin-Wei

**Comment by Kevin-Wei** [comment]
https://github.com/colinxfleming/dcaf_case_management/pull/165 we did it on patient though @colinxfleming

**Comment by colinxfleming** [comment]
Doing it on patient is right on. Thanks a ton!

**Comment by colinxfleming** [comment]
Spun handling this for embedded documents into its own issue; closing.
