### ISSUE TITLE
Integration test to confirm that hitting call result successfully logs a call, and that it displays properly

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#156]
Do what it says on the label!

**Comment by colinxfleming** [comment]
It turns out that getting capybara to execute a `respond_to { |format| format.js }` is a tremendous pain. May wind up just smoke testing and unting.

**Comment by Kevin-Wei** [comment]
logs call first time. on the clickback through it never hits the controller.

**Comment by colinxfleming** [comment]
Resolved in #310 ; closing.
