### ISSUE TITLE
Design screens after 'submit pledge'

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#16]
What happens once the user hits 'Submit pledge'? Things may include:

- finalizing pledge amount
- creating PDF to fax
- faxing PDF
- going back to start screen

**Comment by mebates** [comment]
Let's prioritize this for next week and work through it with a DCAF volunteer.

**Comment by adinneen** [comment]
@mebates Hey Mollie these wires are super super rough but give you a sense of the flow we worked out.  I'll post a new ai file to the design folder.  Happy to touch base on any of this. 

User starts by hitting the "generate 
![dcafwireframe020816 1 -08](https://cloud.githubusercontent.com/assets/12372787/14624445/b9e5386a-05a8-11e6-8c4d-68cd0053d3f3.png)

![dcafwireframe020816 1 -09](https://cloud.githubusercontent.com/assets/12372787/14624450/c23c42ba-05a8-11e6-8588-c1fa0154b7cd.png)

![dcafwireframe020816 1 -10](https://cloud.githubusercontent.com/assets/12372787/14624455/cb216f4a-05a8-11e6-8b53-e7f909e875ef.png)

**Comment by mebates** [comment]
Great! 
- On the 'confirm' modal, will the user be able to edit those fields or will they have to cancel to go back and edit?
- Will the word document autopopulate with the right information (that would be sweet!)
- Veer towards left aligning text instead of center aligning
- With the 'go back' button, does it go to the previous modal screen? Is it weird to navigate forwards and backwards in modals? I wonder if these should be their own screens. But the modals might work ...

Thanks for getting this moving! BIG STRIDES! ⭐

**Comment by mebates** [comment]
Latest designs: https://github.com/colinxfleming/dcaf_case_management/blob/master/_design/DCAF_SubmitPledge.pdf

**Comment by colinxfleming** [comment]
I think we can safely call this resolved -- we've got these represented in https://github.com/colinxfleming/dcaf_case_management/blob/master/_design/DCAFwireframe052416.pdf . Closing it out. 

Fabulous work @adinneen and @mebates !
