### ISSUE TITLE
Pre-call screen

### ISSUE THREAD

**Issue by adinneen** [colinxfleming/dcaf_case_management#17]
Add a screen before a call is placed a patient to record any available information from the voicemail that was left.   This is only necessary when a new record is being created because DCAF has no information on the patient.

**Comment by mebates** [comment]
This is a priority for Sprint 1

**Comment by mebates** [comment]
I think that we duplicated this issue in #65 and closed that one out. Does that look right to you @colinxfleming? If so, please close.

**Comment by colinxfleming** [comment]
Sounds good! Marking complete.
