### ISSUE TITLE
How to display timestamps?

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#177]
This is starting to come up more and more -- can we agree on a way to handle datestamps and timestamps, and then develop a unified method to handle in a helper somewhere?

**Comment by colinxfleming** [comment]
(Marking question so we can discuss before foraging forward)

**Comment by colinxfleming** [comment]
My inclination is `YYYY-MM-DD` for datestamps and `HH:MM XM` for timestamps (using a 12 hour clock). 

Some additional stuff that we can consider, that has come up (as I find it):
* Using `getlocal` (s/o @ajohnson052 ) 

I'll get a proposed method in sometime in the near future.

**Comment by Kevin-Wei** [comment]
http://www.foragoodstrftime.com/ !
