### ISSUE TITLE
Only display full call list toggle if there are 10+ calls

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#178]
In `app/views/pregnancies/_call_log.html.erb`, there's a toggle button that displays the full set of calls instead of just limiting to the most recent 10. In the event that there aren't ten calls yet, let's make it not show up.

**Comment by mebates** [comment]
Also, let's not make it a big purple button! Something more subtle, please?

**Comment by mchelen** [comment]
@mebates How about `.btn-default` http://www.w3schools.com/bootstrap/bootstrap_buttons.asp or adding `.btn-outline` http://bootsnipp.com/snippets/featured/bootstrap-outline-buttons ?

**Comment by mebates** [comment]
@mchelen, I think it can just be linked text. The action isn't important enough to warrant a button. Thanks!

**Comment by mchelen** [comment]
@mebates Ok sure thing, I think I have that implemented, but I can't test it because I'm not sure how to add calls?

**Comment by colinxfleming** [comment]
@mchelen our local expert on all things call-adding is @ajohnson052 . One of us will get you on the right track here at the mtg tonight. 

It might be wise to make a seeds edit so we have a couple fleshed out instances with varieties of fake data, to reduce the overhead, as well.

**Comment by mchelen** [comment]
Ok, updated PR #199 to make it a plain link

**Comment by mchelen** [comment]
I've been digging into the `pregnancy.rb` model and I see this code:
```ruby
  def recent_calls
    calls.order('created_at DESC').limit(10)
  end

  def old_calls
    calls.order('created_at DESC').offset(10)
  end
```

So that means `recent_calls` will always have a max of 10 items, and `old_calls` will also have a max of 10, so at any time there is an absolute max of 20 total calls displayed.

Is that the desired behavior?

**Comment by colinxfleming** [comment]
@mchelen I think either that or just the count of calls in general -- you can infer that `old_calls` will be null if there's ten or under. But yeah, you're totally dead on.
