### ISSUE TITLE
New Call Modal failing to save 'I Reached the Patient' calls

### ISSUE THREAD

**Issue by ajohnson052** [colinxfleming/dcaf_case_management#179]
The new call modal isn't working properly all the time. So far I seem to have issues when I try to go back to the dashboard index from the edit pregnancy page by clicking on "DCAF Case Manager" from the nav bar. If I refresh the page it works fine.

**Comment by colinxfleming** [comment]
Resolving this is a priority; I'm adding this and associated integration tests to the current sprint, since we'll have two full meetings in that time. 

Thanks for flagging @ajohnson052 !

**Comment by colinxfleming** [comment]
Note that tests for this are in #156 and we shouldn't. 

@Kevin-Wei has documented some weirdness in #156 that makes me think this is a JS issue, which is unfortunate.

**Comment by colinxfleming** [comment]
This seems to be only happening when you hit the 'I reached the patient' button. Still think it's a JS issue, but not clear how.
