### ISSUE TITLE
Database side: What to use? 

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#18]
Since we've settled on Rails, I think the next major architecture decision we need to make is how to store our data securely and accessibly. DCAF is able to spend some money in order to outsource the security component of this rather than rolling it up from scratch, so cost should be a factor but we shouldn't just take the closest, free-est option and hack that into what we need. (If we have to spend like $25-50 a month for a solution then DCAF can swing that without issue). 

My wishlist for this, more or less in order: 
* Extremely secure (we are storing very sensitive information, after all)
* Well documented
* Able to provide a separate, distinct account for every case manager
* Has a ruby wrapper 

Here are two options for secure-looking data storage that look like they might be a very good fit:

### Salesforce Nonprofit edition 
http://www.salesforce.org/nonprofit_product/nonprofit-editions-pricing/ 
This is a lot of firepower but they have a REST API we could use to store and retrieve info without that much of a hassle. They limit us to 10 accounts before we start paying a premium of $30/m per user, so our CM corps is too big to have one SF account per user. 
**Benefits**: Free if we share Salesforce accounts between users, other funds are using Salesforce and have an okay time with it, Salesforce is pretty well documented, seems to be pretty hardcore about security
**Drawbacks**: Cost-prohibitive for individual user accounts, though we could roll our own with `devise`

### Firebase
http://www.firebase.com
Looks kinda like a separate database-only service, with pretty flexible rules. Seems good about security and encryption, and perusal of the settings page makes it seem like making things inaccessible to certain users after a given amount of time is trivial. 
**Benefits**: There's a ruby wrapper for it, affordable option, security doesn't seem to be an afterthought, googling 'firebase security breach' didn't turn up anything
**Drawbacks**: Might be tough to figure out how to use -- don't know how good the documentation is

Other stuff I found by googling but don't know anything about, which might be good to investigate: 
https://parse.com/
https://fanout.io/

**Comment by Kevin-Wei** [comment]
If the primary needs for starting out are:

- non relational tables
- schema flexibility
- rapid development 

MongoDB fits the use case for this project. 

For encryption needs [Symmetric Encryption](https://github.com/rocketjob/symmetric-encryption) is suitable option that works for any ruby ORM.

**Comment by colinxfleming** [comment]
@Kevin-Wei I'm into the symmetric encryption idea, and into the idea of using Mongo! I haven't used nosql before but have always meant to -- I'll do some reading up on it this coming week. Thank you very much for the suggestion!

I'm a little curious about the security aspect, since it's like the first question the DCAF board will ask about -- want to make sure that keeping patient data safe and private is as baked into the process here as flexibility and rapid development. Are you recommending we roll with Mongo at first and then swap to something else once we're past prototyping, or going with mongo the full way thru?

**Comment by colinxfleming** [comment]
I did some googling and it looks like heroku, among others, offer Mongo options. Two specifics: 

https://elements.heroku.com/addons/mongolab
https://elements.heroku.com/addons/mongohq

pretty neat!

**Comment by mebates** [comment]
I believe the conversation was to roll with Mongo at first and then swap to something once we're past prototyping.

**Comment by Kevin-Wei** [comment]
Mongo might not be a bad permanent solution. They just released 3.2 today and basically added joins with their implementation of [$lookup](https://docs.mongodb.org/manual/reference/operator/aggregation/lookup/#pipe._S_lookup) aggregation. aka SQL Joins.  

of course the downside is keeping track of private keys and the DB's themselves will need to be done manually

**Comment by colinxfleming** [comment]
To update this: We're going to roll with mongo for development for the time being. The initial stab is in pr #28 .
