### ISSUE TITLE
NOTES: Add checkbox for urgency to the notes section

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#194]
Underneath the input box for a new note, there should be a checkbox to flag a patient as urgent, as represented in the InVision here:

https://projects.invisionapp.com/share/6757W6WFJ#/screens/115983268

This should be an attribute on the `Pregnancy` object as well, and part of the main form.

**Comment by Nico-ehs** [comment]
Add this next.

**Comment by CamLatimer** [comment]
i'm on it

**Comment by CamLatimer** [comment]
I'im on it.

**Comment by colinxfleming** [comment]
Looks like this has fallen off -- going to knock it out this afternoon.

**Comment by CamLatimer** [comment]
Ah. Sorry for getting sidetracked.

**Comment by colinxfleming** [comment]
No worries! TBH this got a lot easier than it would have been otherwise
after I refactored the forms to all run ajax, so I'm glad we waited on
this.
