### ISSUE TITLE
Spin front-end design improvements into their own issues

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#195]
Creating a checklist of design improvements for CSS-inclined friends to tick off over the next few weeks.
You can always refer to the [native .ai files](https://github.com/colinxfleming/dcaf_case_management/blob/master/_design/DCAFwireframe020816.ai) or the [Vivify clickable prototype](https://projects.invisionapp.com/d/main#/projects/5385941) if you don't know what I'm talking about! 

**Everywhere**
- [x] Remove black line around purple buttons
- [x] Load Source Sans Pro and make it the default font for the site
- [x] Base font size should be 17 px, not 14 px
- [x] Font size for all input boxes should be 17 px
- [ ] It would generally be cool if we could implement a standard type hierarchy for H1, H2, H3 etc across the site. If you're interested in this task, let's chat!
- [x] Use sentence case across the site (i.e. "This is an item label" not "This Is An Item Label")

**Dashboard**
- [x] Widen width of name / phone number entry box
- [x] Lowercase "R" in "Search results" heading
- [x] 'Call' phone icon should be a white phone in a blue circle
- [x] 'Call' phone icon should be a white phone in a blue circle

**Patient detail page**
- [ ] Selected menu item in the left nav should match specs in InVision (purple text) Remove blue highlight. 
- [ ] Add right-facing caret to the left of the selected menu item.
- [x] 'Submit pledge' button should be BIG (super button) and should have more blank space above it, separating it from the left nav menu items. 
- [x] Add lines into the page separating top entry, left nav and main right window. 
- [x] Black bar at the top should be gray, type should be black

**Comment by rebeccaestes** [comment]
test

**Comment by mebates** [comment]
Details on the type hierarchy. The names I'm using may not align with the names you'll use in the HTML. All type is Source Sans Pro. (Sizes cribbed from here: https://cfpb.github.io/design-manual/identity/typography.html#web-hierarchy) 

Display: 48 px / 60 px, 300 (Light)
H1: 34 px / 42 px, 400 (Regular)
H2: 26 px / 32 px, 400 (Regular)
H3: 22 px / 28 px, 400 (Regular)
H4: 14 px, 700 (bold), uppercase, 1 px letter-spacing

Body copy: 17 px / 26 px (1.5 em), 400 (Regular)

**Comment by mebates** [comment]
Great work @rebeccaestes !!!

**Comment by colinxfleming** [comment]
#195 resolves the following: 
 Remove black line around purple buttons
 Load Source Sans Pro and make it the default font for the site
 Base font size should be 17 px, not 14 px
 Font size for all input boxes should be 17 px
 Use sentence case across the site (i.e. "This is an item label" not "This Is An Item Label")
 Widen width of name / phone number entry box
 Lowercase "R" in "Search results" heading
 'Call' phone icon should be a white phone in a blue circle
 'Call' phone icon should be a white phone in a blue circle
 Selected menu item in the left nav should match specs in InVision (purple text) Remove blue highlight.

**Comment by colinxfleming** [comment]
#220 resolves the following: 
 'Submit pledge' button should be BIG (super button) and should have more blank space above it, separating it from the left nav menu items.
 Add lines into the page separating top entry, left nav and main right window.
 Black bar at the top should be gray, type should be black

**Comment by colinxfleming** [comment]
The bulk of these are closed, and I think we can spin the remainder (h tag hierarchy, carets and blue highlights) into their own issues. Retagging as admin.

**Comment by mebates** [comment]
More design fixes! 

On the patient views:
- [ ] What's going on with the grid? Are we using one? For the header (ex: "Call Log") there shouuld be equal distance above and to the left. Check out how the grid is set up in illustrator: 
![dcaf_grid](https://cloud.githubusercontent.com/assets/6223901/14971911/e92c3dba-10a4-11e6-9c40-ca93145cb16e.PNG)
- [ ] Call Log and Notes headings are incorrect style
- [ ] Everything should align under the heading. See the grid screen grab
- [ ] Select and hover states on the left nav don't match the specs on the design files
- [ ] Notes input box should be a lot bigger, wider, deeper
- [ ] On all tables, site wide, the table header should align left with the table content. It's all jankety right now.

**Comment by mebates** [comment]
## Some random UI questions for @colinxfleming:
- What's up with the add/remove in the call list? That wasn't on the mockup; was it added for another reason?
- Nice to have: can we do all address inputs so that the zipcode automagically looks up the city and state?

## Some things to fix
- [ ] The 'call now' modal needs lots of padding, spacing, and type styling love. Please match the mockup!
- [ ] When a user saves a note to a case, it shouldn't navigate away from the 'Notes' page. Right now it goes back to the Abortion information page
- [ ] This looks very funky! Do we need the up and down arrows and the x?
![delete2](https://cloud.githubusercontent.com/assets/6223901/15523516/f7adaafe-21e8-11e6-9224-38ec5dee69fa.PNG)

**Comment by colinxfleming** [comment]
I think many of these are sustainable as their own issues, so I'm going to piece them out into new issues and close out this one. 

@mebates re: the ui questions you wisely raised, IIRC I think originally the mockup was a + / - glyphicon? We've been using that as a placeholder but there's no reason we can't move it over. I'll review the designs before I spin that off to make sure I'm remembering correctly.

**Comment by colinxfleming** [comment]
re: ZIP code lookup, I'm super optimistic we can pull something off using a ZCTA or USPS or some sort of mapping API. My inclination is to skip it for MVP and then have it as part of the second phase of this, when we'll be bolting on additional functionality and adding reconciliation etc.

**Comment by colinxfleming** [comment]
(PS totally went into a cold sweat thinking about ZIPS that span multiple cities and states, the bane of my existence in mid-2015.)

**Comment by mebates** [comment]
On the mockups, the + near the note field was to see the full note. We do need an 'add to call list' plus in the part where they're looking up numbers

**Comment by colinxfleming** [comment]
Things are moved up to https://github.com/colinxfleming/dcaf_case_management/issues/195#issuecomment-216404608 . I'll create new issues for my many crimes against the grid system, UI, etc later tonight.

**Comment by colinxfleming** [comment]
The following two bullets from https://github.com/colinxfleming/dcaf_case_management/issues/195#issuecomment-216404608 are moved to #304 . @mebates please confirm I translated these correctly!
- For the header (ex: "Call Log") there shouuld be equal distance above and to the left. 
- Everything should align under the heading. See the grid screen grab

**Comment by colinxfleming** [comment]
Down the list in the remainder of https://github.com/colinxfleming/dcaf_case_management/issues/195#issuecomment-216404608 - 
* Select and hover states on the left nav don't match the specs on the design files (represented in #303 )
* Notes input box should be a lot bigger, wider, deeper (underway in #291 )
* On all tables, site wide, the table header should align left with the table content. It's all jankety right now. (also underway in #291 ?)

**Comment by colinxfleming** [comment]
The add to / remove from call list I'm moving to #305. I think we should confirm with @lwaldsc and @NerdyGirl537 before we pull the trigger on resolving that, though I think it'll be fairly straightforward either way due to @charleshuang80 's excellent work on generalizing that code.

ZIP code thing is moved to #306 .

**Comment by colinxfleming** [comment]
- The 'call now' modal needs lots of padding, spacing, and type styling love. Please match the mockup! (now in #307)
- When a user saves a note to a case, it shouldn't navigate away from the 'Notes' page. Right now it goes back to the Abortion information page (now in #308) 
- This looks very funky! Do we need the up and down arrows and the x? (now in #309)

**Comment by colinxfleming** [comment]
I think that's all of it! Closing this out.

**Comment by mebates** [comment]
👍  reviewing all new issues now.
