### ISSUE TITLE
Rename project / repo / slack channel?

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#2]
What should this thing be called?

**Comment by colinxfleming** [comment]
Can you give me a sense of what you have in mind, or what you think our project title should include? 

I think I favor keeping reference to Dcaf but it's not a hard and fast requirement for me. Still, think it should include some ref to the org somewhere if not the title.

**Comment by mebates** [comment]
I wonder if there's something snazzier and more brand-able than "case management". That's such a broad term and I'm not sure that it captures what we're trying to build (or that we generally know that). Do we think that this repo will be specifically for the DCAF tool and then the future 'neutral' version would be named something else?

**Comment by colinxfleming** [comment]
(For context, during the planning phase of this, we recognized that the data problems DCAF is facing aren't unique to DCAF -- lots of orgs do everything in running, messy excel sheets -- and talked about how we could build something out general purpose.)

I think that we should build this repo out focusing on DCAF, and then take the lessons learned with us into the future / neutral version. My reasoning is that right now we have a very well defined set of needs from DCAF but don't necessarily have the same deep understanding of what's generalizable and what's not. I think it's something we should keep in the back of our minds as we develop and design this, but that the neutral version should probably be named and built as something else. Yr thoughts? Def feel free to be like 'nah' if I'm off base here or thinking of this with DCAF tunnel vision. 

@stvnrlly @cmgiven would appreciate your thoughts on this, as people involved in the planning process.

I'm 100% on board with giving this a snazzier name though! From when I worked in email fundraising data, some people used to do a thing called 'Subject Line Derby' where you'd open up a google doc with 3-4 other people and just type whatever came to your head. Maybe we could try that, haha.

**Comment by colinxfleming** [comment]
Backlogging this for after MVP, since the MVP will work no matter how snazzy the name is.

**Comment by colinxfleming** [comment]
DCAF's CM corps wants to call this Daria, for DCAF Abortion Records Information Application. Cool to make that change for December 5 @mebates ?

**Comment by mebates** [comment]
oh man. i won't argue with the people! 👯
