### ISSUE TITLE
Implement structured data field values for dropdowns

### ISSUE THREAD

**Issue by lwaldsc** [colinxfleming/dcaf_case_management#200]
Listing the structured data field values:

**Race/Ethnicity:**
White/Caucasian
Black/African-American
Hispanic/Latino
Asian or South Asian
Native Hawaiian or Pacific Islander
Native American
Mixed Race/Ethnicity
Other

**Employment status:**
Full-time
Part-time
Unemployed
Odd jobs
Student

**Insurance:**
DC Medicaid
MD MCHIP
MD Medical Assistance for Families (MA4F)
VA Medicaid/CHIP
Other State Medicaid
Private or employer-sponsored health insurance
No Insurance
Don't Know

**Income:**
Under $9,999 (less than $192/week)
$10,000-$14,999 ($192-287/week)
$15,000-19,999 ($288-384/week)
$20,000-24,999 ($385-480/week)
$25,000-29,999 ($481-576/week)
$30,000-34,999 ($577-672/week)
$35,000-39,000 ($673-768/week)
$40,000-44,999 ($769-864/week)
$45,000-49,999 ($865-961/week)
$50,000-$59,999 ($962-1153/week)
$60,000-$74,999 ($1154-1441/week)
$75,000 or more/year ($1442 or more/week)

**Referred by:**
Clinic
Crime Victim Advocacy Center
DCAF Website or Social Media
Domestic Violence Crisis/Intervention Org
Family Member
Friend
Google/Web Search
Homeless Shelter
Legal Clinic
NAF
NNAF
Other Abortion Fund
Previous Patient
School
Sexual Assault Crisis Org
Youth Outreach

**Special Circumstances:**
Domestic Violence
Fetal Anomaly
Homeless
Immigrant
Incest
Maternal Health
Other
Rape
Undocumented/Non-Citizen

**Comment by mebates** [comment]
:star:

**Comment by colinxfleming** [comment]
For the 'Other's here, are we good to account for those in the notes section or is it necessary to have a freeform option for Special Circumstances and Race/Ethnicity?

**Comment by colinxfleming** [comment]
Also, let's make sure these are represented in a helper file, in the event that we need to reuse them elsewhere.

**Comment by colinxfleming** [comment]
Let's make sure we update `update_patient_info_test` when we implement this as well.
