### ISSUE TITLE
SUNDAY PLEDGE VALIDATION: Pledge submission validation and error checks

### ISSUE THREAD

**Issue by adinneen** [colinxfleming/dcaf_case_management#203]
@lwaldsc The only error check required is when the person goes to submit the pledge.  Required fields there include: 

A nice to have would also be error checks for clinics.  Some clinics have strict guidelines for how along in a pregnancy a person is.  Would be great to build that logic in so a case worker knows instantly if that person will be eligible at that clinic.

**Comment by colinxfleming** [comment]
We should be able to wire up fairly exhaustive validation as necessary. We can keep working on this issue until we have it documented.

**Comment by colinxfleming** [comment]
w/r/t error checks for clinics, are there circumstances where someone would get seen anyway even if they're like a day or two after the limit? Maybe the right way to handle is to flash a warning message to the effect of 'Susie Everywoman is 13 weeks but this clinic only goes up to 12, are you SURE you want to send that pledge?' and let them do it after checking a box? 

We can validate pretty hard without too much problem, including clinic LMPs versus patient's LMP, but want to make sure that we don't accidentally tie our CMs' hands.

**Comment by colinxfleming** [comment]
@adinneen I'm going to mark this as Question until we find some way to operationalize it (e.g. 'validate pledge based on clinic weeks limit') or spin it into subtasks. Sound good?

**Comment by colinxfleming** [comment]
Re: @lwaldsc @NerdyGirl537 

We're both fine with the warning popup and confirmation checkbox. Brought up long term maintenance issues with changing of LMP limits, but should be relatively easy change on an admin level if this happens. As long as there is a simple workaround for CMs, think it might be useful to have some sort of warning.

**Comment by mebates** [comment]
Bumping this up. Do we have required fields for submission?

**Comment by colinxfleming** [comment]
topping -- @NerdyGirl537 @lwaldsc what are the required fields for submission? Definitely we need name, pledge amount, clinic, appointment date. Do we also need abortion cost, patient contribution, or any of the patient information fields like insurance, income, etc?

**Comment by NerdyGirl537** [comment]
We only need what you listed.  We don't include total cost (often an estimate until the day of the procedure), how much is coming from the patient (may change; also we may not have it if coordinating directly with another fund), and definitely none of the patient information.

**Comment by colinxfleming** [comment]
Perf. Let's add a model condition as follows:

A pregnancy should not be allowed to create a pledge UNLESS the following fields are present:
* Patient name
* pledge amount from DCAF
* Clinic name
* Appointment date

In the event that any of these fields are nil, we should return an error.

**Comment by colinxfleming** [comment]
Dropping from MVP and backlogging

**Comment by NerdyGirl537** [comment]
CM on 8/22  sent three pledges and two had no appointment date and one had the wrong appointment date.  She also had one with an appointment date showing not matching what was in her notes and one that looks like it should have an appointment date (cost of procedure/clinic entered) but no appointment date in the field.

**Comment by mebates** [comment]
This is at the top of our Release 2 prioritized backlog. Can we bump this up in priority? Anything else needed from CMs or UX?

**Comment by colinxfleming** [comment]
Tossing it in sprint 12. I'll write a plan of attack for it shortly.

**Comment by colinxfleming** [comment]
Plan of attack:

Backend:
- [ ] Validate `Prengnacy#pledge_sent` such that someone cannot mark it true if the following are null:
* Name
* DCAF soft Pledge amount
* Clinic
* Appointment date

Frontend ( @mebates please approve): 
- [ ] Add an `errors` section to the `Create Pledge` modal with (an MVP of this that does it based on moment of page load is fine)
- [ ] Prevent people from clicking continue if the fields above are not filled out (an MVP of this that does it based on page load is fine, bonus points if you check dynamically)

Test:
- [ ] Model tests confirming validation behavior
- [ ] An integration test confirming frontend behavior

**Comment by mebates** [comment]
Sounds great to me @colinxfleming !

**Comment by colinxfleming** [comment]
I think this is resolved by the work in #742 and #739 . 

@mebates can you approve? Example below. 

![image](https://cloud.githubusercontent.com/assets/3866868/20471956/a96046e4-af83-11e6-84b9-7cc6eaad151f.png)

**Comment by mebates** [comment]
Looks good!
