### ISSUE TITLE
Collapse several partials into `table_content` partial in dashboards views

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#214]
Small bad behavior that we should clean up -- calling the search action is currently rendering a partial called `search_results`, which includes `table_content` for the data. Call list includes the same table headers information, and also includes `table_content` for the data. And urgent cases includes the SAME table headers information, and ALSO includes `table_content` for the data. 

We should roll these into one single `table_content` partial to not drive our designers crazy.

**Comment by charleshuang80** [comment]
working on this right now also

**Comment by colinxfleming** [comment]
Resolved in #250 !
