### ISSUE TITLE
Restrict phone fields to a single number

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#225]
@NerdyGirl537 and @lwaldsc flagged that the phone number fields can take unlimited lengths, which could lead to unwanted

We should fix by limiting the length of the field in the relevant model, and add a unit test to confirm the validation.

**Comment by colinxfleming** [comment]
This is a pretty straightforward change -- marking as `beginner friendly`. The `Patient` and `Pregnancy` models have phone fields.

**Comment by colinxfleming** [comment]
I think @ewiggins has staked a claim to this!

**Comment by ewiggins** [comment]
I have!
