### ISSUE TITLE
Add "my dashboard" link in top nav bar on patient screens

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#227]
@NerdyGirl537 and @lwaldsc said on Monday that it wasn't terribly clear to them how to get from the pregnancy edit form back to the main dashboard. Is there some merit to adding some explicit nav text in the top bar?

**Comment by colinxfleming** [comment]
Still needs design work. What will it say and where will it go?

**Comment by colinxfleming** [comment]
(Changing this to a design issue.)

**Comment by mebates** [comment]
Adding this to the wireframes and invisio soon:

![screen shot 2016-04-17 at 4 03 20 pm](https://cloud.githubusercontent.com/assets/6223901/14589673/f7bde39c-04b5-11e6-8be3-8e2f435400a0.png)

**Comment by colinxfleming** [comment]
Turned into dev issues and just waiting on tests at this point -- I think we can consider this resolved from a UX perspective.
