### ISSUE TITLE
Issues with adding patients to a call list from urgent pregnancies

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#228]
@lwaldsc and @NerdyGirl537 had some issues getting patients to add to the call list properly, especially from the urgent pregnancies form. Here are the specific issues they ran into and steps to troubleshoot from. 

* Adding pt from call search does not add, only replaces:
  URL: dashboard
  Thing I don't like: Adding from the urgent cases does not properly populate the call log
  Thing I would like better: Adding from either urgent cases or search properly appends to the call log

* Call list is not maintained when returning to main screen from PT screen from link at top left:
  URL: edit page (to dashboard)
  Thing I don't like: When return to call list from PT info, urgent case has fallen off call list
  Thing I would like better: Keep urgent calls on call list when returning to main screen

**Comment by colinxfleming** [comment]
I've been thinking about this and I wonder if this is an issue with the relationship btwn pregnancy and user being `has_many : belongs_to`? Should this be something like `has_many : belongs_to_many` ?

**Comment by colinxfleming** [comment]
Bumping this into sprint 5.

**Comment by colinxfleming** [comment]
Want to confirm that my guess was right: a patient can only be on one person's call list at a time. If user one has patients a and b on a call list, and user two adds patient b to theirs, patient b disappears from user ones call list. 

Won't be an issue for early stage stuff since the mvp will be single user, but we will Def need to resolve. E

**Comment by Kevin-Wei** [comment]
Will try this guy
