### ISSUE TITLE
more extensive readme - DCAF 101

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#23]
We need to be able to quickly explain DCAF's workflow to new team members. We'll use the User Flow #5 but need more of a checklist model of things to cover

**Comment by colinxfleming** [comment]
@lwaldsc @NerdyGirl537 if you've got capacity can you tackle a draft of this with me over the next week or so? I might enlist someone else from the CM working group as well.

**Comment by colinxfleming** [comment]
After a discussion with @mebates it seems like a good idea to turn this into a wiki page. I popped it into https://github.com/colinxfleming/dcaf_case_management/wiki/DCAF-101. 

Leaving open for the time being until we have a chance to discuss.

**Comment by mebates** [comment]
Looks like a good start - kind of confusing with all of the abbreviations; maybe we can take a plain language pass at it.

**Comment by colinxfleming** [comment]
@mebates good call on abbreviations and the need for a plain language pass. I'll see if I can take a whack at this in the off week, I think having this primer would really speed up onboarding.

**Comment by lwaldsc** [comment]
Yeah. This was def just a quick outline draft. I can mess around slash flesh it out as well.
