### ISSUE TITLE
Organize release planning session - JUNE 2, 6PM, MLK LIBRARY DIGITAL COMMONS ROOM 5

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#237]
Doodle to pick a date: http://doodle.com/poll/b4r92bdes4cgdey7

Brain dump of things to discuss (please add to this in this issue!):
*Release 1*
- Where will the application live? How will users find it?
- What is it called?
- Who can create an account and how do we control that?
- First user should be @lwaldsc, possibly starting on July 11 
- UXers can sit with Lisa on one or more nights to observe how she uses the tool
- 1 sprint to respond to problems from pilot
- Expand pilot to one full line and train new CM users
- At release, we should share our work and how our awesome, diverse team worked (tweets, blog post)

*After Release 1*
- Build accountant / audit features
- Build case manager lead features
- Budgeting features
- How can we share the system with other abortion funds?
- How can we neutralize the system for other case management systems to use?

**Comment by colinxfleming** [comment]
Our winner for the date is **June 2**! We'll be at MLK library room 5.

**Comment by mebates** [comment]
@colinxfleming @lwaldsc @adinneen - Please take a look at this issue in the next week and add the things you're interested in exploring. How should we structure this? I think it would be great if one outcome of this meeting was a group of epics, features, and stories for the next release. I'm hoping we can spend at least half of our time on that topic! 

We will also be able to quick-follow our release planning session with some action at the National Day for Civic Hacking on June 4. I plan to be there! 

We should also make sure we document this meeting well!

**Comment by colinxfleming** [comment]
I think having a group of epics/features/stories for next release is an A+ idea.

Here's the questions I'll want to make sure we address:

General administrativa:
* At some point we'll need to get information we capture during this week back into the Excel doc. What's the least annoying way to do that?
* How do we provide technical coverage for @lwaldsc ? It sounds like a design/UX person will be sitting with her part of the time; should we have a member of the backend team there as well?
* Should we plan on responsively fixing issues on the fly? e.g. if something doesn't work, should we aim to have a technical hotfix in place by the time @lwaldsc is settling in to make calls the following day?

Technical stuff (mostly security stuff):
** Should we move our auth to a service like auth0, and stop using devise?
** We should DEFINITELY turn off account registration, which is currently open as we continue to test. Let's make sure we remember to do that.
** Can we keep deploying on heroku? Should we move to another provider, like google cloud platform or something?
** Should we set up a security integration service like Hakiri, if we think Brakeman isn't enough? 
** Should we set up a monitoring service like New Relic? 
** We've punted on clinics-related features for now. When do we start really working these in?

**Comment by mebates** [comment]
Supplies needed for Thursday: sticky notes, sharpies, notecards, blank 8.5x11 paper, tape, whiteboard markers

Great group of questions @colinxfleming. I love the idea of hot fixes for Lisa, and backends attending the usability testing. I think we can just timebox R1 discussion to the first 90 mins, and R2 to the second 90 mins.

Is it 6-9 pm? Can we bring food in? I'm guessing the answer is no; any ideas for how to keep people fed and happy?

Can the DCAF accountant come? And any other board members who were there for initial planning stuff? If we have these folks, we should start with a 5 minute demo of what we've built so far.

**Comment by mebates** [comment]
Draft agenda:

6:00-6:20 - Introductions, demo of product so far
6:20-6:50 - Release and security (How to find it, who can find it, who can register, security)
6:50-7:30 - Usability testing plan with @lwaldsc, plan for release to a single DCAF line
7:30-7:45 - BREAK
7:45-8:30 - Epic and feature exercise for R2 (Paired user story writing, sorting, voting). Determine MVP for release to all DCAF users, elimination of spreadsheet use
8:30-8:45 - Future of case management tool (Share with other abortion funds? Neutralize the system for other case management systems to use?)
8:45-9:00 - Inevitable overage time and next steps

**Comment by colinxfleming** [comment]
Yep, it's 6-9pm. I'll ask about bringing some snacks to keep us chipper. 

I'll also get out the ask to the DCAF board team -- I think Meghan and Crofoot esp might have some valuable insights.

**Comment by colinxfleming** [comment]
(Tapping in the core team, also: @NerdyGirl537 @Kevin-Wei @charleshuang80 @Nico-ehs @rebeccaestes @ewiggins @drownedout @CamLatimer @ajohnson052 @clarissastark @ashlynnpai @mchelen )

**Comment by colinxfleming** [comment]
Just emailed DCAF stakeholders to request their presence. Also got clearance from our accountant to purchase things we need, so I'll take stock of what I have laying around and then we can invest in the remainder.

**Comment by lwaldsc** [comment]
"At some point we'll need to get information we capture during this week back into the Excel doc. What's the least annoying way to do that?"

Just to get some stuff out of the way ahead of time, I was planning on using both the excel sheet and DCAF system at the same time anyway. I'm sure there will be some tech hiccups along the way, but calls still need to be made. The new AbortBot 5000 will be my primary, obviously, but I can record everything in the Excel as I go. This will take care of having to worry about data at the end of the shift as well.

**Comment by ewiggins** [comment]
Do we have a template for creating the user stories and epics? I can create or find simple templates ahead of the meeting for standardization when creating them.

**Comment by colinxfleming** [comment]
@ewiggins -- @mebates is our expert on that process. Mollie will you flag for @ewiggins if you'd like a second set of hands on that process before tomorrow?

**Comment by colinxfleming** [comment]
Three points of housekeeping: 

a) I got a hard no from the library on food, so probably grab something on your way to the library. Sorry, everyone. 

b) I got clearance from DCAF's accountant to buy supplies, so I'll grab the hardware tomorrow morning on my way to work. 

c) Megan F from DCAF's case manager team will be joining us! (She's not on github that I know of, so she isn't tagged here.)

**Comment by mebates** [comment]
@ewiggins I'm not sure what you mean by templates! Usually for user stories we just use a sentence: As a X, I want to X, so that I can X. For epics, we just look for themes to the user stories. If you have another strategy or template I would love to hear about it!

**Comment by colinxfleming** [comment]
The result of this was a game plan between now and launch -- gameplans for sprints before initial showtime, and logging more long-term plans. These are represented in https://github.com/colinxfleming/dcaf_case_management/wiki .

@mebates straight killed it at organizing this session. 

Closing it out!
