### ISSUE TITLE
CALL LIST: Add calls completed partial to main dashboard view

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#240]
After a CM makes a call, we're going to want to move that call to a Calls Completed section, so a CM can keep track. 

To that end, let's add a new partial similar to `call_list` to the main dashboard view.

**Comment by colinxfleming** [comment]
Until #241 is ready for prime time, go ahead and populate the `table_content` partial with `current_user.pregnancies`.

**Comment by charleshuang80** [comment]
taking a look at this

**Comment by colinxfleming** [comment]
Resolved in #250 !
