### ISSUE TITLE
CALL LIST: Add attribute to pregnancy to indicate whether they've been called in session

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#241]
So that a CM can tell if they've called someone, we need to be able to fill out the call list partial as detailed in #240. 

Here's a minimal implementation: Let's say that if: 
* someone has a call from the `current_user` 
* that is less than 8 hours old, 
* AND they would otherwise be in the call list, 

then they should show up in Calls Completed. 

We should accomplish this with an inferred field on the Pregnancy or Patient model.

**Comment by colinxfleming** [comment]
For code clarity, we may also want to add a helper method to the User model that cleanly separates people who have and haven't been called on a call list. Call this the gold medal version!

**Comment by charleshuang80** [comment]
working on this now during sprint 6
