### ISSUE TITLE
DASH: Add integration test to confirm Dashboard present on non-dashboard pages

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#248]
Using @mebates 's designs as a guide: 

![image](https://cloud.githubusercontent.com/assets/3866868/14590308/1a7fc526-04c5-11e6-8379-9ab2c323f903.png)

If a user is logged in and not on the dashboards controller, we should include a link up in the top right next to the username to head back to the `authenticated_root_url`.

We can make these changes in `app/views/layouts/_navigation_links.html.erb`.

**Comment by mebates** [comment]
And if all three links at the top can now be purple, even better! 💜

**Comment by colinxfleming** [comment]
@CamLatimer resolved primary issue in #251; changing this to an integration test to confirm behavior.

**Comment by colinxfleming** [comment]
This is a good chance to take a stab at writing a capybara integration test if you've never done it before! Using the capybara API, you'll use a fake web browser to basically do the following: 

* Visit the main dashboard
* Assert that the Dashboard link isn't there 
* Visit a patient's edit URL 
* Assert that the dashboard link is there
* Click the Dashboard link
* Assert that you're sent to the main dashboard
* Assert that the Dashboard link is gone again

Switching the tag to minitest, but keeping the beginner friendly tag.

**Comment by colinxfleming** [comment]
Resolved in #272 by @ashlynnpai ! Closing.
