### ISSUE TITLE
Put 'clone and go' guide in the readme

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#25]
Should have step by step instructions to cloning and getting started for mac and pc environments. 

In other words: It's my first day at code for dc, I've got the readme open, what do I need to install and set up to be able to run a local server and start wrenching around?

**Comment by Kevin-Wei** [comment]
installing homebrew on mac's
and using [homebrew](http://brew.sh/) to install [mongo](https://docs.mongodb.org/manual/tutorial/install-mongodb-on-os-x/) and [rbenv](https://github.com/rbenv/rbenv).

Once mongo and the project is installed with bundler.

Mac users need to `$ mkdir /data/db` and 
`$ whoami`
`username`
`$ sudo chown username /data/db`
