### ISSUE TITLE
DASH: hook up dashboard 'week of' to current date

### ISSUE THREAD

**Issue by charleshuang80** [colinxfleming/dcaf_case_management#256]
Dashboard overview has a 'Week of' title that is currently static. Should be hooked up to reflect actual week of the current date. A dashboard helper method seems like one good option.

**Comment by charleshuang80** [comment]
@colinxfleming, wanted to add 'frontend' and 'beginner friendly' tags to this

**Comment by colinxfleming** [comment]
@charleshuang80 💯

**Comment by sco-bo** [comment]
Hey @colinxfleming and @charleshuang80! I have built a helper method for this and it is working on my local branch. Currently, it is set for the beginning of the week to be Monday and the end of the week to be Sunday (a 7 day week). I can tweak it so it is instead written for a 5 day 'work week' if that's more helpful. Let me know and I can make the necessary changes, write up a quick test and submit a pull request!

**Comment by colinxfleming** [comment]
Hey man! Thanks for putting in the work on this!

DCAF does weeks of Monday Sunday, so this should work without incident. I
would say go for it - I'll keep an eye out for the pull request!

Thanks a ton!

**Comment by sco-bo** [comment]
Ok great! Finished writing the test so you should be seeing a PR soon. I'm relatively new to ruby/rails so feel free to offer any feedback on what I might be able to improve. Happy to help!

**Comment by colinxfleming** [comment]
Happy to have you, Scott! Welcome aboard!
