### ISSUE TITLE
PLEDGE: Convert AI design to PDF

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#258]
The design for the pledge modal that @adinneen and @NerdyGirl537 worked on is currently sitting in https://github.com/colinxfleming/dcaf_case_management/blob/master/_design/DCAFwireframe051816.ai -- can we get this converted to a PDF so it doesn't require illustrator to view?

**Comment by mebates** [comment]
boom :boom: 
https://github.com/colinxfleming/dcaf_case_management/blob/master/_design/DCAF_SubmitPledge.pdf
