### ISSUE TITLE
PLEDGE: Create modal view for DCAF pledge

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#259]
Using the pledge designs in https://github.com/colinxfleming/dcaf_case_management/blob/master/_design/DCAFwireframe051816.ai (or its pdf equivalent) as a guide, create a partial called `app/views/_pledge.html.erb` that contains a form we can use to log a pledge from DCAF.

**Comment by rebeccaestes** [comment]
I'll start this

**Comment by mebates** [comment]
See designs on issue #16 !!!
