### ISSUE TITLE
PLEDGE: Wire up the modal to send pledge

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#261]
Once we have a modal, let's wire it up so that it pops up when you hit the big Submit Pledge button. 

NOTE: Depends on #259  being completed.

**Comment by charleshuang80** [comment]
I will be working on this.

Pledge modal should pull information from the Pregnancy attributes. 
* optional: trigger save
* Add form to app/views/pregnancies/new_pledge that creates and saves a new pledge associated with that pregnancy
** pledge should be of pledge_type final_dcaf, other information should populate from the pregnancy object
** pledge amount should be hard set to $100, until further notice from @colinxfleming
