### ISSUE TITLE
PT CREATE: Wire up dashboards#search to return the create a patient partial if there are zero results

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#265]
Right now, the create a patient partial is sitting in `app/views/patients/_new_patient.html.erb` but isn't hooked into anything. Let's adjust the `DashboardsController#search` method to return that partial if a search returns zero results. 

We'll also want an integration test for this, and a controller test for this.

**Comment by lankyfrenchman** [comment]
Hey! I'm new and would love to take a stab at this one. Not sure if you folks assign tickets or anything like that :)

**Comment by lankyfrenchman** [comment]
@colinxfleming There's a pre-existing field called :last_menstrual_period_lmp_type that doesn't seem to exist anywhere else in the app. What field should be used here?

**Comment by lankyfrenchman** [comment]
cc @ajohnson052, we've both run into this on this form for different topics.
