### ISSUE TITLE
PT CREATE: PatientsController#create should create both a patient and a pregnancy from the payload

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#266]
Our data model associates a pregnancy with a patient object. As such, let's alter `PatientsController#create` so that it creates a Patient and then creates a dependent Pregnancy object as well. 

We'll also want to create an integration test for this, and a controller test for this.

**Comment by ajohnson052** [comment]
I'll take a look at this one!
