### ISSUE TITLE
Change name labels to include first and last on forms

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#268]
https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-for-everyone/04-inclusive-forms.md

In my head, we only new the first name of the patient. BUT, I have re-learned that we need first and last. However, I think it's good to have just one input box for name, per the link above. 

Should we add additional helper copy to indicate that we need both names?

**Comment by colinxfleming** [comment]
I've never seen that inclusive forms doc before and I kinda love it! 

I think that adding helper copy to indicate that we need both names is a great. 

(This is partially represented in #55 too.)

**Comment by colinxfleming** [comment]
@mebates what are the next steps here? CM weigh in, frontend changes in the pregnancy view form, something else?

**Comment by mebates** [comment]
How about just changing the text box label, like this?

![delete](https://cloud.githubusercontent.com/assets/6223901/15522902/cd494f8e-21e3-11e6-9964-d18c781fe542.PNG)

**Comment by colinxfleming** [comment]
Perf! Retagging as frontend, this is a pretty straightforward change. 

Whoever takes this on will want to pop into the form field and adjust the label attribute in that particular instance. Refer to the docs in the `rails-bootstrap-forms` gem we use here: https://github.com/bootstrap-ruby/rails-bootstrap-forms

**Comment by colinxfleming** [comment]
There are two places where we'll need to fix this, most likely: the `app/views/pregnancies/_patient_dashboard` view, and the `app/views/pregnancies/_new_patient` view. I think that's the only place we plug in names.
