### ISSUE TITLE
Models: Turn auditability into a concern, instead of having it separately in every model

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#277]
Here is an opportunity to use the Rails feature `concerns` for someone interested in taking a stab!

In just about every one of our models, we have the following code:

```
  # History and auditing
  track_history on: fields.keys + [:updated_by_id],
                version_field: :version,
                track_create: true,
                track_update: true,
                track_destroy: true
  mongoid_userstamp user_model: 'User'
```

Rails has a feature in Rails 4 called `Concerns` which are basically helpers for models. Here's an SO thread about them: http://stackoverflow.com/questions/14541823/how-to-use-concerns-in-rails-4

In a nutshell, we want the code above popped into a Concern called `Auditable`, and instead of having the same seven lines of code in every model, we want `includes Auditable` to do the same thing.

This will keep us from driving ourselves crazy if we ever have to change any of that code.

**Comment by ewiggins** [comment]
@colinxfleming I'm going to work on this! Seems like a fun mini project for the larger project :) p.s. I just took a GitHub tutorial so I'm a pretty much a pro. lol 💯

**Comment by colinxfleming** [comment]
Awesome, thanks Elisheba! Let me know if you run into any snags or need a
hand with the documentation.

**Comment by ewiggins** [comment]
@colinxfleming I give up on this. Maybe some other smart beginner can figure it out :) I'm going to work on something else.

**Comment by colinxfleming** [comment]
@ewiggins I'm gonna take yr PR and run with it! Sorry that this turned out to be way more of a pain in the ass than I thought it was going to be.

**Comment by colinxfleming** [comment]
Turns out concerns are a lying demon hellchild. Closing as a wontfix.

**Comment by ewiggins** [comment]
I know right! I don't usually quit things, but I was starting to hate concerns with a passion!
