### ISSUE TITLE
New pregnancy create form: Change default to current date

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#279]
Rolling into one issue since these both came out of @ajohnson052 's pull request in #273  -- 

Here's our form as it stands now -- 

<img width="984" alt="screen shot 2016-05-19 at 10 38 31 am" src="https://cloud.githubusercontent.com/assets/3866868/15397558/a0d222a2-1dae-11e6-8f69-0492db669d38.png">

An open question here: Is there a meaningful difference between initial call date and the day we actually log them in our system? If there is, or if initial call date ever shifts, then we should keep them separate, but otherwise we can probably use the `created_at` timestamp. 

@lwaldsc @NerdyGirl537 can you weigh in on your preferences here from a CM perspective? Should we keep `initial_call_date` as a field or can we infer it based on when we enter them into our system?

**Comment by NerdyGirl537** [comment]
I can see it either way. I usually log all my patients before calling them
so inference would be fine for me.
Jenn

**Comment by colinxfleming** [comment]
Let's do this as a medium -- let's keep initial call date and set it to the current date by default, but still have it editable.

**Comment by colinxfleming** [comment]
Renaming and removing the `question` tag, now that we have a game plan.

**Comment by Nico-ehs** [comment]
Taking this tonight.

**Comment by colinxfleming** [comment]
Resolved by @Nico-ehs in #288 and its adjacent PR
