### ISSUE TITLE
New pregnancy form: Adjust LMP to be weeks/months dropdowns instead of open text field

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#280]
Raised in #273 -- Our current form in `views/pregnancies/_new_pregnancy` is as follows:

<img width="984" alt="screen shot 2016-05-19 at 10 38 31 am" src="https://cloud.githubusercontent.com/assets/3866868/15397926/d0eb22d0-1daf-11e6-8695-88700530d087.png">

Let's change the LMP representation here to look more like what's in `views/pregnancies/_patient_dashboard` in the edit view, where weeks and days are separate dropdowns. This will ensure we stay consistent and avoid confusion on data entry.

**Comment by CamLatimer** [comment]
I'll get it on it!
