### ISSUE TITLE
Remove blue highlight, add right-facing caret, increase font-size in pregnancies/_menu.html.erb

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#303]
From @mebates in #195 - 

Currently, in the pregnancy edit view, you can see a full blue highlight over `Abortion Information`:

<img width="1111" alt="screen shot 2016-05-28 at 5 57 21 pm" src="https://cloud.githubusercontent.com/assets/3866868/15630197/b8a75446-24fd-11e6-99d9-374e28e28c79.png">

We should adjust this to match the designs, which feature a purple caret instead and no blue highlight: 

<img width="1076" alt="screen shot 2016-05-28 at 5 59 50 pm" src="https://cloud.githubusercontent.com/assets/3866868/15630212/024d9a38-24fe-11e6-81f9-11568ed4f3fb.png">

(See also https://github.com/colinxfleming/dcaf_case_management/blob/master/_design/DCAFwireframe020816.pdf ).

Probably this involves busting into `pregnancies.scss` and editing the `.abortion-left-menu.li.active` styling.

**Comment by colinxfleming** [comment]
Let's feel free to use the `chevron-right` glyphicon here - http://getbootstrap.com/components/#glyphicons

**Comment by mebates** [comment]
Added 'backlog' label as this is non-essential for first release.

**Comment by mebates** [comment]
The left navigation should also be a larger font-size; it is 17 px now and it should be 22 px. Users aren't noticing the left navigation very well.
