### ISSUE TITLE
Properly get Patient Information and Abortion Information into grid system

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#304]
From @mebates in https://github.com/colinxfleming/dcaf_case_management/issues/195#issuecomment-216404608 - 

Our views for Patient Information and Abortion Information on the pregnancy edit page are improperly indented. 

Here is our design for these partials:

![image](https://cloud.githubusercontent.com/assets/3866868/15634043/bec00248-2588-11e6-90d1-1505bf99cb7d.png)

And here is a screenshot of what we have currently: 

<img width="1212" alt="screen shot 2016-05-29 at 10 33 20 am" src="https://cloud.githubusercontent.com/assets/3866868/15634106/099441ca-258a-11e6-813e-8f8a36a3a9c0.png">

In the bottom right section, the actual form fields are indented a little bit. This is the case in both Abortion Information and Patient Information. We should align the form fields in the center column so that they sit underneath their respective headers, like in the designs. 

This is a pretty straightforward fix with some knowledge of the boostrap grid system. These partials are located in `app/views/pregnancies/_abortion_information.html.erb` and `app/views/pregnancies/_patient_information.html.erb`.

**Comment by drownedout** [comment]
I believe I fixed this.
