### ISSUE TITLE
Update designs to incorporate Add to / Remove Call List in the calls to make section

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#305]
Due to a misinterpretation on my part, I understood 'expand note' to mean 'add to or remove from call list'. Right now we have something similar to: 

![screen shot 2016-05-29 at 10 50 40 am](https://cloud.githubusercontent.com/assets/3866868/15634151/36f0c0a2-258b-11e6-8ea0-bf8248f2250e.png)

And from our [designs](https://github.com/colinxfleming/dcaf_case_management/blob/master/_design/DCAFwireframe052416.pdf) -- 

![screen shot 2016-05-29 at 10 52 01 am](https://cloud.githubusercontent.com/assets/3866868/15634165/68399486-258b-11e6-9670-3f8ce884ee6e.png)

**The question as I understand it is this:** The intended workflow as I understand it now is that you can add people to call list *only* from the search function, and can't remove them. We can roll it back with almost no hassle at all. **Does having the Add to / Remove From Call List buttons as we have them now add anything, or should we follow the designs and take it out?**

Seeking your thoughts @lwaldsc @NerdyGirl537 @mebates @adinneen  !

**Comment by lwaldsc** [comment]
Keep the 'remove' function.

**Comment by colinxfleming** [comment]
Tagging in UX -- should we update these designs to reflect this? If not, let's close.

**Comment by colinxfleming** [comment]
^^ @mebates @adinneen

**Comment by mebates** [comment]
Yes we need to work on this. It doesn't make sense as it is now! Thursday!

**Comment by colinxfleming** [comment]
Bumping issue title and removing `question` tag!

**Comment by mebates** [comment]
I took another look at this and I think it's fine as is.
