### ISSUE TITLE
Adjust Call Now modal to match the designs

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#307]
Here's our call now modal: 

![screen shot 2016-05-29 at 11 14 38 am](https://cloud.githubusercontent.com/assets/3866868/15634301/903e02a2-258e-11e6-9b61-ef24fccd5488.png)

And here's the design:

![screen shot 2016-05-29 at 11 15 04 am](https://cloud.githubusercontent.com/assets/3866868/15634302/9f34c412-258e-11e6-9ca2-0e6a4fcc8276.png)

Note the slew of differences, such as the size of it, the spacing, and the colors. Let's adjust our modal (located in `app/views/calls/_new_call.html.erb`) to match the designs.

**Comment by colinxfleming** [comment]
I think this is a good issue for someone comfortable with frontend styling to take a stab at! Marking as beginner friendly.

**Comment by dfelsent** [comment]
I'm going to take this issue.

**Comment by dfelsent** [comment]
Submitted pull requests for designs. **But please note:** "Do not leave patient a voicemail" does not appear to be an option in this modal.
