### ISSUE TITLE
Create notes with ajax instead of synchronously

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#308]
* **What screen are you on?** Pregnancy edit page, specifically the notes partial

* **What are you trying to do?** Create a new note

* **What should be happening?** It should create a new note with javascript, and not reload the page

* **What's happening instead?** It's reloading the page.

The stuff to edit is in `NotesController#create`, specifically L9-14. We'll want to make that look more like the update method and wire it to handle an ajax request. We'll also want to adjust the notes form in `app/views/pregnancies/_notes.html.erb` to handle the remote call.

**Comment by ajohnson052** [comment]
I'll take a look at this one!

**Comment by ajohnson052** [comment]
Wasn't able to make any progress on this tonight after all :( Anyone should feel free to pick it up!
