### ISSUE TITLE
Remove datepicker up-down arrows and the clear X from initial call date field

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#309]
From @mebates in https://github.com/colinxfleming/dcaf_case_management/issues/195#issuecomment-221441155 -- this is kinda uggs and cutting off the actual date:

![image](https://cloud.githubusercontent.com/assets/3866868/15634384/8d5c1c66-2590-11e6-9499-274faed6a5c3.png)

Space is already kind of at a premium there, so let's take the clear `x` and the up-down arrows out of that form field. May involve changing the field datatype in the view or making some other adjustments. 

The code is in `app/views/pregnancies/_new_pregnancy.html.erb`.

**Comment by sco-bo** [comment]
I have a solution for this and it's working in Chrome. Oddly enough, this issue doesn't seem to be happening in Firefox, however the LMP fields don't look right in Firefox ¯\_(ツ)_/¯. I can take a look at that too if you think it would be worth opening another issue. I haven't tried it in IE but maybe someone here has access to IE?
