### ISSUE TITLE
Create a favicon!

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#311]
I have had to work around some pretty weird test failures before, but one of them today happened to be 'create a favicon'. I dropped in THRILLHOUSE.GIF, but we should remember to whip up a real one.

Please enjoy THRILLHOUSE.GIF in the meantime:

![thrillhouse1](https://cloud.githubusercontent.com/assets/3866868/15638628/31513d92-25f0-11e6-930d-49b0df72a1ee.gif)

**Comment by drownedout** [comment]
Added the following as the favicon.

https://pbs.twimg.com/profile_images/711718930419556352/0pS4PuWX.jpg

**Comment by colinxfleming** [comment]
@drownedout whipped this up, which was very kind of him. 

Does someone have the ability to add it to our assets? Simple and straightforward, just replace the current image in `public/favicon.ico`.

**Comment by mchelen** [comment]
@colinxfleming what size .ico do we want, 32x32? are we worrying about multiple sizes? https://msdn.microsoft.com/library/gg491740(v=vs.85).aspx

**Comment by colinxfleming** [comment]
32x32 is fine for now! If we need other sizes we can worry about it later

**Comment by jayzmiles** [comment]
Hey Group - I left the letters off the logo to avoid the legibility issues at favicon sizes.

**Comment by mchelen** [comment]
I like it!

**Comment by colinxfleming** [comment]
Resolved by #582
