### ISSUE TITLE
Make search cast a wider net

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#318]
Right now, our search code casts a pretty strict net, requiring someone to enter in exactly what's in database to retrieve a record. 

Here are a few ways I'd like to loosen it before release:

* Make it hyphen agnostic (e.g. when searching for '111-222-3333', it'll find the record if '1112223333' is entered into the form too
* Make it case insensitive (e.g. 'susie everyteen' will return the record for Susie Everyteen)

**Comment by colinxfleming** [comment]
This code lives in `app/models/patient.rb`

**Comment by colinxfleming** [comment]
Tagging in @katsdc !

**Comment by sco-bo** [comment]
may try to take a stab at this unless others are working on it

**Comment by KatSDC** [comment]
Sorry I should have commented, but I am working on this!

**Comment by colinxfleming** [comment]
Hey @KatSDC, wanted to check in on this -- going okay? Anything I can help with/

**Comment by KatSDC** [comment]
@colinxfleming Yes actually I encountered another error once I upgraded Rails that was resolved by also altering the output of the array with the to_s method. So I'm happy to resubmit with the clearer name. Additionally, I was able to resolve the order of the changelog for issue #403. Would you like me to submit that along with the updates to the patient model? Or should I save that for a different pull request?
