### ISSUE TITLE
Investigate 2-factor auth implementations with Devise

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#323]
Raised by @stvnrlly in slack -- is this a feasible thing to implement? Considerations off the top of my head:

a) cost (but only if it's really outrageously expensive, as DCAF has some money to burn on this and we're way under budget!)
b) support (we have a couple older volunteers who have a hard time with computers sometimes) 
c) implementation (devise extension? something else?)

I'm pro but would like thoughts from the dev squad team, @stvnrlly , @lwaldsc @NerdyGirl537 and at least one CM lead (Meghan?).

**Comment by colinxfleming** [comment]
Email sent to the case management corps. Will report back.

**Comment by colinxfleming** [comment]
Case management team consensus is that there's a place for a limited implementation of this -- something like a 'log in with two factor the first time and then have it recognize the device after that for the next n days'. Kinda like how with google 2fa, you can check a box and have it remember you for the next 30 days or whatever. I've renamed the issue accordingly. 

I'm sure there are devise modules we can install here, or maybe external solutions. The current task here is to investigate our options and see what would be a good fit for us.

**Comment by colinxfleming** [comment]
A pair of 2fa devise extensions:
* https://github.com/Houdini/two_factor_authentication
* https://github.com/tinfoil/devise-two-factor

**Comment by DarthHater** [comment]
After some looking at this, if we want a free solution, the best way forward seems to be using auth0 or some analog to use SSO, and then using Google. Users can then turn on 2FA on their Google Account and the DCAF effectively uses two factor auth.
