### ISSUE TITLE
Run thru 18f 'Before you ship' guide

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#324]
https://pages.18f.gov/before-you-ship/

thanks @stvnrlly !

**Comment by colinxfleming** [comment]
And the OWASP guide! https://www.owasp.org/index.php/Ruby_on_Rails_Cheatsheet

**Comment by colinxfleming** [comment]
And probably the NoSQL specific guide: https://www.owasp.org/index.php/Testing_for_NoSQL_injection

**Comment by mebates** [comment]
I'm on this.

**Comment by mebates** [comment]
Okay, took a look and much was over my head! Would be good for a technical team member to review the Security and Infrastructure sections. Most doesn't apply to us but a quick scan through might help us find any obvious things we forgot to think of. It's a great list!

**Comment by colinxfleming** [comment]
Going thru this now and logging action items!

**Comment by colinxfleming** [comment]
#### Compliance
* not relevant to us

#### Technical
* Our launch is planned (dry run, line release, full release, get tore up)
* 508 compliance not relevant at this time
* Our code coverage is great and we should brag about it, so I made a pull request to add in a codecov badge
* We aren't really running an API so that's not relevant
* **No good reason to not install google anaytics, let's do it. I think DCAF has an account, I'll see if I can find the keys.**
* Open source styleguides are probably worth going thru at some point but not right now.

**Comment by colinxfleming** [comment]
#### Security and operations
* **There's a useful link to a scanner tool here - https://pages.18f.gov/before-you-ship/security/dynamic-scanning/ - This also seems useful and rails specific - https://github.com/ankane/secure_rails ** 
* We're all SSL everything (or at least in the process of getting there) 
* No real suggestions about our specific infrastructure (other than 'the feds don't use heroku)

**Comment by colinxfleming** [comment]
More playbooks: 
* **https://playbook.thoughtbot.com/#production**

**Comment by colinxfleming** [comment]
That's all of them -- I'll spin them up into specific issues later.

**Comment by stvnrlly** [comment]
If you run into issues or find improvements, feel free to send them upstream. I know that the team that works on the guide would love that.

**Comment by colinxfleming** [comment]
Will do, @stvnrlly !

Closing out since we've got issues for these now.
