### ISSUE TITLE
Turn off robots.txt

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#329]
No scrapin' for this please!

**Comment by stvnrlly** [comment]
Some good info on best practices in https://en.wikipedia.org/wiki/Robots_exclusion_standard and http://michaeljaylissner.com/posts/2012/01/16/respecting-privacy-while-providing-hundreds-of-thousands-of-public-documents/.

**Comment by colinxfleming** [comment]
Heads up -- this is all set and taken care of! Merging the PR after hacknight tonight.
