### ISSUE TITLE
Set up application layout

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#33]
Thanks to the great work of the design team, we've got some designs! So we should adjust the frontend application layout to account for that. 

The Invision Prototype, which we should try to match, is here: https://projects.invisionapp.com/share/6757W6WFJ

For purposes of testing, you can go to http://localhost:3000/users/sign_up (the devise login pages). 

This ticket has three components: 
* <strike>Editing the master layout partial in `app/views/layouts/application.html.erb` to match the top bar in InVision</strike>
* <strike>Editing `app/cases/index.html.erb` to account for the change in the application layout</strike> (delayed until after sprint 1)
* Gold medal: Where `Sarah Caseworker` appears in the Invision app, have that populate with either the results of `current_user.name` if a user is signed in or a link to the sign in page if not.

**Comment by mebates** [comment]
How should we incorporate a design review into this (or other) issues? Should we?

**Comment by colinxfleming** [comment]
@mebates I'm 100% about doing a design review and iterating on layouts/frontend code. There's a lot of UX expertise and talent on this between you and @adinneen and I don't want to waste any of it. 

Should we do it incrementally on individual components (such as the top bar) as they're rolled out, or should we start doing them after we have kind of the basic views and interactions from the InVision app turned into code?

**Comment by colinxfleming** [comment]
Since design review is a bit of a broader question, I'm going to split it into a separate issue for further discussion, and rack the last bullet in the ticket in the current frontend PR I'm working on. Design review is an A++ flag and I want to make sure it doesn't get buried here.
