### ISSUE TITLE
Schedule dev and UX presence for soft launch 7/11 - 7/13

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#330]
@lwaldsc is taking this for a test drive during her shift 7/11 - 7/13 from 7 pm to 10 pm, and we want to make sure we're supporting her during this time. So we'll want to have a UX team member and dev team member onsite (near Stadium Armory) if possible. 

Responsibilities for the UX team rep are: Observe user to find out what's working and what's not working; take careful notes for the team. [more best practices TK]
Responsibilities for the dev team rep are: To document any errors or misbehaviors that pop up; to provide QA support on app behavior; to alert the rest of the dev team to anything that needs a hotfix. 

Note that DCAF will ask anyone onsite to sign a confidentiality pledge, which is basically summarized as 'don't go blabbing about patient situations to everyone you see', since @lwaldsc will be taking live calls during this time. I'll provide them once we have signups.

#### 7/11
* **DEV**: Colin
* **UX**: Mollie (work trip timing TBD but I will try my hardest to make this work)

#### 7/12
* **DEV**: Colin
* **UX**: Sabrina

#### 7/13
* **DEV**: [your name here!]
* **UX**: Eva

**Comment by mebates** [comment]
* Need a dinner plan for the group
* Need a shared note taking strategy for UX

**Comment by colinxfleming** [comment]
Dinner plan is a good call. I'm more than sure we can either get something comped or get volunteers to cook, I'll get the gears turning on it.

**Comment by colinxfleming** [comment]
I got clearance from the board treasurer to allocate us ~$100 for dinner on these nights, so we're good on that front.

Let's repost this in the slack channel during the next meeting to move this along and get some signups.

**Comment by lwaldsc** [comment]
Just for the record, I have some pretty decent takeout/delivery places around Capital Hill.

**Comment by colinxfleming** [comment]
For team dev: Mostly this will entail being on hand to log any technical problems, and work on hotfixes in the event that anything pops up.

**Comment by colinxfleming** [comment]
This was a raging success! Issues have been spun out of it. Closing.
