### ISSUE TITLE
Add way to mark case completed

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#335]
(placeholder for now -- add model attribute -- should naturally time out or be marked as 'I'm keeping it' -- should include representation of active pregnancy vs inactive pregnancy)

**Comment by colinxfleming** [comment]
@lwaldsc can you live without this for the dry run and just keep tabs on it in the notes? I'm moving to backlog for the time being. 

Tagging in UX since I'm not sure where to pop this attribute in.

**Comment by lwaldsc** [comment]
Yeah. Not a problem. Definitely something we need to tackle, but I can just
indicate it in the excel as well.

**Comment by colinxfleming** [comment]
Resolved in #532
