### ISSUE TITLE
QA: Build list of QA scenarios

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#336]
Before we release the system, we should QA a series of scenarios that we're anticipating that @lwaldsc will need starting on 7/11. Let's use this issue to build the list and affirm that they are working.

**Comment by colinxfleming** [comment]
This is an A+++ flag. We can (and should!) write integration tests for these as well to match, so we don't backslide.

**Comment by colinxfleming** [comment]
We've been incrementally plugging away at these so far as integration tests. Here's what we have so far:

* Main page loads
* Authorization: 
** Logging in successfully
** Logging in unsuccessfully
** Signing out

* Dashboard link should display / hide at appropriate times
* Logging calls
** Modal pops up and has proper information
** Clicking 'I reached the patient' behaves appropriately
** Clicking 'Left voicemail / couldn't reach patient' behaves appropriately

* Creating new patients
* Creating new notes
* Resetting password
* Using search function
** Retrieves record if exists
** Displays new patient if doesn't exist

* Hides DCAF info if you aren't logged in
* Sign up form works
* Updating patient information
* Updating user information

**Comment by colinxfleming** [comment]
We still definitely need to add tests for:
* pledge sending, 
* calls completed section 
* using the audit trail, 
* call list population, 
* persistence of call list behavior, 
* switching between tabs on pregnancy edit view.

That's what we have open issues to write. I've been fairly good about creating issues to test features but I wouldn't be terribly surprised if I've missed a few.

**Comment by mebates** [comment]
@eheintzelman essentially created some great QA tasks in her Usability Test issue #405.

**Comment by colinxfleming** [comment]
I think we can close this out via #405.
