### ISSUE TITLE
Run thru OWASP rails guide

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#359]
https://www.owasp.org/index.php/Ruby_on_Rails_Cheatsheet

**Comment by charleshuang80** [comment]
OWASP was mentioned as a great resource for security issues. As a list of things to/check, this was also mentioned: https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project

**Comment by colinxfleming** [comment]
Moving the OWASP top 10 to its own issue in #378. $$$

**Comment by colinxfleming** [comment]
Running thru the first link. Again, action items in bold:

#### Command injection
* We don't use `eval`, `system`, backtick commands, or `Kernel` in any of our code. We're cool here.

**Comment by colinxfleming** [comment]
#### SQL Injection
* We're safe on this front thanks to our full use of activerecord.

**Comment by colinxfleming** [comment]
#### XSS
* The guide recommends that we take care about sanitizing variables if we use content_tags/html_safe/raw. We're good. 
* It also recommends confirming that the href values of links aren't user-settable (e.g. someone shouldn't be able to set an attribute to `javascript:alert(‘yolo’)` and have an href destination change to that). **I'm less reasonably sure that all our links run off IDs, so I don't think this is a concern, but I'm going to make a ticket to make sure.**

**Comment by colinxfleming** [comment]
The OWASP guide is WAY better than the official rails doc. man.

#### Sessions
* **OWASP recommends using a database-backed session rather than cookie based.** This is something we can probably change with almost no hassle.

**Comment by colinxfleming** [comment]
#### Authentication
A few action items from here:
* **OWASP recommends putting `before_action :authenticate_user` in applicationcontroller.** We might be doing this in effect with our routing (root vs authenticated_root) but should investigate whether or not we need to do it controller-side instead. 
* **Increase password length.** This is settable via `config/initializers/devise.rb` with `config.password_length = x..y` where x and y are ints. 
* **Validate complexity of passwords.** This showed up in the rails security doc but OWASP has an example that I'll put in the other issue.

**Comment by colinxfleming** [comment]
#### Insecure direct object reference
* These are recommendations about setting up pundit. We aren't there yet; no action.

**Comment by colinxfleming** [comment]
#### CSRF
* We use rails defaults. No action here.

**Comment by colinxfleming** [comment]
#### Mass assignment and strong parameters
* We are a strong parameters project. No action item here.

**Comment by colinxfleming** [comment]
#### Redirects
* I think we're good on this front since we don't allow redirecting to arbitrary stuff.

**Comment by colinxfleming** [comment]
#### Dynamic render paths
* We don't do this.

**Comment by colinxfleming** [comment]
#### CORS requests
* We can explore this if we ever move the frontend to react or something. As it is, no action since everything's coming from the domain. 

#### Security related headers
* Rails 4 does this for us; no action. 

#### Business logic bugs
* This is a reminder more than an actionable thing. No action. 

#### Attack surface
* We hardset available routes so we avoid this whole class of issues. No action.

**Comment by colinxfleming** [comment]
#### Sensitive files
* **We should confirm that actual sensitive information is outside of config/mongoid.yml, config/initializers/secret_token.rb, and seeds.rb.

**Comment by colinxfleming** [comment]
#### Encryption
* We wisely didn't roll our own; devise handles these recommendations for us.

**Comment by colinxfleming** [comment]
#### Having a process of updating dependencies
* We're good on this thanks to the security suite we set up, which involves scanning for ruby and gemfile vulnerabilities as part of CI.

**Comment by colinxfleming** [comment]
#### Tools
* There's a gem called `codesake-dawn` which serves as a security analyzer similar to brakeman. **We should install this and add it to our CircleCI checks.**

**Comment by colinxfleming** [comment]
That's the end of this. I'll turn the bold items into issues soonish.

**Comment by colinxfleming** [comment]
Action items are turned into issues! Closing out.
