### ISSUE TITLE
Need 'Voicemail OK?' check box somewhere on the patient page

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#365]
@dfelsent helped me realize that we don't have a 'Voicemail OK?' check box any where on the patient info pages. Can we add the check mark in on the Patient Info page? 

![image](https://cloud.githubusercontent.com/assets/6223901/15950716/5bbbd8b6-2e7f-11e6-8079-8f16cb94df82.png)

**Comment by sco-bo** [comment]
I can take a stab at this unless someone else is working on it

**Comment by sco-bo** [comment]
Where this field currently appears in the `_new_pregnancy` partial there is a note which reads `<!-- TODO add bootstrap toggle -->`. I can go ahead and implement a toggle in both of these spots instead of a checkbox or should I just go ahead with a checkbox?

**Comment by colinxfleming** [comment]
Hey Scott, up to you whether you'd like to handle it in this pr. I'd say
that since we don't really need it for MVP, don't spend too much blood
sweat and tears on it, but would look nice for sure!

There's a bootstrap toggle library in vendor/assets but feel free to you
anything you like. Let me know if I can unstick anything in the process.

**Comment by sco-bo** [comment]
hey sorry for the delayed response. The toggle actually looks pretty easy to do so that's fine! Would you like it to toggle between 'Voicemail/No Voicemail' or still have the question of 'Voicemail Ok?` then the toggle reading 'Yes/No'

**Comment by colinxfleming** [comment]
Hey Scott, on my phone so I can't look right now but I'd say go with
whatever's in Mollie and Andrea's designs -- they're in the `_design`
directory in the repo. (You'll want to look for the PDF of the most recent
one.) Let me know if you need a hand identifying, and thanks again for
handling this.

**Comment by sco-bo** [comment]
Hey @colinxfleming and @mebates. The design mockup does show a toggle. I've tried to get this working over the past couple days but am not having any luck :( . I think it's a combination of the way bootstrap_forms formats the checkboxes and my limited knowledge of javascript. I don't want this to hold up the next release so maybe someone else should take a stab at implementing the toggle. Sorry guys!

**Comment by colinxfleming** [comment]
No worries Scott! Can you push up your branch and make a PR? I'm inclined
to give it another set of eyes before we declare defeat, but let me know
what you think.

**Comment by colinxfleming** [comment]
Toss it all up! I'd rather have something halfway there that we can build
off of, if that makes sense?
