### ISSUE TITLE
Rewrite call logging integration test so it doesn't randomly fail

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#375]
Our capybara tests are occasionally failing randomly. I suspect this is either an issue in my writing sketch integration tests or with PhantomJS just being a jerk sometimes for no reason. Making a note to investigate.

**Comment by Kevin-Wei** [comment]
Is it ajax? cause my phantom projects have a ton of ajax helpers to reduce intermittent blinking tests

**Comment by colinxfleming** [comment]
They totally vary, which sucks! Sometimes it's javascript, but a lot of the
time it's stuff like 'Can't find link for Call Log on the pregnancy edit
view', which shows up on page load.

**Comment by colinxfleming** [comment]
On a lark I tried switching to selenium and it at least fails consistently! I think phantomjs just might be kinda bad for what we're doing.

**Comment by colinxfleming** [comment]
Renaming to reflect changes made in #420.

These test failures mostly seemed to be coming from capybara testing before the page had actually loaded, or javascript had actually executed. In most places this is fixed, but we're still experiencing a few random failures in the Logging Calls integration test as follows (try running the command `ruby -e "for i in 1..10 do; system 'rake test TEST=test/integration/logging_calls_test.rb'; end"` to replicate):

```
 FAIL["test_0001_should close the modal when clicking Couldn't reach patient", #<Class:0x007fe22197bbd8>, 11.437981902010506]
 test_0001_should close the modal when clicking Couldn't reach patient#LoggingCallsTest::logging Couldn't reach patient::{:js=>true} (11.44s)
        Expected false to be truthy.
        test/integration/logging_calls_test.rb:80:in `block (3 levels) in <class:LoggingCallsTest>'

 FAIL["test_0003_should be able to save more than one reached patient call", #<Class:0x007fae8a88b478>, 9.754180176008958]
 test_0003_should be able to save more than one reached patient call#LoggingCallsTest::logging reached patient::{:js=>true} (9.76s)
        Expected false to be truthy.
        test/integration/logging_calls_test.rb:59:in `block (3 levels) in <class:LoggingCallsTest>'
        test/integration/logging_calls_test.rb:58:in `block (2 levels) in <class:LoggingCallsTest>'

ERROR["test_0002_should be viewable on the call log", #<Class:0x007fd5e89a2d68>, 11.567478222976206]
 test_0002_should be viewable on the call log#LoggingCallsTest::logging reached patient::{:js=>true} (11.57s)
Capybara::ElementNotFound:         Capybara::ElementNotFound: Unable to find css "a" with text "Call Log"
            test/integration/logging_calls_test.rb:41:in `block (2 levels) in <class:LoggingCallsTest>'
```
