### ISSUE TITLE
Require strong passwords for users

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#383]
We should enforce a certain level of password complexity. e.g. require a lowercase character, uppercase character, and a number. 

I'm agnostic as to whether we do this with a gem that extends devise or some other sort of validation on password. Google away.

**Comment by sco-bo** [comment]
Googled around and found [this](http://excid3.com/blog/rails-tip-adding-password-complexity-validations-to-devise) handy validation. It doesn't look like devise has any password complexity baked in, however there's [this](https://github.com/phatworx/devise_security_extension) gem which does a lot of different things in addition to strong passwords. I can implement that first validation, or if it seems like there are other cool features in the security extension gem that may be helpful down the road, I can do that instead!

**Comment by colinxfleming** [comment]
@sco-bo sorry, missed yr post the first time thru! Let's pocket that gem as something to look at after deploy. I like the idea of adding `session_limitable` a lot. 

What do you think about just implementing that validation in the first link for the time being?

**Comment by sco-bo** [comment]
Ya I can do totally do that @colinxfleming! Is this a duplicate of #389?

**Comment by colinxfleming** [comment]
Scott -- yeah, these seem to naturally flow into each other, don't they?

Thoughts about closing this one and moving discussion / tracking to #389?

**Comment by sco-bo** [comment]
Ya sounds good to me!

**Comment by colinxfleming** [comment]
Not really needed for deploy since we aren't opening it up, closing here and moving other conversation to #389
