### ISSUE TITLE
Validate complexity of passwords

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#389]
The OWASP sheet at https://www.owasp.org/index.php/Ruby_on_Rails_Cheatsheet#Authentication has a recommended validator for passwords in the user model as follows:

```
   validate :password_complexity
   def password_complexity
      if password.present? and not password.match(/\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+\z/)
          errors.add :password, "must include at least one lowercase letter, one uppercase letter, and one digit"
      end
   end
```

Let's plug it in! 

Marking as beginner friendly because it's a good way to try out model validations; not marking as deploy since we only really need it for release 2, and not Release 1: Lisa Edition.

**Comment by colinxfleming** [comment]
@mccabe615 pointed out the following in #417 : "Should there be stronger requirements on password strength? Such as, minimum 10 characters, include at least one, special char, number, upper case and can't use the word password in any form."

He's definitely right that the regexp above is a bare minimum and that we should ratchet up the complexity, as well as not allowing any 'password1234' kinda stuff.

**Comment by mccabe615** [comment]
@colinxfleming I'll try to take a crack at a PR in the next couple of days to add a complexity validation for this.

**Comment by colinxfleming** [comment]
Thanks, bud. Let me know if you run into any trouble spots or if there's
anything I can unstick for you.

**Comment by sco-bo** [comment]
@colinxfleming just checking, is #383 a duplicate?
