### ISSUE TITLE
Install codesake-dawn gem

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#390]
In the interest of catching more security stuff, we should install and implement the `codesake-dawn` gem into our testing process!

The steps here are roughly as follows: 
* Install the gem
* Figure out how to run it from the command line (probably something like `bundle exec codesake-dawn`)
* Add a command to `circle.yml` so that the command returns an error if `codesake-dawn` flags anything. Feel free to use the convention in the file (e.g. `gem install --no-rdoc...`) This will make it so that code with security warnings doesn't get deployed. 

Tagging as beginner friendly since this is a cool way to find out more about continuous integration in our environment!

**Comment by ewiggins** [comment]
I'll take this on tomorrow. @colinxfleming after testing, do you want this to be added to the gemfile?
