### ISSUE TITLE
Build call list:  automatically populate search result with name/phone number

### ISSUE THREAD

**Issue by eheintzelman** [colinxfleming/dcaf_case_management#397]
After searching for a patient by name or phone number, the user gets prompted to create a new patient if the search produced no results.  Could the form field for name/phone number get automatically populated based on the search input (i.e., either name or phone number)?

**Comment by colinxfleming** [comment]
@eheintzelman is 100% right, this is really annoying! This is probably an edit to the search function in `DashboardsController`, and probably to `app/views/dashboards/search.js.erb` as well.

**Comment by colinxfleming** [comment]
Taking care of this tonight
