### ISSUE TITLE
Urgent cases list:  question about add/remove 

### ISSUE THREAD

**Issue by eheintzelman** [colinxfleming/dcaf_case_management#399]
What do folks think about the use of add/remove for the urgent cases list?  I'm concerned that a user could interpret this as add/remove from the urgent cases list, not the call list as intended.    

@mebates @lwaldsc @NerdyGirl537 your thoughts?

**Comment by mebates** [comment]
Yeah this and the #400 issue came up because at plus/minus got misinterpreted as an add/remove. (full history in #305). I think we can just remove the 'add/remove' in urgent cases for now!
