### ISSUE TITLE
project minutes process and tool

### ISSUE THREAD

**Issue by mattbailey0** [colinxfleming/dcaf_case_management#4]
Story: As a new contributor to the project, I want an easy way to get up to speed so that I can start helping as quickly as possible.

Possible solution: we need to keep a light weight blog or similar platform where we can note recent accomplishments, such as at the end of each Code for DC hacknight.  That way a new contributor can see not only the commit history but non-code accomplishments, such as design activities.

TODO: figure out the norms/process for how this content will be updated and pick a tool, such as the wiki attached to this repository or a hackpad, to use.

Some points we may want to track:
    - decisions made
    - scrum in post form
    - next steps

**Comment by mebates** [comment]
Here's a first stab. Would love for @colinxfleming to add more detail on what his group did (and even if you caught names?). 
https://github.com/colinxfleming/dcaf_case_management/wiki/11.09.15

**Comment by colinxfleming** [comment]
Assigning this to myself so I remember to update the wiki

**Comment by colinxfleming** [comment]
We landed on the following techniques:
* Defining sprints as a team based on user stories
* Keeping track of sprints in the wiki and as github milestones
* Starting each hacknight with an update on what got done and where we are
* Concluding each hacknight by recognizing individual work done

I'm closing this out.
