### ISSUE TITLE
Edit changelog entries to appear in reverse chronological order

### ISSUE THREAD

**Issue by eheintzelman** [colinxfleming/dcaf_case_management#403]
Change log is in chronological order, whereas Call Log is in reverse chron order.  Can we make these consistent?

How about making the Change Log reverse chron.

**Comment by colinxfleming** [comment]
This is likely a pretty straightforward change in `app/views/pregnancies/_change_log.html.erb`! Marking as beginner friendly, since I think it's a good entrypoint into our codebase. 

Compare to `app/views/pregnancies/_notes.html.erb` for an example of the reverse chron.

**Comment by mebates** [comment]
+1. Thanks @eheintzelman

**Comment by KatSDC** [comment]
I have a solution for this! Just tying up loose ends and then I'll submit the PR.
