### ISSUE TITLE
Usability testing - draft testing script

### ISSUE THREAD

**Issue by eheintzelman** [colinxfleming/dcaf_case_management#405]
Here is a draft usability script to use with a few DCAF case managers.  The idea is to get feedback on the design from case managers who are familiar with the process but who haven't seen the system design before.  

I drafted scenarios to test what I think are the key functions.  Feedback would be great on any recommended changes/additions  @lwaldsc @mebates @NerdyGirl537

**Comment by eheintzelman** [comment]
Introduction 
	- Testing DCAF Case Manager system to see what it is like for people to use it
	- Will take 30-45 minutes
	- Will ask you to complete tasks in the system and want to hear exactly what you are thinking as we go
	- Testing the system not you.  Want your honest feedback
	- Feel free to ask questions as you go
	- If recording (do we want to?), explain that only people working on the project will have access.  

Background questions
	- How long have you been a case manager w/ DCAF?

Tasks

>1 (Main page) Describe what you see on this page? What do you notice first?  What tasks do you think you will be able to complete from here? What can you do from the urgent cases section?  

>2 You are reviewing voicemails and would like to create a list of people to call back as you listen to the vms.

	[non-existing patient case] What would you do if you wanted to add a patient with the phone number 222-222-2222 to the list?  (Have them walk through all steps through to creating a new patient)
	
	[existing patient case] What would you do if you wanted to add a patient with the name "" to the list? 
	(Have them walk through all steps through to creating a new patient)

>3 Call a patient on the call list (new patient)  You reach the patient and collect intake information.  You discuss clinic options and make a note about the patient's ability to get to certain clinics. She is 15 weeks already and you want to flag this for the case manager next week.  (Have them walk through process of entering information) 

>4 Call a patient on the call list (appointment needed).  You reach the patient.  She has selected a clinic and an appointment date.  You confirm how far along she is and she indicates that her due date was adjusted by two weeks. (Have them walk through process of entering information) 
	
>5 Call a patient on the call list (fundraising).  You reach the patient.  Confirm sources of payment for procedure.  Patient will commit $X amount.  You confirm all information and submit the pledge.  (Have them walk through process of entering information) 

>6 You are concerned about a patient you spoke with a month ago and want to know her status.  You want to see what case managers have spoken to her and what progress has been made.  How would you go about doing this? 

>7 How would you go about changing your password? 


Other
Ask any follow-up questions to understand why the user did certain tasks they way they did.

**Comment by mebates** [comment]
@eheintzelman this is so fabulous. I'm sorry I didn't get you any feedback before the interviews! But thank you so much for taking this on; I think you script is great.

**Comment by eheintzelman** [comment]
**Usability Testing Summary – 3 Users
6/27/16**
 
**Priority Changes/Fixes**
 
1 - Dashboard: After creating a new patient, automatically add patient to the call list [3 users] 
 
2 -  Save information entered as the user navigates between tabs or consider putting a save bottom at the bottom of the form, which seems more intuitive to the CMs than having the save button on the side.  Also make sure that system returns user to the same view after saving.  [2 users]
 
3 - Dashboard: Suggest entries with names or phone numbers that are similar to a CM’s search.  Goal is to avoid duplicate creation of patient entries.  Two users were unable to find users they had just entered because of minor discrepancies such as a space after a name. [2 users]
 
4 - Patient Information: Should be able to select multiple “special circumstances.”  Could also include a text field. [2 users]
 
5 - Patient Information: Change language for “secondary person” and “secondary phone” since CMs are not clear on this. One suggestion was “primary contact (if other than patient)” 
 
Add a field to specify the relationship of the primary contact to the patient.  And/or add a text field for explanation.  CMs want to understand who it is they are talking to.  [2 users]
 
6 - Abortion Information: Consider removing street address and zip for clinic.  CMs do not typically enter this information.  
 
Alternatively, create a dropdown for clinic selections since typically CMs work with a fixed set of clinics.  Address and zip could automatically populate when the clinic is selected.  It is useful for CMs to have this address info on hand because they sometimes provide this address information to patients.  Include an option to enter the name of a clinic manually, since this does sometimes (though rarely) come up. [2 users]
 
7 - Change order of tabs to Patient information, Abortion Information, then notes.  [3 users]
 
8 - Dashboard: Add/remove in Urgent cases section is confusing.  [2 users]
 
 
**Questions for DCAF**
 
1 – Status: one user suggested that intuitively there was not much difference between Needs Appointment and Fundraising, since often they happen simultaneously.  Another user thought it would be helpful to have soft pledge and pledge submitted statuses as well.  What would be the most helpful? 
 
2 – LMP dating:  Sometimes CMs update the LMP.  This happens when there is a significant change in the due date estimate.  It’s not clear how they would go about updating this since it is confusing to try to edit the “LMP at intake” after the fact.  Maybe instead of editing the “LMP at intake” there could be a way to edit the “current LMP”?
 
3- One user wanted to understand how the transition would work from one week to the next, one CM to another.  Have we thought this through? 
 
 
**Potential New Features – Lower Priority** 
 
1 - Include a checkbox to specify is Spanish is preferred. [ 1 user]
 
2 - Abortion Information:  Add a text field to specify if there are special medical issues that would cause abortion cost to go up.  Rare, but significant when it happens [ 1 user]
 
3- Create a way to resubmit pledge if there are changes [1 user]
 
4 - Automatically flag patients who have been in the system for a long time as urgent [1 user]
 
5 - Create a text field to add notes re voicemail, i.e. “can leave vm but request that not mention DCAF.” [1 user]
 
6 - Pledge confirmation should specify what state the user is in. [1 user]
 
7- Add helper text where appropriate, i.e., for income field to explain what type of income is included. [1 user]

**Comment by colinxfleming** [comment]
This is really fantastic and very actionable feedback. I'll spin these into
individual issues and get feedback from Lisa and Jenn where appropriate.

@eheintzelman should we save the script in the repo as well, so we can
version control it and use it in the future?

**Comment by eheintzelman** [comment]
I neglected to include all the positive things the CMs had to say during the usability testing!  It seemed very intuitive for them and they were able to work through the majority of tasks without any prompting.  Great design!  

@colin where can I save script in the repo?

**Comment by colinxfleming** [comment]
+1 on these designs absolutely slaying. I think it reflects extremely well on our process (and @mebates 's brain and hard work!) that @eheintzelman was able to basically chuck our CMs in the pool and see them all figure it out without much trouble.

@eheintzelman I'd say either create a new directory in the root (something like `_usertesting`) or pop them into a directory within `_design`.

**Comment by colinxfleming** [comment]
Created or linked issues in the user testing checklist above. @eheintzelman let's close this out when we merge a pull request with the script in it. Thanks again to you and Sabrina for your absolutely fantastic work on this front -- stuff like this is what turns a great product into a fabulous one.

**Comment by mebates** [comment]
@eheintzelman GitHub let's you drag and drop files now, so you can create a new folder and just drag in. I can help you on Wednesday if you'd like. Awesome job on the testing AND summarizing the results into clear next steps. THANK YOU!!!

**Comment by colinxfleming** [comment]
Resolved by @eheintzelman  in 1ed38a3 - closing
