### ISSUE TITLE
Autoemail on email address and password changes

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#415]
If not, we should! Let's make sure this is the case, so that users are alerted to account tampering.

**Comment by colinxfleming** [comment]
Devise doesn't do this out of the box, but we can backlog and keep on deck for release 2.

Here's a set of directions to implement - https://github.com/plataformatec/devise/wiki/Notify-users-via-email-when-their-passwords-change

**Comment by benjamincrane** [comment]
Looking at this one tonight.
