### ISSUE TITLE
Password Complexity?

### ISSUE THREAD

**Issue by mccabe615** [colinxfleming/dcaf_case_management#417]
Should there be stronger requirements on password strength? Such as, minimum 10 characters, include at least one, special char, number, upper case and can't use the word password in any form.

**Comment by colinxfleming** [comment]
I think the example in this ticket is definitely a floor! Do you want to
whip up a regex that we can use to increase the strength of the
requirements?

**Comment by colinxfleming** [comment]
Let's move further discussion of this to #389 -- going to close this out.
