### ISSUE TITLE
Email Enumeration on Forgot Password

### ISSUE THREAD

**Issue by mccabe615** [colinxfleming/dcaf_case_management#418]
When resetting your password if you include a valid email you get a success message and with an invalid one you get an error. This can lead to email enumeration which can then be used to brute force credentials. I believe this is happening in devise not the app proper. I need to look into how this can be changed to show the same error message even if the user isn't found.

*Valid user:*

<img width="783" alt="validuser_response" src="https://cloud.githubusercontent.com/assets/1463253/16354406/00f020c0-3a61-11e6-9c78-cb14ce96d415.png">

*Invalid user:*

<img width="642" alt="invaliduser_response" src="https://cloud.githubusercontent.com/assets/1463253/16354408/0458a5ca-3a61-11e6-99d4-c004b505f353.png">

**Comment by colinxfleming** [comment]
It looks like Devise has a `paranoid_mode` that you can turn on in the configs, that might include this? Investigating!

https://github.com/plataformatec/devise/search?utf8=%E2%9C%93&q=paranoid
