### ISSUE TITLE
'Special circumstances' should be checkboxes, not a dropdown

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#434]
Patients can have more than one 'Special Circumstance' at a time. For MVP, you could eliminate the 'Other' plus text field for now and add it later. 

![image](https://cloud.githubusercontent.com/assets/6223901/16399170/132c0120-3c9e-11e6-86c3-02bfdf49ae02.png)

**Comment by colinxfleming** [comment]
I'll revert this to a plain text field for the time being. 

In the long term, this probably involves setting up an associated special circumstance model with the options, and then doing a has_many :through. Or at least that's how you do it in postgres, might be a little different in Mongo. 

Backlogging for the time being.

**Comment by eheintzelman** [comment]
The UX team would like to know if we can prioritize this so that the data is clean.  @mebates would especially like this!

**Comment by colinxfleming** [comment]
Acknowledged; I'll see if I can spin something up tomorrow.

**Comment by colinxfleming** [comment]
We should have this in place by showtime, marking deploy.

**Comment by ashlynnpai** [comment]
Taking a stab at this.

**Comment by colinxfleming** [comment]
Fixed by @ashlynnpai in #591
