### ISSUE TITLE
Get/Run Brakeman Pro

### ISSUE THREAD

**Issue by charleshuang80** [colinxfleming/dcaf_case_management#435]
We have already added Brakeman and are addressing the vulnerabilities (#283, #301). However, @mccabe615 mentioned Brakeman Pro in his presentation to DCRUG, stating that it has some deeper testing and analysis and is cost effective. Plus, there is a free trial if that helps. More info on the [differences between the paid version and open source version here](https://brakemanpro.com/pro_vs_oss).

**Comment by mccabe615** [comment]
I reached out to Justin Collins at Brakeman to see if he can give DCAF a discount or free license. I'll update here once I hear back.

**Comment by colinxfleming** [comment]
@mccabe615 that'd be dreamy. Let me know if there's anything I can do to assist on that front (pulling nonprofit paperwork, etc).

**Comment by mccabe615** [comment]
Hey @colinxfleming @charleshuang80 I heard back from Justin at Brakeman. They said they could give the project a free license! What email and name should be associated with it? I'll send over the details.

**Comment by colinxfleming** [comment]
That RULES. Thanks for reaching out, @mccabe615 ! 

Can we associate with DCAF as an org? Name can be `DC Abortion Fund`, email can be `info at dcabortionfund dot org`.

**Comment by mccabe615** [comment]
Justin sent an email with the info to that email. Let me know if you need anything else.

**Comment by colinxfleming** [comment]
@mccabe615 thanks a TON for hooking this up, this is really fantastic. Email is received with info, I'm going to get it all set up over the weekend sometime.

**Comment by colinxfleming** [comment]
High five, everyone -- 

![image](https://cloud.githubusercontent.com/assets/3866868/16542690/cec80326-4080-11e6-8152-72c291c2cb7f.png)

**Comment by colinxfleming** [comment]
Remaining task to do here is to see whether or not we should adjust our CI (I suspect not, but I'll do some googling).

**Comment by colinxfleming** [comment]
Closing out -- I think we're in the clear! I'll rerun against master a few times as we get closer to release day, but I think we're good here.

Thanks again to @mccabe615 for hooking this up!
