### ISSUE TITLE
Make notes expander snap to grid

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#448]
see below:

![screen shot 2016-07-02 at 12 08 11 pm](https://cloud.githubusercontent.com/assets/3866868/16541330/bd81297c-404d-11e6-896a-636fe46e4be3.png)

**Comment by CamLatimer** [comment]
I'll get on it.

**Comment by colinxfleming** [comment]
@CamLatimer can I help unstick anything on this?

**Comment by CamLatimer** [comment]
Sorry man. I forgot I had started to work on this. I have the expander snapped. I was trying to do a little more to make the look of the table header consistent with the rest of the table, but I'll submit what I have.

**Comment by colinxfleming** [comment]
@CamLatimer no worries bud! Take your time, and let me know if there's anything I can unstick for you.

**Comment by colinxfleming** [comment]
hey @CamLatimer ! Just giving this a tug -- let me know if I can help unstick.

**Comment by cschlessinger** [comment]
PR ready for review: https://github.com/colinxfleming/dcaf_case_management/pull/869

**Comment by cschlessinger** [comment]
@colinxfleming are the phone numbers in the initial screenshot real data? Noticed it earlier and got a little concerned

**Comment by colinxfleming** [comment]
@cschlessinger Nah, they're the rest of 202-mash-hand-on-keyboard.

**Comment by colinxfleming** [comment]
Resolved in #869
