### ISSUE TITLE
Adjust search to allow for names or phones similar to others

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#449]
From user testing in #405 comes this recommended feature:

> Suggest entries with names or phone numbers that are similar to a CM’s search.  Goal is to avoid duplicate creation of patient entries.  Two users were unable to find users they had just entered because of minor discrepancies such as a space after a name. [2 users] 

First things first is probably to spec out some examples or test cases: Given a patient we're looking for and an entry, what do we expect it to return?

Marking question and backlog for now until we hash this out.

**Comment by NerdyGirl537** [comment]
Is there a way to strip out extra spaces in a name when storing the data?  Is the full name/phone number required to find the patient?  How does this search when we enter phone numbers in different ways (e.g. xxx-xxx-xxx, xxx.xxx.xxxx, xxx xxx xxxx, xxxxxxxxxx)?

I think it would be nice to search on partial information -- the last 5 of the phone number, by only first or last name.  Also, would be nice to see a listing of calls that haven't been pledged final.

**Comment by colinxfleming** [comment]
On the search tip: The people on this project who have spent the most time thinking about the search feature are @KatSDC and @ajohnson052  . If @KatSDC and/or a UXer (@mebates , @SabrinaRitacco , @eheintzelman  ) is available for this I'd love to have them sit down with you and spec out some specific scenarios we can cover. 

Team UX: Does that sound like a good approach? 

Let's punt on the listing of calls that haven't been pledged final for now. I think the dry run is going to inform a lot of our approach to those questions.

**Comment by KatSDC** [comment]
I would be happy to put some more time/thought into making the search more user friendly. Partial search would certainly be ideal, but I'll have to do some more research into how to achieve that with MongoDB. If a UXer has time - maybe next week? I can set aside time to discuss the best approach from a user perspective. I have class on Tuesday/Wednesday nights, but otherwise am pretty open.

**Comment by colinxfleming** [comment]
Closing this as a wontfix, since there isn't a great path to this and this is a really, really complex problem.
