### ISSUE TITLE
Model testing: Add tests for Case, Patient, Call models

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#45]
These models need basic verification tests to ensure that objects save information the way we think they do. 

A good best practices primer on what to test in model tests (and testing in general!) is here: https://robots.thoughtbot.com/how-we-test-rails-applications

**Comment by colinxfleming** [comment]
@kevin-wei

**Comment by Kevin-Wei** [comment]
I got this... I think?

**Comment by colinxfleming** [comment]
Scaling this down to just implemented models.
