### ISSUE TITLE
Find some way to represent the primary contact so CMs know who they're talking to

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#450]
From user testing in #405 -- 

> Add a field to specify the relationship of the primary contact to the patient.  And/or add a text field for explanation.  CMs want to understand who it is they are talking to.  [2 users]

Throwing it up to UX on how to represent this.

See also #402 for part of the technical changes here.

**Comment by colinxfleming** [comment]
punching in @lwaldsc @NerdyGirl537 -- how does this work in the sheet currently?

**Comment by mebates** [comment]
We can talk more about this on Wednesday and design a new mockup.

**Comment by lwaldsc** [comment]
In addition to partial search strings, the search *needs* to also look through "Secondary Contact" and "Secondary Number" to find other contacts.

**Comment by lwaldsc** [comment]
@mebates @eheintzelman @NerdyGirl537 

Autopopulate patient first and last name to the Patient Information page above Age

Rename and reorganize Patient Information fields
**Secondary Contact** 
First and Last Name
Phone 
Relationship 

_Move fields to below ZIP_

**Comment by lwaldsc** [comment]
Pulled in @dfelsent to make some quick changes on this because she is a rockstar.
