### ISSUE TITLE
Questions about our status field - needs appointment vs fundraising? add soft pledge category?

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#452]
Raised in #405 - 

> 1 – Status: one user suggested that intuitively there was not much difference between Needs Appointment and Fundraising, since often they happen simultaneously. Another user thought it would be helpful to have soft pledge and pledge submitted statuses as well. What would be the most helpful? 

+ @lwaldsc and @NerdyGirl537 to assist.

Open questions: 
* Should we add a `Soft pledge` status? Probably. Thoughts?
* Should we merge `Needs Appointment` and `Fundraising`? Is there a better way to represent `Needs Appointment` than actual status, or is this something that we should keep as its own stage in the process? What would be most helpful and intuitive here?

Pledge submitted is represented by the `pledge_status? :paid` line, so we're good on that front.

Our current status code from the `pregnancy` object (fairly readable I think) for reference -- 

```ruby
  def status
    # if resolved_without_dcaf
    #   status = "Resolved Without DCAF"
    # elsif pledge_status?(:paid)
    #   status = "Pledge Paid"
    # elsif pledge_status?(:sent)
    #   status = "Sent Pledge"
    if appointment_date
      'Fundraising'
    elsif contact_made?
      'Needs Appointment'
    else
      'No Contact Made'
    end
  end
```

**Comment by NerdyGirl537** [comment]
I think some of this is training and getting used to the system.  Usually, 'Needs Appointment' also means 'Fundraising' because the patient really hasn't started the process.  However, I like having the two categories so I can tell how far the patient is in the process.  The way we've set it up, when I see fundraising, I know I can go straight to talking about NAF and other funds and how the patient is doing in her fundraising.  

On the soft pledge, I thought there was a field for that (https://projects.invisionapp.com/share/6757W6WFJ#/screens/115983266).  We definitely need it.

**Comment by lwaldsc** [comment]
Agree with @nerdygirl537. I think it's just an issue of defining what the
statuses mean to the CMs during training. Needs appointment is a distinct
part of the process and what we can expect to discuss with the PT when we
call.

**Comment by colinxfleming** [comment]
@NerdyGirl537 To be clear on the soft pledge front, this isn't a matter of whether or not we're representing soft pledge at all (we are), but whether or not it's worth spinning into its own status.

**Comment by NerdyGirl537** [comment]
Ok.  That could be helpful.  Definitely something to talk about tomorrow night.

**Comment by colinxfleming** [comment]
I'm gonna do my best to roll this into a plan of attack, based on my current sense of the project. I propose this: 

* We add a `soft pledge` status, defined as 'Has a number greater than zero in DCAF Soft Pledge'. 
* We keep `Needs Appointment` and `Fundraising` statuses defined as is.
* We are very explicit about defining the different statuses in training materials.

Thoughts?

**Comment by NerdyGirl537** [comment]
Can we do something like put an asterisk by the patient's name if they have a soft pledge?  I'm thinking they'll be in the fundraising status if we've given them a soft pledge.  A lot of the new system will be training and helping the CMs learn where to find the information in the new system.

**Comment by colinxfleming** [comment]
@NerdyGirl537 I hear you on the soft pledge flag. Will you raise that with @eheintzelman @SabrinaRitacco on how to implement that?

Based on that, it sounds like we don't need a separate `soft pledge` status, and can just make do with what we have.  

Code-wise, it sounds we're good to go here. I'm marking closed.
