### ISSUE TITLE
Add representation of language

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#455]
From #405 - 

> 1 - Include a checkbox to specify is Spanish is preferred. [ 1 user]

We've kind of skirted around language for awhile, but we're coming up on a point where we'll need to start working this in. My questions to start:

* Is a checkbox enough? Should we have a dropdown of 'select primary language' in the event that we get, like, a mandarin speaker on the line, or do we only ever really care about spanish?
* what UX adjustments should we make on this? 

cc @lwaldsc @NerdyGirl537 @mebates @eheintzelman

**Comment by NerdyGirl537** [comment]
On a Spanish language caller, we usually hand them off to a Spanish speaking CM.  We only deal with that patient from that point on with regards to the weekly budget.  Everything else is managed by the Spanish speaking CM.

**Comment by lwaldsc** [comment]
I've never encountered anything other than Spanish, but maybe just make the
checkbox "Non-English Speaker" and we can indicate in the notes something
like "Spanish speaker, handed off to CM xxxxx".

**Comment by colinxfleming** [comment]
If we only ever really worry about Spanish then a checkbox for Spanish instead of a dropdown is fine for release 2, I think.

Probably the next step here in the longer term is looking at DCAF's data and seeing if we ever see other languages, and asking the CM Director team what happens when other languages pop up (or if they do at all)! 

This might also speak to a need to be able to clearly identify spanish speakers early in the process. But I defer to team UX on this. (Team UX, let me know if it would be helpful to grab Cindy from User Testing Night to pick her brain on this.)

**Comment by colinxfleming** [comment]
I emailed the dcaf CMDs to make sure that we mostly saw english and spanish. I think we do spanish as a checkbox if it's just english and spanish, some kind of dropdown for non-english language otherwise. Will update the ticket when I hear back.

**Comment by colinxfleming** [comment]
The sense I'm getting from team CMD matches what @lwaldsc has observed --  we only really need to represent spanish, and that non-spanish non-english speakers are fairly rare. 

I think we should go with either an enum or boolean attribute to represent spanish. I'll mix up this issue as appropriate soon.

**Comment by mebates** [comment]
Check box is good for now. In the future we could have some sort of workflow that assigns it to the spanish-speaking CM or adds it to her queue.

**Comment by colinxfleming** [comment]
Way into the workflow idea!

For now, the task here is to: 
* Pop into the `Pregnancy` model and change `field :language, type: String` to `field :spanish, type: Boolean`
* Add a checkbox for `spanish` to the `pregnancy_information` partial

Nice and straightforward!
