### ISSUE TITLE
Add text field to specify medical issues to abortion information?

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#456]
From #405 - 

> 2 - Abortion Information:  Add a text field to specify if there are special medical issues that would cause abortion cost to go up.  Rare, but significant when it happens [ 1 user] 

Thoughts? @NerdyGirl537 @lwaldsc @mebates @eheintzelman

**Comment by mebates** [comment]
I think the CM could use the 'Notes' section for this.

**Comment by colinxfleming** [comment]
I kind of agree with @mebates -- seems like we can find a way to represent this within the current.

@lwaldsc @NerdyGirl537 are medical issues represented in the sheet anywhere currently?

**Comment by NerdyGirl537** [comment]
@colinxfleming we have a column at the end of the spreadsheet with a dropdown.  It also includes other issues such as homeless and domestic violence.

**Comment by lwaldsc** [comment]
@colinxfleming <https://github.com/colinxfleming> @NerdyGirl537
<https://github.com/NerdyGirl537> @mebates as I mentioned to Colin the
other day, I think the 'other issues' dropdown should be checkboxes if
possible (dealt with in #434) I don't know if this is possible with the
system as it is right now but it's sometime to think about moving forward.
This is could also include "medical issues (see notes)" or sometime similar.

I think notes are good enough for right now.

**Comment by colinxfleming** [comment]
@lwaldsc @NerdyGirl537 it sounds like this class of circumstances is kinda similar to what we'll be representing with special circumstances checkboxes down the road. So if we want to work that in, there's a place in the designs for it. 

It sounds like the consensus is notes in the short term, though?

**Comment by lwaldsc** [comment]
Yup. Sounds good to me.

**Comment by colinxfleming** [comment]
So ordered, notes it is. Closing.
