### ISSUE TITLE
Create way to resubmit pledge if there are changes

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#457]
From #405. Placeholder issue for now; not sure what this looks like yet but we'll need it for release 2 probably. marking backlog.

**Comment by colinxfleming** [comment]
Tagging in @lwaldsc and @NerdyGirl537 -- a few questions:

* If a pledge changes, do we need a record of exactly what was in the original pledge, or will just asking CMs to create a note that they're changing some details and resending be enough?
* Is there some representation of this we should have other than unchecking the box that says 'I have sent the pledge'? 

Question for dcaf cm management:
* My inclination is to not really be concerned about logging that a patient required a pledge to be resent, but I'm interested in whether you want to do analysis around this. Is it worth highlighting that a certain patient, CM, etc is often involved in resending pledges?

**Comment by NerdyGirl537** [comment]
On the pledge changes, I don't think we need a record of the original pledge.  The thought is that we only receive back the pledge which was used for the procedure and so it's the only one the treasurer sees and reconciles.  As a CM, I'll add notes about a change in procedure date, clinic or cost, but after the pledge is sent, it drops off my radar.  My main concern would be if the patient continues to be searchable with a pledge sent status (can I find her again if she calls back?).

**Comment by colinxfleming** [comment]
@NerdyGirl537 thanks for your insights here. It sounds like we can live without having to know that someone needs a resubmitted pledge; I think that's an appropriate corner to cut at this point. We can revisit if it ever matters. 

I think there's some UX discovery for what editing a pledge should look like -- I don't think we have that established yet. Can you and @eheintzelman @SabrinaRitacco tackle this at the meeting on 8/4?

**Comment by lwaldsc** [comment]
Bumping this thread bc of user feedback

I know we discussed having the pledge button turn into a "unsend pledge" button to allow further edits, but not sure if there was any movement on this. I think unsending pledges is confusing to a number of people so this needs to be addressed in some capacity.

**Comment by colinxfleming** [comment]
I don't think there's been any movement on that, and I think that's a major fixer upper that we can do. Here's my proposed behavior: 

* Sending a pledge stays the same
* After a pledge is sent, `Send a pledge` button text turns into `Cancel pledge`
* Clicking said button pops up a modal with some copy about 'Uncheck this here box to cancel the pledge for Susie Everyteen'.

Going to let this marinate over the weekend to allow for feedback from CMs and UXers, and then I think I'm going to add it to active. I think it's pretty straightforward and that we can adapt it once the modal overhaul is in.

**Comment by colinxfleming** [comment]
I think our users would really appreciate this. Slating it for the hackathon.

**Comment by zorkian** [comment]
Claim.
