### ISSUE TITLE
Add voicemail notes?

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#458]
From #405 - 

> 5 - Create a text field to add notes re voicemail, i.e. “can leave vm but request that not mention DCAF.” [1 user]

Thoughts @lwaldsc @NerdyGirl537 ? Would this have utility, is there a way we can box it up into a few set options or would free text be better, are there other ways we can press this into service?

**Comment by NerdyGirl537** [comment]
I don't know that it would be very useful to have a separate option.  We usually put that in the notes section along with other instructions the patient may have left in the voicemail.

**Comment by colinxfleming** [comment]
@NerdyGirl537 given that we don't really have the workflow set up to look at the full note history before making a call, I wonder if there isn't some utility to pushing this information to a call modal or something.

**Comment by NerdyGirl537** [comment]
I'm not sure that we need it now.  For first contact, we'll have just listened to the VM.  For follow up contacts, the notes will be available for review prior to the call.  I usually review the notes before I contact a patient I haven't spoken with.

@lwaldsc what are your thoughts?

**Comment by colinxfleming** [comment]
I think what's guiding my thinking is as follows: Given that we've already established that a CM doesn't have the ability to review the full history of notes, let's say that you pick up a hotline shift and call someone who has a note about their voicemail preferences buried.

What are possible outcomes if you don't have this information at your fingertips, and you leave a voicemail identifying yourself as DCAF on a line where it's okay to leave a voicemail but not to identify as an abortion fund?

I imagine that scenario's not an every shift occurrence, but I also bet that the consequences of getting that wrong could do some harm. 

I'm not sure if this is an overabundance of caution or not, honestly. I'd defer to Team CM on that, but I want to make sure that this is a scenario we're considering as we make this design decision.

**Comment by colinxfleming** [comment]
I think this is effectively a duplicate of #522 - closing
