### ISSUE TITLE
Pledge confirmation should specify what state user is in 

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#459]
From #405 - 

> 6 - Pledge confirmation should specify what state the [patient] is in. [1 user] 

Let's add this to the pledges modal in `app/views/pregnancies/_pledge`. Nothing fancy.

**Comment by NerdyGirl537** [comment]
In past, this has been part of the patient identifier: First Letter of State and last 5 of phone number (ex. D4-0258 for DC caller).
