### ISSUE TITLE
Add helper text for income

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#460]
From #405 - 

> 7- Add helper text where appropriate, i.e., for income field to explain what type of income is included. [1 user] 

Tagging in @lwaldsc @NerdyGirl537 @mebates @eheintzelman - 
- What should we make helper text for? 
- What copy be in the helper text?
- What is in the spreadsheet that we can crib from?

**Comment by mebates** [comment]
We can work on this as we expand to new users and figure out where they are having trouble. Marking as backlog.

**Comment by NerdyGirl537** [comment]
In the spreadsheet, we have helper text on the income field and the household field.  For Income, it shows "employment, Food Stamps, SS, TANF, etc.".  For Household, it shows "Number living in household.  Who lives in the house with the woman?  If there are children, list their ages - e.g. 2, 1 year, 5 years"

**Comment by colinxfleming** [comment]
Promoting this to active, since it's a pain point for users, and tagging hacktoberfest since it's pretty straightforward. Let's skip the household stuff since we aren't collecting child age anymore and keep the income one. 

In practice, this is a matter of adding some helper text to the `Income` form field per @NerdyGirl537 's comment above. We use the [Rails bootstrap forms gem](https://github.com/bootstrap-ruby/rails-bootstrap-forms) -- if I remember right adding helper text is just a matter of adding something to the hash, so it should be straightforward.

**Comment by lwaldsc** [comment]
Just as an aside, we need to be careful about what language we use. Just
saw "with the woman" (crypto is old old old haha) whereas we try to use
"patient" instead. Right now we don't use a lot of text, but as we start to
add more, just something to keep in mind.

**Comment by mebates** [comment]
How will the helper text appear?

**Comment by colinxfleming** [comment]
We use a similar technique in LMP display on the patient edit page. It'll show up the same as the 'Currently' thing underneath the input form. 

<img width="303" alt="screen shot 2016-10-22 at 1 35 24 am" src="https://cloud.githubusercontent.com/assets/3866868/19617178/e7dbaede-97f7-11e6-9d8c-09ae5da90aa3.png">

**Comment by colinxfleming** [comment]
Promoting to active since it's a nice CM happiness thing and I think it'll help with transition. 

Again, task here is to add `Employment, Food Stamps, SS, TANF, etc.` as helper text to the income field in the view for `patients#edit`. You might have to dig thru a few partials to get there but it should be a straightforward enhancement when you get there. Should be a nice introduction to how our view code is structured.

**Comment by vincecampanale** [comment]
@colinxfleming I'd like to give this a shot
