### ISSUE TITLE
Nice to have: Write a script to import spreadsheet data into the system

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#475]
Since Lisa will be picking up the work of the person who came before her, we'll want to give her a little bit of seed data so she can have a more realistic experience of what using the system is like in a live-fire situation. 

Let's plan on writing some kind of script (and checking it into version control so we can iterate on it as we continue to roll out) that will let us take a spreadsheet and dump it into the system.

**Comment by NerdyGirl537** [comment]
@colinxfleming @lwaldsc if you don't have time to get to the script I'll help input the data by hand.

**Comment by colinxfleming** [comment]
@NerdyGirl537 It's a problem we're going to have a few times in the next few months, so I want to make sure we make some forward progress on it. If you're coming tomorrow I might stick you with a dev and have you pair on it to get it going.

**Comment by colinxfleming** [comment]
Untagging deploy since this has the potential to be a very messy operation, sad to say.

**Comment by colinxfleming** [comment]
I'm marking this backlog for two reasons:
* it's not necessary for release to DC
* right now I think we should be focusing on features that bring CM happiness.

**Comment by colinxfleming** [comment]
Overtaken by events, now. Closing.
