### ISSUE TITLE
Adjust time stamp on call log for EST

### ISSUE THREAD

**Issue by eheintzelman** [colinxfleming/dcaf_case_management#485]

**Comment by colinxfleming** [comment]
Doesn't seem to be an issue in local/development but is an issue in staging and prod, so I wonder if it's a mongolab thing.

**Comment by colinxfleming** [comment]
Investigating this now. System clock seems to be four hours fast, probably thinks it's GMT.

**Comment by colinxfleming** [comment]
Happening to all uses of time we have (such as `Notes`)
