### ISSUE TITLE
Should be able to add notes even without contacting the PT

### ISSUE THREAD

**Issue by lwaldsc** [colinxfleming/dcaf_case_management#486]
You are currently unable to add notes if you have not indicated you have reached the PT. You should be able to add notes regardless of that step.

Tagging @colinxfleming to label this note as appropriate.

**Comment by colinxfleming** [comment]
Can recreate on my end. Message from the logs: 

```
Started PATCH "/pregnancies/57814946311c88114aefb3da/notes" for ::1 at 2016-07-09 14:58:22 -0400

ActionController::RoutingError (No route matches [PATCH] "/pregnancies/57814946311c88114aefb3da/notes"):
```

Likely solvable via form edit

**Comment by colinxfleming** [comment]
Stowing this for now because I couldn't solve in a half hour. The general story is as follows: 

* For whatever reason, on the first load, it doesn't work at all
* It also seems to be happening to the `urgent_flag`
* It seems to sort itself out after that point -- after a reload notes and other things seem to save normally, it sends payloads to the proper endpoints, etc

**Comment by colinxfleming** [comment]
Something similar to this seems to affect the 'continue' button the pledge modal

**Comment by mchelen** [comment]
here's the part of the html that changes on reload
**working**
```html
<div class="info-form-right col-sm-6">
        <input name="utf8" type="hidden" value="✓"><input type="hidden" name="_method" value="patch">
          <div class="checkbox"><label for="pregnancy_urgent_flag"><input name="pregnancy[urgent_flag]" type="hidden" value="0"><input type="checkbox" value="1" name="pregnancy[urgent_flag]" id="pregnancy_urgent_flag"> Flag this patient as urgent</label></div>
      </div>
    </div>
```


**working**
```html
<div class="info-form-right col-sm-6">
        <form id="urgents-form" class="text-right text-danger edit_pregnancy" role="form" action="/pregnancies/57a3cdc9d6519f00011c8b36" accept-charset="UTF-8" data-remote="true" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="_method" value="patch">
          <div class="checkbox"><label for="pregnancy_urgent_flag"><input name="pregnancy[urgent_flag]" type="hidden" value="0"><input type="checkbox" value="1" name="pregnancy[urgent_flag]" id="pregnancy_urgent_flag"> Flag this patient as urgent</label></div>
</form>      </div>
    </div>
```
I think the relevant code is in `app/views/pregnancies/_notes.html.erb` line 17
