### ISSUE TITLE
Use docker hub automated build for container image

### ISSUE THREAD

**Issue by mchelen** [colinxfleming/dcaf_case_management#491]
https://hub.docker.com/r/mchelen/dcaf_case_management/

**Comment by colinxfleming** [comment]
Discussed with @mchelen over 🍨 and he wins the prize on getting this set up! It's all yours, dog. 

I removed xfvb in #517. @mchelen if there's other scruff we can take out, holler.

**Comment by colinxfleming** [comment]
Sorry for being the holdup on this @mchelen ! I'll get in this weekend, promise.

**Comment by mchelen** [comment]
@colinxfleming hey no worries! i've been trying to think if there is any better approach, like if we want to do some of the container build steps locally in case people want to work on the docker config. but we can probably deal with that when such a use case comes up.
