### ISSUE TITLE
Remove !important tags from pregnancy menu styling

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#496]
We brute forced this through for MVP, but it shouldn't always be brute forced. A nice piece of code hospitality for someone who wants to take it on.

See `app/assets/stylesheets/pregnancies.scss` -- the `a, a:hover` tags contain an `!important` to force the color and background color, because we couldn't get the inheritance to chill out. The task here is to remove the important tags and recreate in a way that doesn't rely on the important tags. (HTML span tags? Figuring out where the inheritance is coming from? Up to you!)

**Comment by mchelen** [comment]
Here's the relevant commit: https://github.com/colinxfleming/dcaf_case_management/pull/487/commits/34e5ab49dc9dcaa41ed5acc37019b638a92a4527

I wonder if the color & background color are coming from Bootstrap, and need to be changed via class assignment?
