### ISSUE TITLE
design a high level user flow

### ISSUE THREAD

**Issue by mattbailey0** [colinxfleming/dcaf_case_management#5]
Based on source research in the Google Drive (team members can help with access to this), design a high level user flow to describe the application.  Post it to the repository.

--> this issue needs more detail if people are going to pick it up and do it without a lot of introduction.

**Comment by adinneen** [comment]
User Flow!

![dcaf flow](https://cloud.githubusercontent.com/assets/12372787/11199057/1ebcf320-8c98-11e5-9553-e0d5f7e64f53.jpg)

**Comment by adinneen** [comment]
User Flow - Second Try!

![dcaf flow 2](https://cloud.githubusercontent.com/assets/12372787/11200243/45b1a5de-8ca2-11e5-876c-da0f738041f0.jpg)

**Comment by colinxfleming** [comment]
@adinneen this RULES and I am going to show it off to the CM/board in a bit

**Comment by mebates** [comment]
Should we close this? @adinneen can you drop the source files into the _design file so others can access it if necessary? What program did you build it in?

**Comment by adinneen** [comment]
@mebates I built it in omnigraffle so will add that file to the _design folder!
