### ISSUE TITLE
Design login / welcome screen

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#51]
What does the very first screen look like for a case manager? How about a positive, grateful welcome and a very easy, no hassle login? What happens if they're a new user? Or if they forgot their password?

**Comment by mebates** [comment]
Let's use this as a starting point: https://playbook.cio.gov/designstandards/form-templates/#login-form

**Comment by colinxfleming** [comment]
Great call on the CIO standard. I'll create a separate issue to make the root route the sign in page as well.

**Comment by colinxfleming** [comment]
This is all done except for the thank you message, which is outside the scope of this sprint; spinning that into a separate issue and closing.
