### ISSUE TITLE
Make search function work for partial phone numbers 

### ISSUE THREAD

**Issue by lwaldsc** [colinxfleming/dcaf_case_management#512]
As a reminder to @colinxfleming we need to make the search work for partial phone numbers.

**Comment by colinxfleming** [comment]
Will be working on this tonight, jumping off @KatSDC 's work the other night

**Comment by colinxfleming** [comment]
After hacking on this for an hour and change I think the right path might be to change phones to be a string of all digits, and then do all the phone related formatting on the model level (similar to how we do LMP display as its own methods, and store it as a pair of ints). 

This involves a few nasty steps:
* Changing the validations in the patient model over
* Mass updating all phone numbers in the prod db
* Fixing seed data and rerunning in staging
* Adding some methods to display phones with hyphens
* Probably add a `before_save` hook to strip all non digits from phones
* ~ testin ~
