### ISSUE TITLE
Remove link to "Leave voicemail" when pt is flagged as No VM?

### ISSUE THREAD

**Issue by lwaldsc** [colinxfleming/dcaf_case_management#513]
"I left a voicemail for the patient" should be removed when a PT is flagged to not leave VM.

**Comment by NerdyGirl537** [comment]
I think that's fine.  Some times I leave VMs for PTs who haven't specified either way.

**Comment by mebates** [comment]
Hey team - The designs accounted for that. See below. Any way we can code this up in the modal?

![screen shot 2016-07-31 at 5 56 46 pm](https://cloud.githubusercontent.com/assets/6223901/17279666/36f349d2-5748-11e6-80a1-5aeba20adfce.png)

**Comment by colinxfleming** [comment]
Adding to the instructions in #522; closing this as a dupe. Thanks for pointing this out @mebates !
