### ISSUE TITLE
Safety check for appt date 

### ISSUE THREAD

**Issue by lwaldsc** [colinxfleming/dcaf_case_management#514]
Need to put some sort of logical safety check into the appointment date format. Not sure what exactly we want to do here, but maybe making sure the apt date is after the initial call date.

![image](https://cloud.githubusercontent.com/assets/10578608/16787964/9c6c463a-486e-11e6-9a69-1de4f6711d4f.png)

**Comment by colinxfleming** [comment]
This should be a fairly straightforward validation of checking `initial_call_date` against `appointment_date` in the pregnancy model. Marking for resolution this week.
