### ISSUE TITLE
Make call list drag and droppable

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#520]
During the pilot, @lwaldsc mentioned that she'd find it helpful to be able to rearrange her call list on the fly, rather than have them display in the order that they were added to her call list.

Open questions: 

* What's the use case for this? How do CMs organize their calls, and how should we reflect that in the app?
* What should we make them sortable on? Name, phone number, LMP, everything in the section?
* The possibility of doing this drag and drop was raised also -- is there something we get out of that which we don't get out of oneclick sorting?

**Comment by colinxfleming** [comment]
@lwaldsc 

I think a simple sort by name, lmp, and status would be sufficient; talked with colin about it the one night and he felt that a drag and drop was a lot more coding than is practical right now. would be nice somewhere down the line to d&d but a simple chart sort by those issues would solve the need without as much effort.

**Comment by NerdyGirl537** [comment]
A sort would be helpful.  Also would suggest a sort on call date.  The D&D would make CMs ecstatic beyond their wildest dreams.

**Comment by colinxfleming** [comment]
Let's see what our frontend heavy hitters ( @mchelen @rebeccaestes ) think is in the realm of the possible here -- how tough would it be to roll something like this out?

**Comment by mchelen** [comment]
@colinxfleming sorting definitely seems easier, because it can be done entirely client side. d&d requires a way to save the results, which is a ruby task. maybe start with the easy one and meanwhile get things in the place for full d&d?

also i forget if the call list is paged or not?

**Comment by colinxfleming** [comment]
Call list isn't currently paged, no. We don't really see enough volume to worry about pagination for an individual CM.

Right now we're populating call list from a attribute on the User model (which functions as a normal array for most intents and purposes), so inventing some way to reorder that isn't totally out of the question.

**Comment by mchelen** [comment]
If we can handle the reordering in JS, is there a good way to save the changes? Would that be a "save" button, or should it be handled after every move via Ajax?

**Comment by colinxfleming** [comment]
I'd lean toward an ajax call that fires on change, which is consistent with
how we interact with data across the app -- pretty much everything except
note creation saves via ajax on change.

**Comment by mchelen** [comment]
Ok cool, so what should the Ajax call? I can take a look at some of the
other pages and see how it's being done.

**Comment by colinxfleming** [comment]
We'll probably have to set up a new route for this in the users controller.
Something like a patch to `UsersController#reorder_pregnancies` should do
the trick as an endpoint. I'm happy to whip this up in a day or two, should
be fairly straightforward.

**Comment by mchelen** [comment]
Ok cool, if you can make a route to this, I'll take a crack at the frontend
code. My go-to for sorting is Datatables, and it also supports d&d
https://editor.datatables.net/examples/extensions/rowReorder.html

**Comment by colinxfleming** [comment]
This has coalesced around implementing drag and drop. Changing the labels and title to reflect.

**Comment by mchelen** [comment]
Ok I've got a lot of the UI elements in place. Minor stylistic question, what handle icon colors are the best?
![dnd3](https://cloud.githubusercontent.com/assets/30691/17313775/aa3e8da4-582c-11e6-8507-062dca0f3ac0.png)
![dnd2](https://cloud.githubusercontent.com/assets/30691/17313774/aa3e413c-582c-11e6-9a9e-5d5a3aaa3080.png)
![dnd1](https://cloud.githubusercontent.com/assets/30691/17313776/aa402a74-582c-11e6-9c9a-3a715f5eff5c.png)

**Comment by mchelen** [comment]
The big issue I'm having now is that the row, while dragging, has its cell widths messed up. I found 2 approaches to address this:

http://benw.me/posts/sortable-bootstrap-tables - works, but sets all cells to be equal width

http://stackoverflow.com/a/1372954 - can't get to work

**Comment by colinxfleming** [comment]
@mchelen that rules. When you have some sense of what the payload looks like, can you send it my way? I think that's probably the last major piece of this still waiting in #539 . 

Thanks again for your hard work on this. 

re: grabber icons, I like the way the first one looks, and they'll be straightforward to change, so let's roll with that (if it's easy, otherwise go with whatever's simplest).

**Comment by mebates** [comment]
Very cool! Can we go with a more subtle light gray for the handles? The drag-and-drop is not the primary action here, and we don't want to distract from the Patient Name link or the Call button.

**Comment by mchelen** [comment]
@mebates Sure, that sounds good! There ended up being several other design questions, such as row highlight when dragging, so I put in some default styling for now and maybe we could go over them all at once?

**Comment by mchelen** [comment]
@mebates i wrote up the design questions here: #560
