### ISSUE TITLE
New patient partial - input boxes for phone and name need to be wider

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#521]
Nice piece of low hanging fruit here -- modify the form input fields in `app/views/pregnancies/_new_pregnancy` to be long enough that you can get an entire phone number or name in. 

Consult with team UX if you need clarity on this. 

(Note that this came out of the pilot test.)

**Comment by colinxfleming** [comment]
Removing from deploy since it's not mission critical

**Comment by karldonus** [comment]
Hey! I'm going to tackle this issue. Thanks.
