### ISSUE TITLE
Expand patient voicemail preferences

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#522]
We were bikeshedding this prior to the pilot test -- now's a good time to figure it out, since we've had some livefire experience. 

How should we represent a patient's request to not leave voicemail? Right now we're doing a simple 'yes' or 'no', defaulting to 'no', but @lwaldsc found that to be a little strong.

Tagging in @lwaldsc @NerdyGirl537 @mebates @SabrinaRitacco @eheintzelman . We'll want to figure this out before showtime on Sept 1, I think. 

Sub-issue: When we figure this out, we should also make the Voicemail OK target in the patient view much bigger (something like a toggle switch on the new patient partial should do nicely).

**Comment by colinxfleming** [comment]
@lwaldsc 

I feel like the default no and a Do Not Leave VM no are two answers to the question. I'd rather see a red, yellow, green kind of system, sort of like:

Yes- Can leave VM
Default - No instructions left; proceed with caution; leave a No ID VM if want
No - No VM; No ID

Tagging @NerdyGirl537 again for her thoughts

**Comment by colinxfleming** [comment]
This also affects #513. If we have a true "no" instead of a default "no answer," I would remove the "leave voicemail" option.  - @lwaldsc

**Comment by NerdyGirl537** [comment]
I agree that there are 3 different options and I like the red/yellow/green system.  Default would be 'no instruction left.'

**Comment by colinxfleming** [comment]
It sounds like a consensus is emerging around this being a three option, defaulting on 'No ID VM'. Let's plan on rolling with that.

**Comment by mebates** [comment]
:+1:

**Comment by colinxfleming** [comment]
The action items here:
* in the pregnancy model, change `voicemail_ok` to be an (enumeration)[http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html] with the options :voicemail_ok_no_id, :voicemail_ok_id_ok, and :voicemail_no (with the default of :voicemail_ok_no_id). 
* Let's change the checkbox / toggle switch to a select element in the new patient partial and the pregnancy view patient information partial. The select text should be similar to what @lwaldsc posted above: 

```
Yes- Can leave VM
Default - No instructions left; proceed with caution; leave a No ID VM if want
No - No VM; No ID
```
