### ISSUE TITLE
Notes: Show full name of user instead of just initials?

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#523]
@lwaldsc mentioned during pilot that the ability to see the full name of a user (e.g. 'Colin' or 'Colin Fleming' instead of 'CXF' like we're doing now) in the notes section would be helpful. 

Tagging as a UX question. @lwaldsc can you get this conversation started by saying what you're hoping to get out of it and what the ideal behavior is? 

(Subnote: @mebates left a note about restyling this section)

**Comment by colinxfleming** [comment]
Hey @mebates can you refresh @lwaldsc 's mind on what she was talking about with this issue because she does not remember. Whoopse.

**Comment by colinxfleming** [comment]
BC right now @lwaldsc does not feel strongly one way or the other about it. I think initials are just fine, but not opposed to popping in full names if others feel they are needed.

**Comment by NerdyGirl537** [comment]
My 2¢:
This is feedback from the in-service:  Some of the CMs were excited by the thought they could see the full name of the previous CMs who had worked with the patient.  I always just look it up on the calendar so it's not a big thing for me.

**Comment by mebates** [comment]
I have no idea why it would be initials. I don't think we ever mocked up a 'notes history' screen. I think it should be first and last name, which would be most user friendly for new CMs in particular.

**Comment by colinxfleming** [comment]
@lwaldsc @NerdyGirl537 and @mebates make a very compelling case for full name here. 

Let's use the existing `name` field on the user model for this, and just clarify on the label that we'd like full name rather than adjusting the models. 

@KatSDC can I tag you in to take care of this? Just a matter of changing the label for `name` in `app/views/devise/registrations/edit.html.erb` to read 'First and last name' instead of just name. See `app/views/pregnancies/_patient_dashboard.html.erb` for something similar.

**Comment by colinxfleming** [comment]
@KatSDC let me know if you need me to unstick anything on this!

**Comment by colinxfleming** [comment]
Fixed via 451d131 (thanks @KatSDC )
