### ISSUE TITLE
Add ability for a user to remove their own calls

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#524]
A time or two during the pilot, @lwaldsc accidentally clicked 'left voicemail' on an 'unable to reach patient' call, and right now we aren't able to remove calls from the call log.

Potential solution here that I would like to run by UX: Maybe do it kinda like facebook does, where you can remove a call within a certain time period (5m? 10m?) of creating it, but then it's in there for keeps? Or should we just have it so that users can edit their own calls? Or should we just open it up and have everything editable?

**Comment by eheintzelman** [comment]
Discussed with @lwaldsc - Would it be possible to make calls editable during a CM's current session?  Once the sign out or their session times out, they no longer have the ability to edit.

**Comment by colinxfleming** [comment]
@eheintzelman I think we can swing that, or do something that's functionally identical. I'll change the issue accordingly.

**Comment by colinxfleming** [comment]
Technical requirements here are as follows:

Minimal:
* A user should be able to delete their own calls from the call log
* A user should not be able to delete other users' calls from the call log
* We should adjust the `call_log` partial to add the delete option, with a javascript alert confirmation

Gold medal version:
* a user should only be able to delete their own calls within their own session or within 8 hours, whichever is easier
* Both the views and model logic should reflect that behavior

**Comment by colinxfleming** [comment]
TBH I think this is a nice to have rather than a must have. I'm marking backlog, please let me know if you disagree @lwaldsc @NerdyGirl537 .

**Comment by colinxfleming** [comment]
Promoting this to active!

**Comment by mebates** [comment]
For the UI, please add a column in the Call Log table with the word "Remove" in it, as a red underlined link. This resembles the 'Remove' behavior on the call list. 

+1 to the javascript alert confirmation

**Comment by charleshuang80** [comment]
I'll work this issue today

**Comment by colinxfleming** [comment]
@charleshuang80 I'd put good money on you being in good shape on this, but let me know if you need an un-stick!

**Comment by colinxfleming** [comment]
Promoting to hackathon!

**Comment by yf6** [comment]
I'd like to give this a try during the hackathon, just to confirm, we are talking about this table here?
<img width="1191" alt="screen shot 2017-03-03 at 11 27 43 pm" src="https://cloud.githubusercontent.com/assets/1358856/23577014/0f685806-0069-11e7-81b3-71a11a043c83.png">

**Comment by colinxfleming** [comment]
@yf6 yep, that's the one!
