### ISSUE TITLE
Reduce the size of the notes entry box

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#525]
Right now the notes entry box is kind of big. We should reduce it, so that you can see the first note and not just the huge box without scrolling down a little bit. 

Steps: 
* Reduce the size of the notes input in `app/views/pregnanices/_notes.html.erb`
* Get @lwaldsc or a member of team ux to approve

**Comment by jeffreyeaton76** [comment]
Hi. I'm planning to come to the Civic Hack Night on 8/4 and would love to help with this project. I thought I'd get to know it by taking on a beginner-friendly issue. See you next week. --Jeff
