### ISSUE TITLE
Represent patient notes in the call modal

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#526]
@lwaldsc spent some time clicking into the pregnancy view before making a call, to look at the notes for an individual person. Should we find a way to include the full set of notes for a patient in the call modal?

**Comment by colinxfleming** [comment]
@lwaldsc @eheintzelman 

We both think having the full set of notes in the modal is somewhat impractical and has the potential to get very messy very quickly

Could we have a Call PT button within the actual pregnancy file at the top of the left hand tabs menu? Mirroring the Send Pledge button at the bottom.

Then a CM could pick a PT on the list, read notes, and be able to call from inside the pregnancy view.

**Comment by NerdyGirl537** [comment]
I think the full set of notes would be overwhelming/unwieldy on the main page.  This could be a training opportunity as well, as once the PT has been added to the call queue, the CM can just return to the main menu and do the call.

**Comment by colinxfleming** [comment]
Sounds like the next step here is team UX insight. Tagging in @mebates

**Comment by mebates** [comment]
I think both would be helpful.
1) A button within the pregnancy file to place a call. I think this makes sense on the "Call Log" section
2) A portion of the last note in the call modal - perhaps it could be limited by character numbers so you don't see a full novel, but maybe the first few lines with an ellipsis? That way it gives you a general idea of what is going on.

**Comment by colinxfleming** [comment]
Sounds like a plan. I think @mebates is right on.

Action items here are: 

- [ ] Add a button to pop up a call modal in the `_call_log` partial. Should behave exactly like the one on the dashboard for now. 
- [ ] Add the first 400 characters of the most recent note to the new call modal underneath the links to log a call. See the note helper in `dashboards_helper` for some code you can adapt. 

tagging in frontend.

**Comment by colinxfleming** [comment]
Feature is CM happiness related; tagging deploy

**Comment by jeffreyeaton76** [comment]
I'm going to take a crack at this.
