### ISSUE TITLE
Represent Other Contact information in call modal

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#527]
How should we represent the fields `other contact name` / `other contact phone` / `other contact relationship` in the call modal?

**Comment by colinxfleming** [comment]
I think that should just pull the additional information if available. Pretty straightforward.
Maybe something like a smaller title like “Alternate:  PersonZ (xxx-xxx-xxxx) - Mother" directly under the PT’s name and phone in the modal. - @lwaldsc @eheintzelman

**Comment by eheintzelman** [comment]
How about additional instructions after "Call [PT NAME] now" and before the phone number.  

If the patient is the primary contact, something like, "You can call this patient directly."

If other contact, something like, "Mary Miller (mother) is the primary contact for this patient." 

Do we need to have a way to identify what phone number is primary?

Would like design input from @mebates

**Comment by colinxfleming** [comment]
Having this in place for deploy would be helpful I think -- tagging as such

**Comment by colinxfleming** [comment]
Let's roll with this as follows: 

* If there's an `other contact` on the patient, display '{Other contact name} ({other contact relationship}' is the primary contact for this patient -- phone {other contact phone}' in red 
* Otherwise do nothing

I think we can fine tune this down the line, and would prefer it be in place for showtime.
