### ISSUE TITLE
Mark patients as resolved without help from dcaf

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#528]

**Comment by colinxfleming** [comment]
A few times now we've needed to represent a patient as having resolved their pregnancy by either deciding to keep it, or finding cash independently, or something similar to that. To reflect this need, we should add an attribute in the pregnancy model so that we can mark a pregnancy complete. 

The steps to this are as follows:
* Add a boolean attribute to the pregnancy model, `resolved_without_assistance`
* Adjust the `status` method to incorporate this
* Adjust tests for the Pregnancy model / status method

**Comment by ashlynnpai** [comment]
I'll take a stab at it.
