### ISSUE TITLE
Filter :search in system logs

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#529]
Let's make sure to filter out `:search` from application logs, in addition to PII in our actual model fields. 

See #382 for the first pass at this -- should be as simple as adding another field.

**Comment by benjamincrane** [comment]
I have a commit adding :search to the filter parameters. I did a basic test on Cloud9 and the system log shows "[FILTERED]" in the Parameters output when I use the search function so I think it is working.
