### ISSUE TITLE
What procedure should we use to rename fields in the live db?

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#533]
It seems like when we change a db model field, existing objects stop saving until you run `rake db:seed` again. That's not a tenable situation after we start storing actual production data in the system.

What are best practices around this? Is there a gem we can install, or some rake task we can write which will automatically update? 

@Kevin-Wei especially interested in yr thoughts here, since I imagine this is a problem you've run into before.

**Comment by colinxfleming** [comment]
Now that we're storing production data, probably time to address this! Because I suspect this is something that someone familiar with mongoid has a workaround for, and because I want to have a solution on file, I'm marking `hacktoberfest`.

A test case, for reference:

* The user model has a field `role`, currently stored as a string. It's all null at present
* Soon we'll be changing that to an enum, which has a datatype of Int

Questions: 
* What do we run to change the datatype?
* If `role` actually had data in it, would we run something different if we wanted to keep that data?

**Comment by pcofilada** [comment]
@colinxfleming I think since you are using mongoid you can just change the datatype of a field on the model and regarding on the data you should need to create a rake task for this.

**Comment by colinxfleming** [comment]
@pcofilada thanks -- I kinda figured that was the case, so I'm glad moving something is straightforward enough. Do you by chance have an example of a rake task (or want to toss one up in a PR 🎆 )?

**Comment by pcofilada** [comment]
@colinxfleming I'll just have a PR for this. Just let me know what specific fields you want to change.

**Comment by colinxfleming** [comment]
@pcofilada that'd be lovely, if you'd be so kind! In the short term we're going to be changing `User#role` from a string to an enum (so an int, in practice), so that's the immediate need. But major bonus points if it's something flexible enough to adapt in case we have to do this in the future. Thanks so much for your time and brainpower!

**Comment by pcofilada** [comment]
@colinxfleming Already submitted a pull request. Just let me know if you have any questions.
