### ISSUE TITLE
Have to install MongoDB, Bundler on Cloud9

### ISSUE THREAD

**Issue by benjamincrane** [colinxfleming/dcaf_case_management#534]
Currently the instructions for working on this in Cloud9 seem to be out of date. I had to install another version of Ruby, then the Bundler gem, then install Mongo in the Cloud9 workspace.

**Comment by colinxfleming** [comment]
Thanks a ton for documenting this! Do you remember what commands you ran /
want to fire up a pull request with suggested Readme changes?

**Comment by benjamincrane** [comment]
I can try. I would be more confident but I wasn't able to get MongoDB to work on Cloud9 so first I need to figure out what went wrong with that.
