### ISSUE TITLE
Plan September Launch Party! 

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#548]
We are launching DCAF Case Manager to the entire DC line by early September. Let's celebrate!

**Comment by colinxfleming** [comment]
Backlog until September! (But then let's party up!)

**Comment by colinxfleming** [comment]
@mebates and I discussed this a few weeks back and I think we decided mid-September. A good thing to do here would be to poll the group and Mollie and select a day that works for everyone, and log that and the venue in this ticket.

**Comment by mebates** [comment]
@colinxfleming we discussed a weeknight affair with pizza, drinks, and treats. here's the doodle!
http://doodle.com/poll/33nixf5gqazgbzkt

**Comment by mebates** [comment]
The party will be on Sunday, September 18. Check slack for more details, coming soon! @lwaldsc and @ajohnson052 we hope you can somehow swing it - lmk if any timing changes would help!

**Comment by mebates** [comment]
September 18
6-9 pm
Mollie's house
check slack for details

@colinxfleming : order pizza
@mebates : make salad, get plates, cups, silverware, make cake, make sure house is presentable
