### ISSUE TITLE
Update Cloud 9 instructions in Readme to be beginner friendly

### ISSUE THREAD

**Issue by ewiggins** [colinxfleming/dcaf_case_management#549]
Idea from #544.
- [Create detailed instructions from setting up a cloud9 account ] 
- [ Take screenshots]

Create a detailed step by step on how to sign up for a Cloud 9 account and begin coding on your first beginner friendly issue stress free!

**Comment by ewiggins** [comment]
I'm going to work on this once #544 and #534 are closed.

**Comment by colinxfleming** [comment]
Love this. Thank you for tackling @ewiggins !

**Comment by colinxfleming** [comment]
Closing as a wontfix, since this has been sitting in the backlog for a little while and I'm not sure what it entails these days. @ewiggins let me know if I should reopen!

**Comment by ewiggins** [comment]
Hey , I think this was born out of the fact that I didn't have much ruby on rails experience at the time. Now I think it fine . :100:
