### ISSUE TITLE
Write service administration manual

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#554]
Placeholder issue for writing the systems administration manual for this. cc @NerdyGirl537

**Comment by mebates** [comment]
What format will this take?

**Comment by colinxfleming** [comment]
Made an initial brain dump in the google drive, will follow up with @NerdyGirl537 after deployment.

**Comment by colinxfleming** [comment]
I did this and turned over to the DCAF board, I think we can call this resolved for all intents and purposes. Marking closed.
