### ISSUE TITLE
Write user manual

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#555]
Placeholder issue for writing the user manual for CMs. cc @lwaldsc

**Comment by mebates** [comment]
What format will this take? GitHub wiki? Google Drive? Doc, PDF?

**Comment by colinxfleming** [comment]
I think my ideal format is something we can have under version control - so maybe something similar to the readme, like `MANUAL.md` in the root directory with the readme?

**Comment by colinxfleming** [comment]
Made the ask to @lwaldsc @SabrinaRitacco @eheintzelman (and summoning them to this thread). I trust their judgment about what to document. 

To walk back my earlier statement about having a markdown doc, I'd like it to be that eventually, but that's secondary to actually having it written, so please do whatever's easiest to crank out and collaborate on between each other. 

Thanks all!

**Comment by mebates** [comment]
I have a feeling that we might want the Manual to be private, as well. It will probably contain instructions that we don't want to share with the world (login, etc).

**Comment by colinxfleming** [comment]
@mebates That's a very good point, I think I lost sight of this. 

Team UX and @lwaldsc can you write in a googledoc for now, and we'll figure out with the CM admin team where this should live long term?

**Comment by mebates** [comment]
Just agreed that @lwaldsc will put the final user manual in Crypto in a non-editable Word doc and update as necessary from the google doc

**Comment by colinxfleming** [comment]
Solid. @lwaldsc please flag when you've popped it in crypto and close it out? Thanks a ton for taking lead on this.

**Comment by colinxfleming** [comment]
I think at this point I'm very comfortable declaring victory on this -- we have a well-assembled user manual that covers major functions. I'm marking this complete.
