### ISSUE TITLE
Write integration test for drag and drop

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#572]
PR #539 puts together a slammin' function for drag and drop reordering of call list... that I have no idea whatsoever how to write an integration test for. We shouldn't overlook this, but shouldn't address before launch on Aug 22.

**Comment by colinxfleming** [comment]
Promoting from the backlog. Drag and drop is kind of a key feature in the workflow we've built, and I think it's important to represent. Would be awesome to have an integration test dedicated just to this!

**Comment by Kevin-Wei** [comment]
Found a drag_to in capybara http://www.rubydoc.info/github/jnicklas/capybara/master/Capybara/Node/Element#drag_to-instance_method

**Comment by Kevin-Wei** [comment]
PR should be good now
