### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by stvnrlly** [colinxfleming/dcaf_case_management#58]
This is a great resource is one is needed: http://choosealicense.com/

**Comment by colinxfleming** [comment]
Thanks for Choose A License Dot Com, @stvnrlly !

After looking, I think either an MIT or a GPL is our best bet. I think the major question that should drive the decision here is whether or not we want to keep work any work based on this open as well, or whether we're fine with it if another fund takes this, adapts it to their own need, but doesn't share their improvements. If we're cool with that, MIT is our bag; if we're not cool with it, I think GPL v2 is what we'd want.

**Comment by stvnrlly** [comment]
The goal of GPL is noble, but as a CC0 aficionado myself, I'd lean toward the MIT license.

**Comment by colinxfleming** [comment]
I mulled it over a little and think @stvnrlly is right to point us toward MIT -- will take the steps to add that soon. If you have an objection please raise with me.
