### ISSUE TITLE
UX: Call modal "other contact info"

### ISSUE THREAD

**Issue by mchelen** [colinxfleming/dcaf_case_management#585]
There are 3 fields from "other contact info" that are displayed in the call modal:
Other contact name
Other contact relationship
Other contact phone number

With #584 the modal will display properly only if all 3 are filled out.

In what way should we handle situations where only some of these fields are filled out?

**Comment by mebates** [comment]
I think that we need name and phone number at a minimum. Relationship seems optional

**Comment by mchelen** [comment]
Ok, added to #584
