### ISSUE TITLE
Create a footer

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#587]
Create a footer! And populate it with the following:

"Please send feedback or ideas for the CM App to DCAF.CMapp@gmail.com." (mailto link)

DCAF phone number, website
NAF phone number, website
onlinefaxes.com
+ <strike>link to User Manual in Crypto</strike> (later)

cc: @lwaldsc

**Comment by colinxfleming** [comment]
Promoting from backlog!

**Comment by NerdyGirl537** [comment]
@mebates 

DCAF phone number, website: 202-452-7464  http://dcabortionfund.org/
NAF phone number, website: 800-772-9100  https://prochoice.org/

**Comment by jasonallenphotography** [comment]
Working on it!
