### ISSUE TITLE
FRIDAY Establish multiple call lines on start

### ISSUE THREAD

**Issue by jayzmiles** [colinxfleming/dcaf_case_management#589]
Based on - "As a CM, I need to be able to choose the call line I'm working on tonight so that I input patient's data into the correct line"

**Comment by jayzmiles** [comment]
A couple questions/observations we ran into:

- Is there a situation where a user (in any role) would need to view information from multiple call lines at once?
- We may solve for this issue from the perspective of the CM and then work on adapting this feature to other roles? (higher-level views for DCAF leadership or others)

Please feel free to add anything I missed, @eheintzelman.

**Comment by eheintzelman** [comment]
@lwaldsc @NerdyGirl537 We would like your input. We discuss at the Sept 4th meeting if that's easier.

Here are a few follow-ups to Jay's comment above, focusing on solving the permissions issues from the perspective of the CM:

1- Are there times, outside of working a line, when a CM would need access to the system?  If so, for what purpose? 
2- While working one line, are there situations when a CM would need to view or edit data for a different line?
3 - Are there situations when a CM would need to work multiple call lines?

**Comment by NerdyGirl537** [comment]
@eheintzelman, the short answer on all three is currently no.  On the second item, there is a slight likelihood that a caller might select the wrong line and the CM not realize until after entering in the patient into the system.  That might require accessing the other line's data or some other way to get the patient's info.  

@jayzmiles, the CM directors and the treasurer may.  It's difficult to say without having the budget function built out and no reporting functions.  It might be better to ask the CM directors and treasure.

**Comment by eheintzelman** [comment]
@NerdyGirl537 That certainly keeps things simple. What about the CMs handling the Spanish-only patients?

**Comment by eheintzelman** [comment]
@colinxfleming Call line selection is ready for development.  It turned out to be quite simple for the CMs since there are not needs to access multiple lines at the same time or toggle between lines. We are not tackling roles other than CM that might benefit from the ability to view information from multiple lines at once in this user story. 

1. Add concept of 3 lines (in code).  DC Line, MD Line, VA Line.

2. Add screen allowing the user to select call line. 

Welcome to DCAF! (h2)
(blank space)
What line are you working tonight? (h3)
DC Line    MD Line   VA Line   (label/body; radio buttons; options are mutually exclusive) 
Cancel (color: red; otherwise standard button styling) Start (Standard button styling; justify right with cancel button)

3. Let the user know what line they are on in the header under "DCAF Case Manager." Options are DC Line, MD Line or VA LIne

**Comment by colinxfleming** [comment]
Awesome, thank you very much team UX! Going to quickly jot down some thoughts:

* The concept of lines is represented in the object model already, thankfully.
* We'll need to find a good way to scope a patient's experience to a particular line. MVP is locking to a particular url (e.g. `dcaf-cmapp-staging.herokuapp.com/dc` or something), nicer version is probably some kind of a session attribute that we can use to scope db queries.

This is pretty straightforward, so thank you for that!

I have one question about implementation, code-wise: If they're seeing this page as soon as they log in, what should the cancel button do?

**Comment by mebates** [comment]
Perhaps instead of cancel, it should say 'logout'?

**Comment by eheintzelman** [comment]
'Logout' makes more sense, yes.

Unless we removed the cancel/logout option altogether?  How important is it to give users the option not to start a session after all, once they have logged into the system?

**Comment by colinxfleming** [comment]
I can't really think of a case where someone would log in and not want to start a session of some kind, really. I'd vote for removing cancel as an option and making them dive right in.

**Comment by colinxfleming** [comment]
Also, I'm reasonably sure we can knock the major components of this out in a hacknight, so I'll try to slate it for either this coming one or the one after.

**Comment by colinxfleming** [comment]
Promoting to backend/question since now this is pretty much ready to go from a UX standpoint. 

I think how I'd like to have this shake out is to have picking a line assign a session variable, and then scope queries through that session variable. Thoughts?

**Comment by colinxfleming** [comment]
Going to keep this as the admin thread for discussion of this feature and spin things off, to keep the issues as straightforward as possible. Setting up the view and route is repped in 683, and once that's built we can worry about the backend logic.

**Comment by mebates** [comment]
I think we're done from this, in terms of questions and design. Closing.

**Comment by colinxfleming** [comment]
@mebates going to keep it open just as a feature 'master issue' we can spin stuff out of so I don't lose track of it! But yeah, the design stuff is all done, just have to knock it out. 

Have retitled to make it clearer that the UX component is set!

**Comment by colinxfleming** [comment]
Remaining steps after #745 gets merged:
