### ISSUE TITLE
Add civic.json

### ISSUE THREAD

**Issue by stvnrlly** [colinxfleming/dcaf_case_management#59]
See http://open.dc.gov/civic.json/ for more information.

**Comment by colinxfleming** [comment]
Info we'll need/want to fill this out: 

* Page url 
* Any partner info (include Mollie, Andrea, other contributors?) 
* License

**Comment by stvnrlly** [comment]
Note that only `name`, `status`, and `tags` are required fields. I don't think this project has a homepage (though the repo is fine) and partner info would traditionally mean just DCAF (with the rest of us working on behalf of Code for DC). And of course the license will follow quickly after #58 :smile:.

**Comment by colinxfleming** [comment]
Resolved in #81
