### ISSUE TITLE
DCAF Training: small issues 

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#593]
Collecting some small issues we saw or heard during the DCAF team training. We can break these out into smaller issues and prioritize if necessary. 

Dashboard/Status:
- Nice to see everything that happened on the last shift (a record of the patients served by the previous CM) (#654)
- "Nervous about somebody falling through the cracks" "Should I mark each of my unresolved patients as 'Urgent' to make sure the next CM has them? NO!" " (I think this has been trained around)
- Should PTs stay on call list if they weren't reached, but if they have been reached before? (open question, is this actionable?) (nothing to do at present, should keep an eye on things)
- Should there be a way to search for a patient and get to their profile without adding them to the 'call list'? (There kinda is, just plugging them into the search bar and then clicking their name)
- Need to do some work on the "Pledge Sent" status in the case of a pledge being sent but then the status going backwards if circumstances change (this is true. We probably need an omnibus pledge action item.)
- Is there a way to flag a person who's been unresolved (playing phone tag) for a while? (#678)
- Request for flag that is a good 'story' for fundraising/blog purposes (I want to discuss this with the CMDs first before we turn it into an action item)
- Could the system automatically mark someone as urgent of the appt is days away and a pledge hasn't been sent? (#679)

Add new PT:
- Phone number box needs to be wider so you can type a full number and see it (resolved)
- Data columns not lining up with the call list data table below. what's going on there? (not sure this is still an issue)
- need error state for an invalid phone number and ability to let them type that in again without having to fill out all other fields. (repped in #274)
- Stretch: is there a way of flagging that a patient's LMP is approaching the clinic's cutoff? Could be especially helpful for PTs in Virginia (ref for #146, when we implement clinic stuff later)

PT view:
- Remove calendar icon from Appointment Date field (It looks like a date picker and it's not) (#660)

PT info:
- Request for additional language box for 'other' (not served by notes?)
- Add "Other (add to notes)" option to Patient Insurance (#680)

Abortion info:
- Add option to Clinic dropdown that says "Other (add to notes)" (donezo)
- Add "Other funds" under Cost Details ? (repped under external pledge)
- Reconsider adding calculations into Cost details (repped in a diff issue)
- Include soft pledge recommendations based on LMP (#793)
- Add section for "Access exception" (as an 'add other cost' element) (#794)
- Add PP discount (as an 'add other cost' element) (#794)

Notes:
- Mollie Request: Notes meta data shouldn't be styled as a table. We can just stack "Name, Date, time" above the note and eliminate the bar. The meta data should not be in all caps (#795)
- Spell check? (not worth it until we hear otherwise)
- Nice to be able to email a user's email address from the notes! (#795)
- Save notes draft as I'm navigating from page to page (this is unlikely to be worth the dev time, I'm saying nah for now)

Submit pledge:
- <strike>Continue button not working !!!</strike>  (#597)

**Comment by colinxfleming** [comment]
Thanks a ton for logging these, @mebates !

I'm going to spin off the continue button not working as a bug and fix it before showtime, since that's something we need to be functional on Monday. The rest of these we can spin off and triage as normal.

**Comment by colinxfleming** [comment]
Marked up around half of these, so we can take advantage of additional eyes during hacktoberfest.

**Comment by colinxfleming** [comment]
Clearly actionable stuff here has been spun into an issue -- closing. The rest, I think we should wait to see if they pop up again. 💯
