### ISSUE TITLE
Fix javascript error that is causing the pledge form to not pop up

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#597]

**Comment by colinxfleming** [comment]
Consulting with @NerdyGirl537 and it seems to be a similar-ish problem to our notes problem that alexis fixed a few weeks back -- something about reloading the page after wrenching on the patient fixes. Wonder if there's some field we have to fill out for the modal to produce valid code.

**Comment by mchelen** [comment]
I can take a look, what are the steps to reproduce?

**Comment by colinxfleming** [comment]
Mike you're a gem.

From the dashboard:
* Create a new patient by searching for someone not in our system
* Click over to their view page
* Click submit pledge -- this makes their modal pop up

At this point, the expected behavior is:
* Clicking continue in the Create Pledge modal should take the modal to the
next step, the 'preview your pledge' thing we haven't yet hooked up

The actual behavior is:
* It doesn't do anything

Note that the workaround here seems to be literally just reloading the
page. On second view it seems to work okay, which is mysterious!
