### ISSUE TITLE
add appropriate materials from Google Drive to repository

### ISSUE THREAD

**Issue by mattbailey0** [colinxfleming/dcaf_case_management#6]
To ease onboarding of new members, we should move whatever material we can (i.e. stuff that is appropriate to make public) to the repository from the Google Drive.

**Comment by mebates** [comment]
For now, I've added wireframe links from google drive (with open access) to the bottom of the ReadMe. But I agree that we should add a folder with design assets.

**Comment by colinxfleming** [comment]
@mebates Are there other assets from Drive we need to add, or can we pretty much consider this good to go?

**Comment by mebates** [comment]
I think this is good for now, once you merge my pull request. If any other missing items come up, we can reopen the issue.
