### ISSUE TITLE
Improve error message when unable to save patient

### ISSUE THREAD

**Issue by mchelen** [colinxfleming/dcaf_case_management#605]
When creating a new patient via "Build your call list" the patient creation requires these fields:
- phone number (must be valid_
- name

If they are missing or invalid, an error appears:
> An error prevented this patient from being saved

It would be nice to make this error more specific, such as
> Error: missing patient name

or
> Error: invalid phone number

**Comment by colinxfleming** [comment]
Right now it's not super clear why things aren't saving, so this is an opportunity to reduce an identified point of frustration for our users. 

It should be as simple as correcting the error rendering in the patients controller (though please do some googling around to follow best practices etc).

**Comment by Kevin-Wei** [comment]
When the save fails we just need to update the flash msg to use the .errors hash in the create action on the patient's controller

**Comment by danfowler** [comment]
Looking into it 👀
