### ISSUE TITLE
Fix mailer from info

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#607]
password reset info comes from noreply@dcaf.org which is not a real thing. Should take steps to make it look like actual dcaf.

**Comment by Kevin-Wei** [comment]
I'll take a look at this

**Comment by Kevin-Wei** [comment]
default from: 'no-reply@dcaf.org' is set in user_mailer.rb. Are we just trying to plug in something that makes more sense?

**Comment by colinxfleming** [comment]
yeah, pretty much. Can we set a global default of
no-reply@dcabortionfund.org?

**Comment by Kevin-Wei** [comment]
devise.rb has a default you can set there too   config.mailer_sender
