### ISSUE TITLE
Standardize modal code & style

### ISSUE THREAD

**Issue by mchelen** [colinxfleming/dcaf_case_management#612]
There are at least 2 different types of modals being used, such as the call modal and the pledge modal. Because they have different code & styling, they have different animation style, button styling, and only the call modal is successfully closed by clicking elsewhere on the screen.

The different types should be standardized, with code & styling reused between them.

**Comment by colinxfleming** [comment]
Promoting this from the backlog.

This is a great opportunity to remove a lot of redundant code and abstract it into something very effective. I'm looking for something along the following lines:

* Create a `modal_helper` with a method that generates code for a modal, and takes content as arguments
* Standardize the animation, code, dismissal, and button styling in this modal
* Replace the new call modals and pledge modal with this standardized modal
* GOLD MEDAL: Have it be an empty thing until it pops up, and then have it populate contents dynamically! This will fix a lot of CM complaints and make the system generally feel less janky. 
* Add unit tests for methods in the modal helper

**Comment by mebates** [comment]
And have a designer take a look at the visual design! When you submit a pull request, please include a screen grab so we can take a look. Thanks!

**Comment by mchelen** [comment]
2 places where current modals are:
Call modal
`app/views/calls/_new_call.html.erb`


Pledge modal
`app/views/patients/_pledge.html.erb`

**Comment by colinxfleming** [comment]
Resolved by #809 !
