### ISSUE TITLE
Plan next training

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#619]
cc @lwaldsc

**Comment by colinxfleming** [comment]
A few thoughts from conversation with @lwaldsc : 

* the first cast of CMs is about done with the system. Soon we'll be starting round 2, so another training of the second squad is probably in order. Let's start shopping dates in mid-September
* sooner rather than later we should get this process into the CM directors' hands again so we can focus @lwaldsc on user feedback and pushing forward design. Maybe one more training organized by the project team and then it's CM leadership's problem to handle
* CM Katelyn took to the system really fast and might be good to tap to co-lead a training

**Comment by colinxfleming** [comment]
Updates to this:

* Date set for Sep 22, 630-8pm, led by @lwaldsc 
* Team CMD will be taking on training responsibilities within DCAF after that. (Let's make sure to ask them to write a manual that we can share with other funds if possible.) 
* need to CM Katelyn if she wants to co-lead, since she's our reigning expert. (Want to make sure we confirm with Lisa before asking though)
* we'll have 2-3 CMs who will be CMing before the training and who haven't gotten onboarded, may want to explore having a one-off with them

Let's try and have the remaining outstanding stuff resolved by the end of the upcoming code for dc mtg.

**Comment by colinxfleming** [comment]
TODO for me: Print out training manuals and get them to the library
Approx headcount at this time: 22ish
Lisa's on point for asking KBC if she'd like to join for training

**Comment by lwaldsc** [comment]
Training went really well. CMs in attendance flagged a lot of the same issues already discussed in #614. Seemed very excited about the system and eager to use it in real life.
