### ISSUE TITLE
Validate patient uniqueness on primary phone

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#620]
Barely a week in and we're already starting to run into duplicates on phone number. Let's add a validation such that Patient is unique on phone number as soon as we can. (Step two is merging duplicates already created in production, but I'll handle that part of it when this PR is ready to deploy.)

**Comment by jasonallenphotography** [comment]
On it!

**Comment by jasonallenphotography** [comment]
Pull Request #624 is in, build passing.
Please let me know if I may be of further assistance!

**Comment by colinxfleming** [comment]
Closed via #624
