### ISSUE TITLE
Appointment date added to Dashboard information

### ISSUE THREAD

**Issue by lwaldsc** [colinxfleming/dcaf_case_management#629]
Related to #510 

A few CMs have flagged they would like a PT's appointment date in the dashboard information so they can also prioritize PTs with close appointments 

![image](https://cloud.githubusercontent.com/assets/10578608/18487690/269479be-79c4-11e6-9356-499a236130d6.png)

**Comment by mebates** [comment]
Cool! Should be easy to add, just squeeze the space we leave for comments.

**Comment by colinxfleming** [comment]
Promoting this to active!

**Comment by lwaldsc** [comment]
Fantastic!

**Comment by colinxfleming** [comment]
Tagging as hacktoberfest. This entails going in to `app/views/_table_content.html.erb` and adding a table cell with `patient.appointment_date` (or maybe patient.pregnancy.appointment_date`, I forget which). This in turn will be a great help for our case managers as they prioritize calls. 

If necessary to get the squeezing right, you can adjust the note text length in the patient model, IIRC.

**Comment by nickgnd** [comment]
Hi, 
I would like to work on this issue, I'll give you a PR asap :)

**Comment by colinxfleming** [comment]
Fixed in #671
