### ISSUE TITLE
Add "hard pledge" box

### ISSUE THREAD

**Issue by lwaldsc** [colinxfleming/dcaf_case_management#630]
We will eventually need a hard pledge box as well as soft pledge for budget tracking.

**Comment by mebates** [comment]
Does a soft pledge simply turn to 'hard' upon submitting the pledge? Perhaps we ask them to confirm the amount during the 'submit' flow?

**Comment by NerdyGirl537** [comment]
I think there is an opportunity here to look at how we track pledges in the future.  The soft vs hard pledge, I think, is related to how we stored data on the spreadsheet.  We should really look at how we want to manage the budget and reflect available fund for the CMs.

**Comment by colinxfleming** [comment]
I agree with Jenn here, I think getting away from the notions of hard vs
soft pledge would be really great. Would love to ditch that concept
entirely if at all possible.

**Comment by NerdyGirl537** [comment]
Brain dump here for discussion and design of budget functionality:

The main thing a CM needs to know when coming on shift is actual funds available and projected spending for the week.  The budget resets at the beginning of the week (Mondays).  Each line as a specific budget.  If coming on shift on Monday, there is normally the full budget available but there may be some pending appointments already in the system that will get pledged.   If coming on shift on Thursday, some of the budget has already been used and there are likely pending appointments in the system needing a pledge.  

I'm thinking we need to start talking about pledges as completed/sent or as outstanding/unsent.  Like the patient status, the pledge status only changes (and affects the budget) if the CM click the pledge sent button.  We also need to look at the budget bar display for this.  Can we do a pale gray for outstanding pledges for the week, kind of like a shadow?  Also wondering about the colors for the budget bar.  Do we want to do a traditional green/yellow/red?  Would a different color scheme be better to help CMs understand going over/asking for exceptions is okay? (I was thinking of using the new DCAF color scheme).  

For outstanding pledges, we will have two kinds:  those expected to be pledged during the current CM's shift and those that are for future budgets.  It would be great if there could be a report generated that showed all outstanding pledges by appointment date.  That would help CMs manage their budget.  I'm also thinking it will be similar to the report for reconciling pledges for payment.

How do we want to handle exceptions to the budget caps that the CMDs authorize?  How does that affect the budget bar?  Have we started talking to Crowfoot (Board treasurer) yet about those needs?

Dump done.

**Comment by verbingthenoun** [comment]
Just to clarify on "hard vs. soft pledges" what I think would be most useful is being able to track what was pledged over time, and then have a separate place to denote the final amount sent to the patient. Right now, the system can only store one number for the pledge and I think it would be really helpful to see how pledges changed - do we usually shoot low/high? Are pledges more likely to be sent if we give a higher initial number? Etc.

**Comment by lwaldsc** [comment]
Just a quick thought on color scheme: I'd avoid red/green for accessibility
issues. I'm sure Mollie has more insight into this as the actual designer
on the team.

Backing off of Alexa's thought, it would be nice, data-wise, to see how our
CMs use soft pledging versus hard pledging. It may not look like a separate
"soft" versus "hard" but knowing how pledges change over the course of our
interaction with a PT could be useful.

**Comment by NerdyGirl537** [comment]
To Alexa's comment on seeing how the pledge changes, would it work if it was stored in the change log?

**Comment by colinxfleming** [comment]
Yeah, @verbingthenoun 's problem description is totally something we can engineer around with the changelog / audit trail. Thrilling that we'll be able to start to answer these questions.

I'm onboard with @NerdyGirl537 's excellent writeup of the problem here -- I think we're using different vocabulary for the same ideas of hard/sent and soft/unsent. 

To confirm, @lwaldsc do you think that an explicit 'hard pledge' box gets us anything special, other than reducing a bit of confusion from CMs used to the idea of hard/soft pledge? If not, I think we:
* close this issue as a `wontfix`
* make sure that as we build out budget, we're cognizant of money spent outside of the current week. 

@lwaldsc yr thoughts?

**Comment by mebates** [comment]
Just found all of these great comments about pledge type. I think we should close this issue and shift it over to the budget bar issue. #692 We don't need to add an actual hard pledge bar!
