### ISSUE TITLE
Add "Other medical issue"

### ISSUE THREAD

**Issue by lwaldsc** [colinxfleming/dcaf_case_management#631]
Need to add "Other Health issues" checkbox to the special circumstances

**Comment by mebates** [comment]
Is that valuable from a data-collection lens? Or just something that can be noted in 'notes'?

**Comment by lwaldsc** [comment]
As valuable as collecting any other special circumstance, yes.

**Comment by colinxfleming** [comment]
I wonder if there are other special circumstances we're missing -- was Other health issues in the spreadsheet and we just missed it? Or is this something that people were putting in when the spreadsheet validation broke?

**Comment by colinxfleming** [comment]
Outstanding question here is to figure out whether there are other special circumstances we're missing. That's on me, I'll figure it out this weekend.

**Comment by colinxfleming** [comment]
Was slacking on this -- emailed the CMDs tonight, will update thread when I hear back and then we can plan based on that.

**Comment by vtmeghan** [comment]
@lwaldsc and I think that other medical issue needs to be added. Should also add "Minor," and "Undocumented." Also CMD Kate had flagged changing "fetal anomaly" to "fetal diagnosis." @mebates @colinxfleming @NerdyGirl537 @eheintzelman

**Comment by colinxfleming** [comment]
@vtmeghan @lwaldsc  we can back out minor from age, no? 

It sounds like the task coalescing around here is the following (assuming that we don't need to collect `minor` twice):
* Add `Other medical issue` and `Undocumented`
* Change `Fetal anomaly` to `Fetal diagnosis`

@vtmeghan @lwaldsc can you approve this course of action?

**Comment by colinxfleming** [comment]
Also I don't think there's a design issue here given how this is currently rendering -- plenty of space we can utilize.

**Comment by lwaldsc** [comment]
Yeah, grabbing it from age works perfectly.

**Comment by mebates** [comment]
All sounds great to me!

**Comment by colinxfleming** [comment]
This is ready to rumble! Most likely it just involves making a few changes to the part of the patient view and making these edits in the form. Please refer to directions in https://github.com/colinxfleming/dcaf_case_management/issues/631#issuecomment-255921472 .

**Comment by KatSDC** [comment]
Going to start working on this!
