### ISSUE TITLE
LOGIN: Create registration screen

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#64]
Create a view with basic signup information with necessary information from the User model -- nickname to use, email address, set password, etc.

**Comment by mebates** [comment]
This is related to issue #51! I'm all for making a really plain MVP for now, but please see if we can start with the US Federal Web Design Standard for login screens: https://playbook.cio.gov/designstandards/form-templates/#login-form

**Comment by colinxfleming** [comment]
I'll tackle this during the weekend! Will just copy the fed suggestions for now, and we can tweak slightly after MVP.
