### ISSUE TITLE
How to handle phone extensions?

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#641]
This happened while I was entering data into prod -- we strictly format phone to 10 characters, and I couldn't squeeze in an extension and had to put it as a note in 'Other Contact' instead.

Should we add a field for extension somewhere, or just rely on other contact/notes to handle this? Any opinion or best practices from team ux?

**Comment by mebates** [comment]
I would vote for notes. Generally want to reduce complexity and not design for the edge cases.

**Comment by colinxfleming** [comment]
Notes works for me. @lwaldsc and @NerdyGirl537 please reopen this issue if you object to this course of action.
