### ISSUE TITLE
Break out clinics all the way

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#642]
We have some grouped ones -- PPMW is one entity in the app, and that represents a few diff clinics. @NerdyGirl537 pointed out that we will probably need to break this out so that we can find the correct fax number. 

Let's either break out the environment variable more, or start writing clinic yaml.

**Comment by vtmeghan** [comment]
@lwaldsc and I think that we definitely need to break up the clinics, especially PPMW and other affiliates. We could do it similarly to how it used to be in Crypto where you picked the clinic and then the location in a separate field - for most clinics, this would auto-populate/only be one option, but for PP and some other clinics, you would have several options to choose from. (And eventually we'd need this to be broken out anyway for the pledge form, which ask for both clinic name and location.) @NerdyGirl537 @colinxfleming @mebates @eheintzelman

**Comment by vtmeghan** [comment]
Prioritize for sprint 11

**Comment by colinxfleming** [comment]
As @mebates noted in another thread, clinic validation is a priority for second release. We should handle this as part of #203 .

**Comment by colinxfleming** [comment]
Resolved by #975 . @vtmeghan please make separate clinics be separate entries.
