### ISSUE TITLE
Investigate MongoDB indexing

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#645]
Are you great at MongoDB performance tuning, or interested in learning about it? Then I have a great opportunity for you!

As we continue to create more and more records, I'd love to keep our search functionality snappy. I suspect that the way to do this is to add indexes on the stuff we search for all the time, but I leave it up to the person taking this on to investigate and recommend a path forward via a pull request. 

Here are the fields users search on all the time:
* `Patient#primary_phone`
* `Patient#other_contact_phone`
* `Patient#name`
* `Patient#other_contact`

And here's something our system regularly uses when loading the dashboard:
* `Patient#urgent_flag`

**Comment by Kevin-Wei** [comment]
all about https://docs.mongodb.com/ruby-driver/master/tutorials/6.0.0/mongoid-indexes/
