### ISSUE TITLE
ADD PATIENT: Design screen for adding basic patient info from a voicemail

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#65]
CMs are logging calls from voicemails with some basic data entry. We'll need a design for this.

**Comment by mebates** [comment]
I think this can be solved very simply by adding a 'name' field to the gray well we already have designed. The case manager has already entered the phone number, so if we require that they also enter the name  before 'add new patient to call list' we have enough good information to get the case started.

This could prove wrong in usability testing -- perhaps a lot more info comes in on the voicemail -- but what do we think about starting here?

![screen shot 2016-02-08 at 7 03 56 pm](https://cloud.githubusercontent.com/assets/6223901/12903942/d139fa00-ce99-11e5-80f6-571543eb2776.png)

**Comment by mebates** [comment]
Tonight I asked Lisa and Jen, what info do you usually hear on the voicemail?
- name (sometimes this is garbled)
- phone number
- weeks pregnant
- and can they leave a voicemail or not

**Comment by mebates** [comment]
After a quick chat, I think we should include both name and LMP and make both fields *optional* since the case manager may or may not get all that information from the voicemail.

![screen shot 2016-02-08 at 7 34 52 pm](https://cloud.githubusercontent.com/assets/6223901/12904142/21c9e16e-ce9b-11e5-9f91-f6e39f85396d.png)

**Comment by mebates** [comment]
This interaction has been updated in InVision (along with some other updates thanks to Lisa and Jen!) 
https://invis.io/6757W6WFJ and a pull request was made with native files: https://github.com/colinxfleming/dcaf_case_management/pull/76. Considering this closed!
