### ISSUE TITLE
Add monthly income text to options on income select

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#657]
Nice free basket from a CM -- it would be helpful if income options included monthly income, since that's how a lot of patients talk about their incomes in practice.

Two things to do here:
- The option displayed in the select should include monthly income (ex: `Under $9,999 (less than $192/wk - $834/month)`)
- The value persisted in the database should be just the first part of the option. e.g. Instead of saving `Under $9,999 (less than $192/wk - $834/month)`, we should just save `Under $9,999`.

To implement, you can just fix up the array in `PatientsHelper#income_options` to something you could drop in a `form_for` block.

Came up in #614

**Comment by souphan** [comment]
I'll take this =D.  I'm new to Ruby, so I will most likely have questions.

**Comment by colinxfleming** [comment]
ayo @souphan let me know if there's anything I can help unstick on this!

**Comment by souphan** [comment]
Hello Colin,

I modified the monthly income portion, but am having issues finding the portion that stores the selection to mongodb.  I was under the impression it would be under /config folder.

**Comment by colinxfleming** [comment]
To close the loop on this -- we talked about this in slack and unstuck this!

**Comment by colinxfleming** [comment]
@souphan check this stuff out -- http://guides.rubyonrails.org/form_helpers.html#the-select-and-option-tags

The stuff in the second code block in 3.1 is what I'm talking about. Basically, there's an array of two-piece arrays getting put in that looks like this:
```
[
  ['display thing 1', 'actual value 1'],
  ['display thing 2', 'actual value 2'],
  ...
]
```

and what rails is doing when it builds that form into HTML is turning it into something like this:

```
<option value='actual value 1'>display thing 1</option>
<option value='actual value 2'>display thing 2</option>
```
where it goes thru each item in the array, and then the first value is what shows up in the dropdown, and it saves the value of the second item to db. So we need to convert the income array to something like: `[ ['display item 1', 'value1'], ['display item 2', 'value2']... ]`.

Is that helpful?

**Comment by souphan** [comment]
Thanks for the helpful explanation.  I will update you once I get this done, or have any other questions.

**Comment by souphan** [comment]
I just got around to doing this again, and I believe this is what you wanted:

 <%= f.select :income,
                       options_for_select([[income_options[1],'Under $9,999'],
                                           [income_options[2],'$10,000-14,999'],
                                           [income_options[3],'$15,000-19,999'],
                                           [income_options[4],'$20,000-24,999'],
                                           [income_options[5],'$25,000-29,999'],
                                           [income_options[6],'$30,000-34,999'],
                                           [income_options[7],'$35,000-39,999 '],
                                           [income_options[8],'$40,000-44,999'],
                                           [income_options[9],'$45,000-49,999'],
                                           [income_options[10],'$50,000-59,999'],
                                           [income_options[11],'$60,000-74,999'],
                                           [income_options[12],'$75,000 or more/yr'],],patient.income),
                                           autocomplete: 'off' %>

Let me know if that is the case.  Sorry for being slow on this.
