### ISSUE TITLE
What cheatsheets should we port over from Crypto?

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#658]
Brought up in #614 -- There are a few valuable reference sheets that still live in crypto, so as part of our effort to completely get out of crypto by the end of the year, it would be awesome to port these over. 

@NerdyGirl537 and @lwaldsc can you log the types of information in there, if there's anything besides clinic info and contact for other funds we work with?

**Comment by NerdyGirl537** [comment]
The CM guide is in Crypto.  I don't reference it often anymore, but I think
it's a critical tool for the new CMs.

**Comment by lwaldsc** [comment]
Numbers to NAF and other East Coast funds (as well as our own #) would be
very useful to have as well. Maybe the sheet with contacts to other support
nonprofits in the DMV (homeless shelters, dv assistance, etc)?

**Comment by colinxfleming** [comment]
So the action items here are: 

* Get the CM guide, clinic info, other fund contact info, and other support nonprofit documents out of crypto
* and into a private but accessible-from-within-the-system place TK
* Once we've done that, create a UX ticket to make them discoverable

@lwaldsc step one is pulling these down. Can you assemble and email to me?

**Comment by colinxfleming** [comment]
( @lwaldsc did this. So the rest of this is on me to figure out where to put them, and then on ux to make it discoverable.) 

Unmarking question.

**Comment by colinxfleming** [comment]
Given the following:
* we need to account for N of these, where N is more than one but less than, like, ten
* they're going to vary from fund to fund
* we don't want to check them into version control
* we don't want to be the people who have to update them when there are changes
* they're sensitive but not Capital-P-Private (the stuff in this thread is, like, our CM training playbooks plus services info)

I think that, as with so much other stuff, the answer might be Google Driving these, and then we can link to them remotely. (I think having them available in a separate tab gets us the bulk of the way here, and the return to effort ratio goes way down after that).

Here's my proposal for how to solve:

* we ask team CM to create a google drive folder with shared resources (this might have already been done by Lisa), and make it accessible to people with the link
* we take a link to that directory and save it as an env var, called something like `FUND_RESOURCES_URL` defaulting to, like, google.com or something
* we throw a link to it in the navbar

Interested in @lwaldsc @vtmeghan @NerdyGirl537 's thoughts on whether or not this is a viable path.

**Comment by lwaldsc** [comment]
I don't think this is an *ideal* answer, but it's by far the easiest,
quickest, and most adaptable for other funds' use.

**Comment by colinxfleming** [comment]
I think the dev task here is to work with a DCAF stakeholder on porting these documents over to an accessible and reasonably secure place in google drive, and then adding the link up top. Probably this gets us 95% of the way there and that last 5% involves more design/frontend coding than it's worth.

**Comment by colinxfleming** [comment]
( @lwaldsc and @vtmeghan please weigh in if there's sensitive information you feel we should NOT be putting in google drive in there.)

**Comment by lwaldsc** [comment]
The only thing I can think of currently in Crypto that is sensitive is the
pledge tracker, but once the budget bar and audit systems are in place,
that should take care of the need for one.

I would say, we should envision something that will take its place so to
speak (an automated list of everyone that was marked 'pledged' this week so
CMs can check if a pledge was actually made if a clinic calls to confirm a
missing pledge).

**Comment by NerdyGirl537** [comment]
I had a thought, about putting a link to the Google docs in DARIA. What do
y'all think?
