### ISSUE TITLE
REPORTING: Build basic report view

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#659]
Team UX has whipped up a draft design, and @itsWill set up a reports controller, so it's time to put it to work! 

![dcafwireframe091316_data center](https://cloud.githubusercontent.com/assets/6223901/18497755/21fcaa76-79ff-11e6-917a-a57bc1ef6d6b.png)

Build this out in `app/views/reports/index.html.erb`. Don't worry about populating with actual data for now -- just write down 'TK' or hardcore a fake number.

Sourced from #634

**Comment by itsWill** [comment]
I can take a stab at this!

**Comment by bristolkr** [comment]
Hi, I'd like to claim this. If I'm understanding the issue correctly, you just want the index to look like the UX mockup, with actual functionality to be added at a later date?

**Comment by colinxfleming** [comment]
@bristolkr that's exactly right -- we're trying to just build out a recreation of the UX mockup for now, so we can then have people working on the components independently. Still, a pretty crucial first step! Thanks a ton for digging us up, and let me know if you have any questions or if I can unstick you on anything!

**Comment by colinxfleming** [comment]
@bristolkr please let me know if you've made progress on this, otherwise we're going to introduce it back into the pool tomorrow at the team meeting. Thanks much!

**Comment by colinxfleming** [comment]
@ashlynnpai can you take on this one?

**Comment by colinxfleming** [comment]
This is back in the pool!

**Comment by ashlynnpai** [comment]
I'll do this.

**Comment by ashlynnpai** [comment]
https://github.com/colinxfleming/dcaf_case_management/pull/882
