### ISSUE TITLE
Create call list clearing rules for between shifts

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#666]
From a conversation between @mebates and [the CM directors](https://github.com/colinxfleming/dcaf_case_management/issues/118#issuecomment-246886012): 

> So what came up tonight was the many patients who are 'dormant' for days, weeks, or forever. We don't want to encourage CMs to keep calling PTs who don't give DCAF a call back, and leaving them on the list for the whole shift might do that. And what if you come back a month later and they're still there? Or 9 months?

@NerdyGirl537 seconded this.

Two things here: 
a) finding some way to discourage people from calling patients over and over again when they don't hear back. There may or may not be a programmatic way to do this -- I suspect that the solution here is training.

b) starting with a fresh call list when you hop on a fresh shift. This I think is doable -- as part of the cleanup task, clear users' call lists entirely if they haven't logged in for two weeks or so. I don't imagine there are that many cases where people take multiple shifts like that. 

@NerdyGirl537 thoughts? 

Spun out from #118 .

**Comment by lwaldsc** [comment]
I think clearing the call lists after a shift (while leaving the option to
mark pts as urgent if they need to retain them in the list) will
effectively take care of this. And don't urgent marks expire after 4 days?

**Comment by colinxfleming** [comment]
Yeah, urgents patients are de-flagged after a couple of days of no action.

The task here is to add something to the `User#clear_call_list` method that will completely wipe a user's call list if `User#last_sign_in_at` was over two weeks ago. This, in turn, will cascade up to the rake task that we run nightly. (And to add a test for the method you write that does this, if you can!)

Marking backend/hacktoberfest.
