### ISSUE TITLE
Adjust spacing in call log between header and new call

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#667]
In #610 @mebates requested more user-friendly spacing between the header and the ability to create a new call on the patient edit page. Since this is a pretty straightforward template fix in the view, let's make it happen!

The view is in: `app/views/patients/_call_log.html.erb`. Should be straightforward to do using the tools provided by bootstrap. Requested changes are as follows: 

> Can we make some adjustments to the "record new call" function on the Call Log? I would prefer that it separate from the words "Call Log", potentially by aligning to the right side of the table. We can also just use a standard link style (17 px) and skip the icon since it seems to be a bit problematic with the size.

Bonus if we can make this happen with HTML / bootstrap classes, and not with custom CSS.

**Comment by colinxfleming** [comment]
<img width="983" alt="screen shot 2016-12-15 at 6 02 11 pm" src="https://cloud.githubusercontent.com/assets/3866868/21245481/a4700e8c-c2f0-11e6-9d42-9c97aa22bebc.png">

Screenshot to clarify!

**Comment by AlexandraCasser** [comment]
@colinxfleming Is this still relevant?

**Comment by colinxfleming** [comment]
@AlexandraCasser yep, this is still live! Should be pretty straightforward but I'd very much appreciate your time and energy on this regardless.

You should feel free to join our [slack](http://codefordc.org/joinslack) too if you're so inclined! We're #dcaf_case_manager in there. 

How'd you find us, if ou

**Comment by AlexandraCasser** [comment]
@colinxfleming so sorry I never got back to you.  I found you via Code for DC...and now I have the time to actually contribute!  Hopefully you'll see a few PR's from me over the next few days.  Please bear with me--I'm new to the open source world and haven't done any Ruby coding in ages.

**Comment by AlexandraCasser** [comment]
See: PR #810
