### ISSUE TITLE
Edit voicemail display text for Voicemail OK

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#674]
Change from `Voicemail OK` to `Voicemail OK, ID OK`. Trivial change -- code is located in `dashboards_helper`. Likely involves a test change too. 

Stems from some user feedback in #614.

**Comment by valeriecodes** [comment]
I'll take this.

**Comment by colinxfleming** [comment]
hey @valeriecodes ! Good to see you, hope you've been well. 

@itsWill kindly knocked this out yesterday, so I think we're good on this front. Any chance I could direct you toward #448 if you're looking for a quick-ish one?

**Comment by valeriecodes** [comment]
Sounds good, thanks @colinxfleming !
