### ISSUE TITLE
Patient status in cases of appt date left in voicemails

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#676]
CM Joy and @lwaldsc flagged a scenario where a PT will give an apt date in the voicemail, but we may not actually contact the PT. If the CM fills in the appointment date, the PT's status will be fundraising, regardless if we have ever talked to them. It is rare of enough an occasion, we may not have to do anything, but just want to flag that.

Should we adjust the behavior of status to account for this? 

cc @NerdyGirl537

**Comment by vtmeghan** [comment]
@lwaldsc and I discussed and we think that although this is a somewhat rare scenario, it would be useful to change the behavior of the status, so that the status remains "No Contact Made" for these patients. @NerdyGirl537 @colinxfleming @mebates

**Comment by vtmeghan** [comment]
Prioritize for sprint 11

**Comment by zorkian** [comment]
I'm looking at this one.
