### ISSUE TITLE
Update user manual on how to handle patients with more than one alt phone

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#677]
TODO for me: write the use case and detail plan of attack from dev side

**Comment by mebates** [comment]
We should just use the notes section for this.

**Comment by colinxfleming** [comment]
Potential rub is that only the first two phones are searchable, so that's a potential pain point, I agree with you. Just want to make sure we have this decision documented for when someone asks us for it again.

@lwaldsc @NerdyGirl537 @vtmeghan can you weigh in on how often we get patients with 3+ phones and how problematic it is to just keep the top 2 of them?

**Comment by NerdyGirl537** [comment]
Honestly, I've never had a patient with more than 2 phone numbers.  Definitely need 2 numbers, That happens a lot.  I think we can make it a training issue: suggest putting the line that will show up in the voice mail as the main number for searches; remind CMs to search on name if the phone number can't be found.  I'm for simplicity and have a concern with trying to cover every, single situation becoming unwieldy and limiting functionality in other ways. Just my 2¢.

**Comment by colinxfleming** [comment]
Agree with @NerdyGirl537 . @lwaldsc can you weigh in, and if you agree, make any appropriate edits to the user manual about best practices when logging multiple phones?

**Comment by lwaldsc** [comment]
Swore I already answered this. Agree 100% with @nerdygirl537. I'd
personally love more than two searchable numbers but I also don't want to
make the dash too busy so we're good with two.

**Comment by colinxfleming** [comment]
Sounds like we're in agreement -- @lwaldsc will you make an edit to the user manual detailing this behavior and close?

**Comment by lwaldsc** [comment]
Updated and closing.
