### ISSUE TITLE
How to flag people who we're playing phone tag with?

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#678]
Is there a way we can highlight these cases? What should behavior surrounding this be? 

Will work out whether this is worth implementing and how. 

Stems from #593

**Comment by vtmeghan** [comment]
@lwaldsc and I discussed and don't think this is necessary (largely because PTs automatically get added back to the call list if we don't reach them.) @NerdyGirl537 @colinxfleming @mebates

**Comment by colinxfleming** [comment]
Closing as a wontfix.
