### ISSUE TITLE
Add 'Other (add to notes)' option to patient insurance

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#680]
Nice and easy -- add an option in the `insurance_options` method in `patients_helper` that makes 'Other (add to notes)' and option. This will let us do a better job of handling unusual cases among the patients we serve.

**Comment by valeriecodes** [comment]
@colinxfleming is this issue still outstanding? Happy to pick up.

**Comment by colinxfleming** [comment]
yes pls!
