### ISSUE TITLE
Build scratch call line splash page

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#683]
[Here is a rough mockup of the user select screen.](https://cloud.githubusercontent.com/assets/17989540/18189002/c64c7ae0-7084-11e6-86ee-dec20293707e.png). The task here is to recreate this, except without the cancel button, per discussion in the UX thread #589.

Let's put this in a file in `app/views/dashboards/select_line.html.erb` for the time being, and add a get route for it. (And tests, if possible.) For now, just hard-code everything in HTML and skip any actual functionality. No need to have it actually do anything yet. 

This is fairly straightforward, so tagging hacktoberfest.

**Comment by lomky** [comment]
I'll take a stab at this tonight.

**Comment by lomky** [comment]
Rough version done and submitted!
