### ISSUE TITLE
ACCOUNTING: Build simple accountant dashboard view

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#685]
(Not tagging hacktoberfest until this is done, since it's probably best to have a designer in the same room!)

Let's start building out the accountants draft designs, so that we can iterate on them and add functionality piece by piece. 

The designs @eheintzelman built are here: 

![accountant input sketch](https://cloud.githubusercontent.com/assets/17989540/19152106/62f7311c-8b9e-11e6-8086-9abaedcac839.JPG)

In particular, we're interested in what's in the top half -- the search cases and search results in the `accountants/index` view, and a partial with the modal content in it. 

**Don't get hung up on the functionality of this -- for now, just hard code it all. No need to worry about wiring the modal up to anything at this point, either.**

Depends on #684 being completed. Stems from #643

**Comment by JoshNezi** [comment]
Attempting this one.

**Comment by mebates** [comment]
@JoshNezi - This is definitely not done, design wise. Please let @eheintzelman and me know what you're up to and maybe give us a peek before you get too far!

**Comment by eheintzelman** [comment]
@JoshNezi In particular, we are moving away from the modal for entering data...

**Comment by JoshNezi** [comment]
@mebates @eheintzelman yeah.....I have a few questions about this.

**Comment by eheintzelman** [comment]
@mebates @colinxfleming Since the current plan is to do away with the modal, how about we limit this for now to searching by Patient ID or Name and seeing search results. This is modeled after the search function for CMs to build a call list.  

Key difference - Accountant wants to search by unique Patient ID (M3-2349).  Colin, can you confirm this is possible based on what is in the system now? 

![accountant simple search](https://cloud.githubusercontent.com/assets/17989540/19602993/74344f38-977d-11e6-9d14-b0d3076da6eb.jpg)

**Comment by colinxfleming** [comment]
@eheintzelman Sure, we can adjust things so that we can search by patient id, no problem. It'll require a very slight backend change, but one I was thinking about making anyway.

**Comment by colinxfleming** [comment]
@JoshNezi sorry, sounds like I jumped the gun on this -- apologies!

**Comment by mebates** [comment]
Sounds like a good approach to me

**Comment by eheintzelman** [comment]
Here are digital versions.
![accountant simple search](https://cloud.githubusercontent.com/assets/17989540/19648298/9fe5885a-99cf-11e6-8cd6-eeb68187b58d.png)
![accountant simple search results](https://cloud.githubusercontent.com/assets/17989540/19648308/a78a0e0a-99cf-11e6-9141-e8f11149c776.png)

**Comment by JoshNezi** [comment]
@colinxfleming no worries.

**Comment by colinxfleming** [comment]
Let's plan on building this out according to the digital designs above. Please chuck it in `app/views/accountants/index.html.erb` (okay to create that folder and file if it doesn't exist yet). The important part for now is just coding up the template, so we can start bolting individual pieces onto it. Feel free to liberally copy code over from the dashboards index!

**Comment by mebates** [comment]
Could we remove the instructional stuff out of the search bar, and onto the page? As soon as you click into that, it goes away. Could just be simple helper text below the search box that says, "You can search by .... x, y, z."

**Comment by mebates** [comment]
One of the items on the search results should be a link, right? Name or case number? Let's style that as blue with an underline so the devs know it should be a link. Great work @eheintzelman!

**Comment by colinxfleming** [comment]
@DarthHater you should consider this open season -- iirc there's an accounting controller already made for you to start building off of. You might be able to consume some of the existing search partials. Go with @eheintzelman 's designs and ping her on slack if you've got any questions probably. 

( @JoshNezi let me know if you're still plugging away at this and I've missed it!)

**Comment by DarthHater** [comment]
Sure thing, I'll crack at it.
