### ISSUE TITLE
Implement Rate Throttling 

### ISSUE THREAD

**Issue by mccabe615** [colinxfleming/dcaf_case_management#699]
The following package can implement various forms of rate throttling and banning on various functions. This is something worth implementing on functions such as login and forgot password.

https://github.com/kickstarter/rack-attack

**Comment by colinxfleming** [comment]
We have this established in a limited way for login attempts thru devise, but I agree that there's a need to implement a general policy around it and that this is a good idea. 

From a skim of the docs I suspect that this is a pretty straightforward install -- marking hacktoberfest in case someone wants to take a stab. My inclination is to do this formally for login, forgot password, user create, and implement some of the best practices here: https://www.kickstarter.com/backing-and-hacking/rack-attack-protection-from-abusive-clients

Sound good to you @mccabe615 ?

**Comment by mccabe615** [comment]
Awesome. I'd like to take a crack at this but not sure if I have time immediately.

**Comment by colinxfleming** [comment]
This is a priority and I'd be stoked if someone knocked it out!

**Comment by lomky** [comment]
Taking a stab at this tonight.

**Comment by lomky** [comment]
@colinxfleming 

Here is what I've come up with from your input & the guides:

 - a standard throttle of `limit: 10, period: 10`
 - more severe throttle for these, maybe tighter restriction to `limit: 2, period: 2`?
    - `login`, `forgot password`, `user create`
  - maybe also restrict tries per email for these?
    - `login`, `forgot password` 

let me know your thoughts on the particular numbers and the email thought. 

Digging into the initial installation process now, hoping to get that PR in my end of hacknight.

**Comment by lomky** [comment]
Oh, I just noticed they offer a fully written basic configuration. I'm going to hack at that a bit before trying anything custom.

**Comment by lomky** [comment]
Initial functionality good-to-go. I'd like the weekend to get some tests in, but if you don't here from me by Monday feel free to merge.
Or merge if you make the call that it's good to go, but file me another ticket to write the tests please :D

**Comment by lomky** [comment]
[Testing rack::attack](http://blog.hayleyanderson.us/2015/06/05/using-and-testing-rack-attack-to-improve-the-security-of-your-rails-app/)
