### ISSUE TITLE
Make a clickable prototype in invision

### ISSUE THREAD

**Issue by mattbailey0** [colinxfleming/dcaf_case_management#7]
To support usability testing and design refinement, build a clickable prototype from current wireframes using Invision - http://www.invisionapp.com/

**Comment by mebates** [comment]
I'm getting started with InVision tonight. Users can join me by creating a login at http://www.invisionapp.com/. The link to our prototype is here (maybe): https://projects.invisionapp.com/d/main#/projects/5385941

**Comment by colinxfleming** [comment]
Should we close this and start creating separate issues for separate additions to InVision?

**Comment by colinxfleming** [comment]
Since this is now at the point of iteration and incremental changes, I think we can close this out.
