### ISSUE TITLE
Using remove call empties urgent call list partial

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#705]
Bug discovered by @tingaloo -- using remove call empties out the call list partial until reload. Clearly not expected behavior, proper behavior should be no effect on this partial. 

(NOTE: Resolved by code in #704 so no need to address separately)

**Comment by valeriecodes** [comment]
@colinxfleming should this be marked as closed/resolved?

**Comment by colinxfleming** [comment]
@valeriecodes you are right! This was resolved in #704 by @tingaloo . Thanks for flagging!
