### ISSUE TITLE
README addition: How to Run the Tests

### ISSUE THREAD

**Issue by lomky** [colinxfleming/dcaf_case_management#714]
The Fine Manual is missing how to run the test suite. 

If the circleci I snooped is any indication, it should be run like so:

### Whole Test Suite (long running)

`rake test`

### Individual Tests

`rake test test/path/to/test_file.rb`

And possibly other ways I do not know?

**Comment by mchelen** [comment]
That's probably correct, if you are basing it on circleci. Want to create a PR that adds this to the readme?

**Comment by lomky** [comment]
I would just need to know whereabout to place it.

**Comment by lomky** [comment]
Done with a best guess. Can always edit in the PR!
