### ISSUE TITLE
ACCOUNTANT: Add Fulfillment section to Patient edit view

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#731]
This is a good opportunity to get a feel for how we have the patient view arranged. Here are the designs from @eheintzelman : https://cloud.githubusercontent.com/assets/17989540/19648468/5031e410-99d0-11e6-9331-76cac8a8ca50.png

For now, just recreate the panel on the right in the patients edit view. Most likely the steps here are as follows:
* Add a 'Fulfillment' section to `views/patients/edit.html.erb`, and `views/patients/_menu.html.erb` -- follow the standard
* Create a fulfillment partial; toss the skeleton of a form in it. Doesn't have to do anything yet, just stub it! (Remember that we use the rails bootstrap forms gem - feel free to liberally crib from other forms.)

Stems from #643

**Comment by eheintzelman** [comment]
I got some feedback from the accountant making the design even simpler.  Here's an update. 

![pledge fulfillment v3 - landing](https://cloud.githubusercontent.com/assets/17989540/20367068/e9a5c99c-ac1b-11e6-89a4-61fe5a801e57.png)

**Comment by mebates** [comment]
Looks great! I wonder if we could prevent the 'Pledge Fulfillment' tab from appearing or being clickable until after the pledge is sent. Good or bad UX?

**Comment by colinxfleming** [comment]
Team dev can make that work either way, so whatever you think the good ux
solution is, haha. Either way we probably obscure it from regular CMs and
just show it to people with increased privileges, right?

**Comment by ashlynnpai** [comment]
I'll take a stab.

**Comment by eheintzelman** [comment]
Just talked to DCAF folks and yes it's fine to just obscure the pledge fulfillment from regular CMs, if that's easiest.

For the accountant/admin, I like Mollie's idea of only making the pledge fulfillment tab clickable once the pledge is sent.

**Comment by ashlynnpai** [comment]
Can you tell me where the higher level privileges are defined? I see only admin_user.

**Comment by colinxfleming** [comment]
I think `current_user.admin?` should work -- it should use the enum on the
user model, which is how we are giving people increased privilege. See some
of the users controller methods for an example of how we've been doing
this. (Sorry I can't be more specific, I'm on my phone!)

**Comment by ashlynnpai** [comment]
Thanks, I didn't realize you were using admin for that.

**Comment by ashlynnpai** [comment]
Can't figure out why this integration test isn't recognizing test_helper methods ('NoMethodError: undefined method `log_in_as' for PledgeFulfillmentTest:Class').

https://github.com/ashlynnpai/dcaf_case_management/commit/e990c60def80e53c5e38fcb20c727e856abbd83e

**Comment by ashlynnpai** [comment]
https://github.com/colinxfleming/dcaf_case_management/pull/741

**Comment by colinxfleming** [comment]
Taken care of by @ashlynnpai , just forgot to close! Closing out.
