### ISSUE TITLE
ACCOUNTING: Add fulfillment object

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#732]
We need to be able to mark a pledge as paid out administratively, so we'll want to do that with a fulfillment object. For MVP, let's do that as follows:

* Add a `Fulfillment` object; a Patient should have one fulfillment object
* Create it on initialization of a new patient object, at the same time as a new pregnancy object
* Add fields based on the last panel of https://cloud.githubusercontent.com/assets/17989540/19648468/5031e410-99d0-11e6-9331-76cac8a8ca50.png

This is a nice opportunity to wire up a mongo model from scratch!

Stems from #643

**Comment by lomky** [comment]
I'll take a stab at this.

**Comment by colinxfleming** [comment]
Slight iteration from @eheintzelman -- 

![pledge fulfillment v3 - landing](https://cloud.githubusercontent.com/assets/17989540/20367068/e9a5c99c-ac1b-11e6-89a4-61fe5a801e57.png)
