### ISSUE TITLE
PLEDGE VALIDATION: Add errors to view

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#733]
Known national treasure @ashlynnpai wrote up some validations which require

On the patient edit view load (or modal load or whatever), let's do the following:

* See what would happen if we did try and save a pledge (without actually saving it)
* If any errors come back, render them in the modal in `app/views/patients/_pledge.html.erb`

This will give our CMs a nudge in the right direction, keep our data quality high, and implement a notable quality of life improvement. 

This is the last big piece of #203 (besides testing), then we're in!

**Comment by valeriecodes** [comment]
I'll take a stab at this!

**Comment by valeriecodes** [comment]
It looks like the modals aren't currently using the pledge models or controllers. Should they be? If not, how should we check for errors?

**Comment by colinxfleming** [comment]
Nah, keep it using the patients update endpoint like it is in the form.

As for method, I'm not sure if there is a Rails accepted way to do
something like 'try to validate under these conditions' - if so let's use
that, otherwise can just add some conditionals to the view, probably? What
do you think?

I'll make sure to depreciate the unused stuff this wknd. You're right to
flag this as it makes getting the lay of the land much harder. Sorry about
that!
