### ISSUE TITLE
Create a presentation poster!

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#743]
@NerdyGirl537 was talking about presenting our work at a conference -- this is probably something that would benefit from UX eyes. (I think there was a conversation about this at the last hacknight, but wanted to make sure it was represented in the issues!)

**Comment by colinxfleming** [comment]
Here's a link to the session deetz:

http://take-root.org/submit-a-proposal/

Proposals for the 2017 Take Root: Red State Perspectives on Reproductive Justice Conference should

address how presenters will connect to reproductive rights and justice in red states
include concrete take-aways and/or action items
be specific in their focus and what they uniquely contribute to Take Root
be engaging and dynamic
Proposals may also describe how the presenters became and are currently involved with the issues discussed. Your intended presentation should strive to be accessible to a diverse audience of both emerging leaders and long-time activists. Biographical and contact information are required for all presenters. Please be sure to fill out all of the required information, as incomplete proposals will not be considered.

You can see what information is required for the proposals here.

Poster session proposal: Poster proposals indicate the individual or group whose work is organized in a visual format suitable for the poster session. The presenters are expected to be in attendance to discuss their projects for the duration of the poster session. Please indicate the top two related themes that correlate to your intended presented work.

Poster session proposals are due by December 9, 2016 at 11:59 CST. The Take Root Steering Committee will review all the poster session proposals AFTER the December 9th deadline.

http://take-root.org/wp-content/uploads/2015/07/Photo-Mar-26-7-21-31-PM-1024x683.jpg

**Comment by lwaldsc** [comment]
Great. Meghan and I started the CM UX survey tonight for some
numbers/feedback on the system. Can start a googledoc to organize sections
and start writing some copy.

**Comment by mebates** [comment]
"Using Tech to Remove Economic Barriers to Abortion Care"

- Feature Journey Map, images of the system, system benefits table

*Goals:*
- Discuss opportunities in tech for repro-justice activists 
- Inform activists doing similar work that DARIA exists
- Connect with funds that may find this useful

*Main ideas:*
- The problem
- The solution/What we did: describe product
- How we did it: Partner with other organizations (probono tech help) - find your local code for america brigade, use open source to allow many ppl to contribute, meet tech folks where they are (be open to using their tools, processes), user centered (surveys, interviews, usability test, regular Involvements from CMs (product team)), Discovered/mapped process, Added structure to a volunteer project, Built a diverse team. Cooperative/collaborative effort -not asking for a solution, working together to develop it. Security

**Comment by colinxfleming** [comment]
This is approved, and we need to have it to them by the 17th of Feb so they can print. Max size 24" x 36". Awesome job @NerdyGirl537 for getting this thru!

**Comment by lwaldsc** [comment]
Do we have any idea of word count on each of these sections?

**Comment by NerdyGirl537** [comment]
It's going to be a design thing based on text size and aesthetics and what
we want to say.

**Comment by mebates** [comment]
I made a thing! Please let me know how it looks to you. Text needs:
- 50 words on the Problem
- 50 words on the Solution (if you do less for problem, you can have more for solution)
- 30 word "How we did it" blurbs. 5-7. If we can keep it down to 5 we can keep the journey image in and big.

Go team!
[DCAF_TapRoot_Poster.pdf](https://github.com/colinxfleming/dcaf_case_management/files/762395/DCAF_TapRoot_Poster.pdf)

**Comment by NerdyGirl537** [comment]
Looks awesome so far!

**Comment by lwaldsc** [comment]
Just chiming in to say THIS LOOKS INCREDIBLE! Great job, Mollie!

**Comment by NerdyGirl537** [comment]
63 words for Problem:
Abortion funds are more in demand than ever while the anti-abortion crowd has been stepping up internet attacks. Add in the privacy concerns of handling medical information, and you have a lot of challenges for those helping people with access to abortion care. And our tools have not kept up with these challenges– secure websites can be cost-prohibitive, taking funding from direct support.

**Comment by NerdyGirl537** [comment]
67 words for Solution:
The DC Abortion Fund built a partnership with Code for DC to build such a tool. After more than a year of collaboration, the low-cost app was launched for the entire fund in December, greatly improving DCAF’s efforts to center patients, improve services, and provide a secure and usable internal system. In addition, it’s engineered to be shared with other funds, or repurposed by other RJ organizations.

**Comment by NerdyGirl537** [comment]
Thoughts on "How We Did It" section: ( @colinxfleming, could use a coder's perspective here too)
- End-user involvement from the beginning
- Collaboration with pro-bono tech
- Discovery process that included all level of users (i.e. Board, CMDs, CMs)
- Sprints and planning
- Use of industry best-practices.

**Comment by colinxfleming** [comment]
@NerdyGirl537 I think the really cool stuff about this project are the first two bullets, and that these are the really exciting parts of them:

* Having our case managers and fund staff build out the workflow based on their experiences
* Collaborating with engineering and design teams outside the usual repro justice sphere

I'm less sure that people will be stoked on these but maybe:
* Going heavy on security
* Completely open source and available for general use

**Comment by colinxfleming** [comment]
Some proposed revisions for problem and solution -- @NerdyGirl537 feel free to adapt whatever you like from these.

### PROBLEM
> Abortion funds are meeting a higher demand than ever before in the most hostile climate in years. Our tools of binders and spreadsheets have not kept up with these challenges -- our intake can overflow, security can be cost prohibitive, and we can't always afford redirect our resources toward these problems without an impact to our direct support.

### DOG SOLUTION
> Volunteers at both the DC Abortion Fund and Code for DC partnered to build a modern system that reduces the stress of intake, securely records sensitive data, and is very affordable. After more than a year of development, the low-cost app was launched in December, and we've already seen improvements in how we center and serve patients. In addition, it's engineered to be shared with other funds, or repurposed by other RJ organizations.

Since we now have @lwaldsc  and Michela's excellent survey, we might also consider dropping some of the feedback from that in here somewhere? Don't want to be the extra cook in the kitchen though, so I defer to the team here on that.

**Comment by NerdyGirl537** [comment]
@colinxfleming  I'm liking all of this.  

@lwaldsc @mebates Other thoughts?

**Comment by lwaldsc** [comment]
Love the blurbs. Think they work great at describing the problem and the
solution in limited space.

Not sure what we want to pull out of the survey. Do we think the "[X
Feature] made it easier for me to [X Direct Service Thing]." numbers would
be an interesting add here?

**Comment by NerdyGirl537** [comment]
I did an update of the poster based on previous comments.  It seems though my version of Adobe doesn't support the lovely font.  @mebates Can you help with that?  

[DCAF_TakeRoot_Poster.pdf](https://github.com/colinxfleming/dcaf_case_management/files/777402/DCAF_TakeRoot_Poster.pdf)

**Comment by mebates** [comment]
"we’ve already seen improvements in how we center and serve patients". What does 'center' mean?

@colinxfleming - can you fill in a line or two explaining how we did security?

I followed the convo above and filled in with some extra copy. Latest:
[DCAF_TapRoot_Poster.pdf](https://github.com/colinxfleming/dcaf_case_management/files/777493/DCAF_TapRoot_Poster.pdf)

**Comment by colinxfleming** [comment]
Some security boilerplate:

> To ensure the safety of our patient data, we take advantage of other services' powerful security where possible, rigorously review and test all our code, and actively monitor every part of the application for vulnerabilities.

**Comment by mebates** [comment]
Latest:
[DCAF_TapRoot_Poster.pdf](https://github.com/colinxfleming/dcaf_case_management/files/777610/DCAF_TapRoot_Poster.pdf)

**Comment by lwaldsc** [comment]
Oh my god @mebates this looks incredible! Great job, everyone.

I'm not sure if we still want to fit anything from the survey in, but at
this point, it might make everything a little too squished? If so, we can
pull some stuff out, but if not, it's still great data we can use on the UX
side.

**Comment by NerdyGirl537** [comment]
I love it. I'm gonna send this morning.

**Comment by mebates** [comment]
@NerdyGirl537 hold on! I'm checking the resolution of the images with a test print.

**Comment by mebates** [comment]
@NerdyGirl537 it should be good. send away!

**Comment by colinxfleming** [comment]
This is a beaut. Awesome work @mebates and @NerdyGirl537 ! 

@NerdyGirl537 go ahead and close this issue when you've shipped it to our friends at TakeRoot!

**Comment by NerdyGirl537** [comment]
Shipped to Take Root!  Thanks everybody for all the amazing work!
