### ISSUE TITLE
MULTIPLEDGE: Frontend changes to accept multiple pledges from other funds

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#747]
Since the MD and VA lines require a lot of collaborative work with other funds, we need to have some clean notion of that represented easily. The scope of this issue is rigging up those changes in the patient edit view. 

![img_0463](https://cloud.githubusercontent.com/assets/6223901/19990799/e47216b6-a206-11e6-8080-3fdb1788435f.JPG)

Which follows the following list of changes:
1) move 'Resolved w/out..." to the right of Clinic details
2) Move 'Cost details' below
3) Abortion cost on left column
4) Right column: PT contribution, then DCAF, then NAF, then "+ Add other". (The first 3 should be from the Pregnancy object; the others will be pledge objects).
5) Add other chunk to include "Other", a dropdown, and money input box
6) Dropdown values = Baltimore Abortion Fund, Richmond Reproductive Freedom Project, Blue Ridge Abortion Assistance Fund, Tiller Fund (NNAF), Carolina Abortion Fund, Women's Medical Fund (Philadelphia), NYAAF (New York), Other
7) User is able to "add other" repeatedly

These also require some model changes I'm personally working on in a separate thread. For now, I think the really important things are making the stylistic changes and getting the 'Add Other' to work. 

Stems from #746

**Comment by itsWill** [comment]
I'll take a stab at this one

**Comment by colinxfleming** [comment]
Good to see you again, @itsWill !

We're in our final push and are flipping a switch on Sunday 12/4, can you be sure to make a pull request by Thursday? Something that's a work in progress is totally fine -- just want to make sure we don't lose any of your hard work! 

Thanks my dude!
