### ISSUE TITLE
Alternate contact not populating in call pop up

### ISSUE THREAD

**Issue by lwaldsc** [colinxfleming/dcaf_case_management#758]
Using the system tonight, alternate contacts were not populating in the call screen pop up. These were contacts with no alternate number.

**Comment by colinxfleming** [comment]
Code here is in `calls_helper` and `views/calls/_new_call.html.erb` -- probably this is just a matter of a helper only rendering stuff if alt name and alt number are set. Sounds like the desired behavior is for presence of either one to make alt info show up in the call partial.

**Comment by colinxfleming** [comment]
In bug report-ese, here's what this comes out to:
* Given that I have a patient who has a secondary contact name but not a secondary contact number,
* I expect that when I open a new call modal, I will see the secondary contact name;
* Instead, I don't see the secondary contact name.

Pretty small fix but Monday will be the first exposure most of our users have to this system, so if we can get this resolved by Sunday afternoon it would be clutch.

@valeriecodes if you've got capacity can you take a look at this? @lwaldsc can you keep an eye on this thread and help @valeriecodes out in case she needs help whipping up an example case?

**Comment by lwaldsc** [comment]
Gotcha. Sounds good!

**Comment by valeriecodes** [comment]
👍  Thanks @colinxfleming and @lwaldsc
