### ISSUE TITLE
Fix formatting error in patient edit page abortion information partial

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#765]
The extra pledges are a little off-grid -- we should do our best to match them with the section above. 

![screen shot 2016-12-03 at 5 06 41 am](https://cloud.githubusercontent.com/assets/3866868/20858600/61f6c642-b916-11e6-80c1-c40fa4b591ba.png)

**Comment by valeriecodes** [comment]
Taking a look at this.

**Comment by mebates** [comment]
👏
