### ISSUE TITLE
Migrate from Unicorn webserver to Puma

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#769]
It is time to do this. Memory usage with unicorn is getting a little out of hand.

**Comment by colinxfleming** [comment]
We're deployed on heroku, and here's their documentation on deploying with puma: 

https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server

Moving to active development, since I think we should make this a priority.

**Comment by DarthHater** [comment]
I can take this if need be.
