### ISSUE TITLE
Write tests for data entry functionality

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#771]
This is a good opportunity to learn some minitest, the ruby library we use for writing tests!

* **What are we trying to do?** QA our data entry form, `/data_entry`!

* **What feature or behavior is this required for?** We wrote a data entry function in a hurry for deployment; we want to have it tested so that we don't accidentally break it in a future small release. 

* **How should we solve this issue?**

We should write the following: 
* A controller test in patients that confirms that the methods `data_entry` works, and that `data_entry_create` works with both the success and failure conditions
* A new Capybara integration test that i) fills out the form successfully and confirms that the fields show up on the patient edit page it dumps you on; and ii) fills out the form unsuccessfully and confirms that any errors are on the page.

**Comment by vincecampanale** [comment]
I'd be happy to take this one!

**Comment by colinxfleming** [comment]
hey @vincecampanale , that would rule! Let me know if I can assist with anything as you dig in.

**Comment by vincecampanale** [comment]
Hey @colinxfleming happy to help! I'm running into some setup issues. The command `rake db:seed` is returning this error: 

```
$ rake db:seed
rake aborted!
NoMethodError: undefined method `ruby_dirs=' for #<Quality::Config:0x007ff28311d050>
Did you mean?  ruby_files
/Users/vincecampanale/dev-stuff/open-source/dcaf_case_management/lib/tasks/quality.rake:8:in `block in <top (required)>'
/Users/vincecampanale/.rvm/gems/ruby-2.3.1/gems/quality-27.3.0/lib/quality/rake/task.rb:57:in `initialize'
/Users/vincecampanale/dev-stuff/open-source/dcaf_case_management/lib/tasks/quality.rake:3:in `new'
/Users/vincecampanale/dev-stuff/open-source/dcaf_case_management/lib/tasks/quality.rake:3:in `<top (required)>'
/Users/vincecampanale/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/Users/vincecampanale/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/Users/vincecampanale/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/vincecampanale/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/Users/vincecampanale/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/Users/vincecampanale/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `each'
/Users/vincecampanale/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `run_tasks_blocks'
/Users/vincecampanale/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/application.rb:452:in `run_tasks_blocks'
/Users/vincecampanale/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/engine.rb:453:in `load_tasks'
/Users/vincecampanale/dev-stuff/open-source/dcaf_case_management/Rakefile:4:in `<top (required)>'
/Users/vincecampanale/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/vincecampanale/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/vincecampanale/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by colinxfleming** [comment]
hey @vincecampanale , it looks like a gem we were using depreciated something and you're the first person to get bitten, sorry!

Go ahead and comment out the code in `lib/tasks/quality.rake` and that should fix.

**Comment by vincecampanale** [comment]
@colinxfleming Okay, I think everything is ready to go. This is the output of `rake test` - is it expected? 

<img width="1277" alt="screen shot 2017-01-24 at 9 55 43 am" src="https://cloud.githubusercontent.com/assets/15335197/22252157/4c98571a-e21b-11e6-8e8a-4247be77f80e.png">

**Comment by colinxfleming** [comment]
@vincecampanale given the scope of this issue those are almost definitely false flags. I'd start up a pull request for what you did and see if it passes the CI test.

**Comment by vincecampanale** [comment]
@colinxfleming I just meant that I was done with setup - I'll get on writing the tests now! I haven't done this before, so it may take a while but I hopefully I can get it done in a couple of hours.

**Comment by colinxfleming** [comment]
Oh word! Yeah, go ahead and dig in without fretting about those. There are
some similar tests you can adapt for some ideas.
