### ISSUE TITLE
Figure Out Why Line:XY Turns White After Click

### ISSUE THREAD

**Issue by kscoulter** [colinxfleming/dcaf_case_management#783]
![linegoeswhite](https://cloud.githubusercontent.com/assets/12025195/21247114/174a8144-c2fb-11e6-8951-4e089b80b2af.gif)

Guessing it has something to do with a :visited style.

**Comment by colinxfleming** [comment]
@kscoulter love the GIF here, super helpful. Also really appreciate your brainpower on this aspect of our app!

Seems like other links also have this , which suggests that we can apply a global css style. Do you have a suggestion for what color we should change it to (maybe a black, a darker purple, or another color entirely?)

cc team design @eheintzelman @mebates

**Comment by mebates** [comment]
How about Navy blue? Also would love to incorporate an underline on hover. Good catch, thanks!

**Comment by AlexandraCasser** [comment]
I'm going to give this one a go.

**Comment by AlexandraCasser** [comment]
I'm happy to do this, but want to get the details straight.  So we want both nav links and body links to be navy blue after visited and underline on hover?

**Comment by colinxfleming** [comment]
@AlexandraCasser yeah, go ahead and set that as the global style and we can scope it down from there if need be.
