### ISSUE TITLE
Improvements to notes section in patient edit view

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#795]
There are a few user feedback items pertaining to the notes partial as follows:

* Would be nice to be able to email a user from their notes -- e.g. if not system, link to a mailto of their email
* Notes metadata should not be styled as a table -- we can just have them next to each other in a header. Something like `User.name on YYYY-MM-DD TIMESTAMP` should work nicely.

Stems from #593

**Comment by AlexandraCasser** [comment]
@colinxfleming Is this how you'd like the metadata to look?
![localhost-3000-patients-587908345e0dd11a782fd603-edit](https://cloud.githubusercontent.com/assets/12383179/22081390/684c2024-dd91-11e6-8791-4fc0fb452e1e.png)

**Comment by mebates** [comment]
Hey @AlexandraCasser ! I would do the metadata like this:

Username    MM/DD/YYYY, 00:00 pm

**Comment by AlexandraCasser** [comment]
@mebates  duh, that's what you said before ;)  Thanks.  I'm happy to take this.  Where on the page should the email go?

**Comment by mebates** [comment]
You can make the username a mailto: link

**Comment by AlexandraCasser** [comment]
@mebates Is there an example of how to grab the user email on one of these pages?

**Comment by colinxfleming** [comment]
@AlexandraCasser looks like we don't have that currently implemented (it's just rendering name), so I'd say let's skip it. (Sorry for remixing directions!)

But if it ever comes up again, you can use rails' `mail_to` helper (similar to `link_to`)! http://apidock.com/rails/ActionView/Helpers/UrlHelper/mail_to

**Comment by AlexandraCasser** [comment]
@colinxfleming Thanks, I thought that was the case but wanted to make sure I wasn't missing anything.

**Comment by colinxfleming** [comment]
Just for reference, I think in the interest of obscuring user emails I think we can skip the request to toss in mailto links unless we get more requests. I'm not sure it gets us anything new for the CMs now that we have individual names associated with calls and notes. 

e.g. the current implementation as @AlexandraCasser has it in #827 is good.
