### ISSUE TITLE
Breakout PP Clinic Name Info

### ISSUE THREAD

**Issue by NerdyGirl537** [colinxfleming/dcaf_case_management#818]
We need to breakout the clinic name drop downs for all the Planned Parenthood clinics so that each clinic is represented individually.

This will be a critical part of the pledge process, especially when auto-generating the pledge forms.

Update the file where the clinic names are stored.

**Comment by colinxfleming** [comment]
Since we have basic clinic modeling in place, I just asked the CMDs to rack this by next Friday. Hopefully we'll be able to close this out soon (let's not close it out until we have clinics in prod, and until there's a link in the top navbar for CMDs).

**Comment by colinxfleming** [comment]
Resolved at long last in #975 . This is in the CMD's hands entirely now.
