### ISSUE TITLE
Remove "undocumented" from special circumstances

### ISSUE THREAD

**Issue by lwaldsc** [colinxfleming/dcaf_case_management#834]
Do not think we should be tracking this in a systematic way to protect our patients' data. Can be noted in the notes sections if needed. 

Thoughts @colinxfleming @NerdyGirl537 ???

**Comment by colinxfleming** [comment]
Documenting some offline conversation: This stemmed from a conv with Baltimore. We have two paths forward here, one of which is a global remove (pretty straightforward) and the other of which is figuring out some way to configure certain settings by deployment (more involved but not impossible).

No action on this until we resolve how to handle this DCAF side, which requires input from  @vtmeghan and other case management team brass.

Interested in @NerdyGirl537 's thoughts regardless.

**Comment by colinxfleming** [comment]
Consensus from the CM directors is that this is good to remove; marking frontend and throwing in active.

**Comment by colinxfleming** [comment]
Task here is to do the following:

Frontend change:
* Remove this from the frontend

Gold medal version:
* Write a rails console command that will remove Undocumented from existing patients' special circumstances
* Write a rails console command that will nuke any and all audit trails containing reference to undocumented status

**Comment by AlexandraCasser** [comment]
Can do the simple remove.
