### ISSUE TITLE
Resource guide

### ISSUE THREAD

**Issue by lwaldsc** [colinxfleming/dcaf_case_management#841]
***Currently our resource folder also includes the budget tracker and pledge form, so those features should be completed before we can migrate everything.

**Essential information we need**
Clinic contact information/price guide 
Other local funds' contact information and eligibility
Other social resources contact information (could be supported in a follow up program) 
LMP calculator (could be supported in another feature in DARIA) 
Suggestions for fundraising
Call script
How to fax document (could be included in the pledge box?)
Policies and procedures
Meghan's weekly email content (separated into "Basics" and "New Information")

**Where does it live? How do I get to it?** 
Pop-out new window/tab that houses a mini-wiki
Links in ? helper buttons near certain features to related page (Clinic details would link to the list of clinics; additional funding would link to the list of funds, etc)
Ideally, the New Information would be housed on the home page of the wiki as a reminder to CMs who didn't read the email.

**Wiki tabs**
Home
Basics
Clinics
Funds
Resources
LMP Calculator
Fundraising
Script
Hard Cases
Policies
History
(Using anchor links to go to specific information under each tab.) 

**How to keep it updated? What changes a lot, what doesn't? (Jekyll in github/CRM/links to PDF?)**
Girl I have no idea. Information does not change that often. Parts of Meghan's weekly email does, alerting CMs to any new information or changes and who is on the lines this week.

**Relationship to other DCAF resources**
Currently in googledrive/crypto but hoping to get rid of both

**Comment by mebates** [comment]
I see in #962 that we added this to the top nav. Since this opens a new tab outside of the app, I might consider adding it to the footer instead. Thoughts @lwaldsc ?

**Comment by colinxfleming** [comment]
ping @lwaldsc  -- if you think it's good at the top go ahead and hit close, otherwise let's figure out where it should live.

**Comment by colinxfleming** [comment]
Area Man Mashes Wrong Button

**Comment by lwaldsc** [comment]
Honestly I would leave it on the top so it's easier for CMs to find. I know you're the expert Mollie but I know there will be a bunch of "where is the link" kind of questions soooooooooo
