### ISSUE TITLE
Add DCAF and C4DC logos to the footer

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#842]
Now that we're starting to expand, we should brand a little bit! We have some footer space -- let's add a small code for dc logo and dcaf logo to the bottom of the footer partial. 

You can snag a code for DC logo from https://github.com/codefordc/branding-assets . 
You can snag a DCAF logo from http://dcabortionfund.org/ .

**Comment by KatSDC** [comment]
I'll take this one!

**Comment by colinxfleming** [comment]
I'll see if I can dig up dcaf assets, but here are code for dc's: https://github.com/codefordc/branding-assets

**Comment by KatSDC** [comment]
I found an SVG of the DCAF logo from their site. It's the square one, but I imagine when I complete this we can trade out the logo if need be.
