### ISSUE TITLE
User feedback from surveys and stakeholders meetings

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#846]
DCAF-side we've had a bunch of meetings, email chains, surveys, etc where we've collected user feedback. Much of it is already represented but I want to get it in one place (and out of my notebooks).  

### From the CM Stakeholders meeting

@NerdyGirl537 , @lwaldsc and I had a meeting with the CMD brass where a few requests popped up. Much of it was represented in other places / issues but I want to make sure we got it down explicitly. 

* Get docs accessible. There's a bunch of associated materials that CMs need to reference, such as scripts etc. It would be nice if these were accessible from within the app. This is represented in #839 
* Phonetic search. "It would be nice if the search were more flexible on spelling." It sure would be, but it's probably a significant engineering undertaking to make this happen. This is represented in #449 but if there's no gem or pre-rolled library solution I think we should close as a wontfix.
* My week's activity feed. Repped in #654 I think. CMs would like a running log of patients the line has had contact with over the week, so they don't lose anybody -- this is a trivial task in an excel doc but much more challenging in an obscured db. 
* limit patients returned. @NerdyGirl537 pointed out that there isn't a limit on patient returns, something she learned doing data entry QA. Probably more of a db optimization problem than a data security problem but we get gains in both areas from this. Repped in #845

**Comment by colinxfleming** [comment]
### From correspondence with CM JW

This is from an email awhile back (first week or so of production on the DC line, whoops). Below are items not resolved between then and now:

* Add an appointment date column to the dashboard to make it easy to arrange the call list by who will need their pledge soonest.
* Add an "urgent" toggle to the dashboard so that you can mark or unmark someone as urgent without needing to go all the way in to the patient notes.
* Make the dashboard sortable by the column headers.
* Make a way to move someone from completed calls back to the call list.  I had a hard time getting a record back in my call list when I left a message for someone and then they called back.

**Comment by colinxfleming** [comment]
### From correspondence with CMD Travis

> I know I have mentioned this in passing before, but I think we should add a column where we can note if we referred the patient to a particular clinic. I have always thought that we could potentially use this information as leverage for approaching clinics to request clinic discounts. When we toured XXXXX their clinic administrator even said we should be leveraging relationships for discounts. I agree we should but feel our only leverage would be if we could say something like, 'We have referred (X) number of patients to you in the last 12 months who were all initially planning to go elsewhere/didn't know where to go.'

**Comment by lwaldsc** [comment]
Oh I really love the idea of tracking clinic referrals for leverage with
clinics. That's a great idea from Travis. Not sure how we integrate it into
the system, especially as many CMs (myself included) will refer to several
clinics, but it would be an interesting thing to track.

What a damn best problem to have, being able to leverage clinics instead of
being forced to send people to one a few hundred miles away because it's
the only one.

**Comment by colinxfleming** [comment]
Stuff to spin into issues: 

* design team: completed calls to main list, mark/unmark urgent without having to go to dash
* sort on headers in dashboard
* referred patient to clinic-ness

**Comment by colinxfleming** [comment]
Actionable stuff spun out into individual issues; closing.
