### ISSUE TITLE
Create Distinct Dev and CI Environment Test Settings

### ISSUE THREAD

**Issue by lomky** [colinxfleming/dcaf_case_management#849]
Since introducing Rack-Attack in #699, we have tests that are not very useful to run every time a developer wants to test but add value in our CI build. There are probably other tests that meet these criteria today?

 - important to test
 - not likely to fail unless their corresponding code is directly messed with
 - take a relatively long time to run

Downsides: 
 - a user may break something and not know until they do a PR
    - mitigated by only moving very narrow tests
 - :question: 

Resources: 
 - [Customizing Rake Tasks In Rails 4.1 And Higher](http://metaskills.net/2015/02/08/customizing-rake-tasks-in-rails-41-and-higher/)

We may decide this isn't worth doing due to minimal time saved (Rack-Attack's test suite is only 5 seconds) or just not worth doing yet.

**Comment by colinxfleming** [comment]
Per discussion in #851, let's revisit this if our test suite continues to balloon. Thanks much @lomky !
