### ISSUE TITLE
Add sortability to call list dashboard table

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#896]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Our case managers have asked for the ability to sort the patient dashboard by the column headers.

![image](https://cloud.githubusercontent.com/assets/3866868/23581317/652f06a6-00c6-11e7-8ea9-70ca773c2191.png)

* **What feature or behavior is this required for?**
Case managers often want to sort their call list or urgents list by appointment date, so they can prioritize their calls easier.

* **How could we solve this issue? (Not knowing is okay!)**
Probably a JS library, but this is something I don't know much about, so chef's choice!

* **Anything else?**
If there's an easy path to this then that's awesome, but we have this implemented in a limited way already with drag and drop. 

The file here that generates tables is located in `app/views/dashboards/_table_content.html.erb`.

**Comment by janinedog** [comment]
I'm going to take a look at this one.

**Comment by janinedog** [comment]
@colinxfleming Do you want a particular column sorted by default on page load?  Or no default?

**Comment by colinxfleming** [comment]
Closed via #927 and #924
