### ISSUE TITLE
Add way to mark down that we referred a patient to a clinic

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#897]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Keep track of who we referred to a particular clinic with a checkbox.

* **What feature or behavior is this required for?**
Our case management directors want to keep track of this so that they can negotiate discounts from clinics. We want to be able to say 'we said you were a good option, can we get a couple bucks off for this particular case?' Having a record of who we referred is the first step!

* **How could we solve this issue? (Not knowing is okay!)**
I think there's a good path to this: We can add a field to the pregnancy object (something like `referred_to_clinic`, a boolean attribute). We should then add it to the Abortion Information partial in `app/views/patients/_abortion_information.html.erb`.

* **Anything else?**
Not really!

**Comment by lilliealbert** [comment]
I am going to work on this!
