### ISSUE TITLE
Add nontechnical roles to readme

### ISSUE THREAD

**Issue by mattbailey0** [colinxfleming/dcaf_case_management#9]
Add project needs by skillset to the readme.  Don't forget about non-technical users such as designers, testers, and copywriters.

**Comment by mebates** [comment]
Covering the design needs in my latest pull request. @colinxfleming do you think the ReadMe properly describes the 'project needs' for developers?

**Comment by colinxfleming** [comment]
As we get closer to MVP I think we're going to spend more and more time testing and drafting directions. We've started to attract some nontechnical interest. My current thinking is to revisit in mid to late May and develop a testing plan/start a CM-led instructions manual team to write up things in the wiki.

**Comment by colinxfleming** [comment]
(Backlogging since we're not actively working on it.)

**Comment by colinxfleming** [comment]
Remixed to reflect readme changes in #356. Need to flesh out nontechnical help.
