### ISSUE TITLE
Questions / Notes from a newbie reading DCAF 101

### ISSUE THREAD

**Issue by lilliealbert** [colinxfleming/dcaf_case_management#900]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Make the [DCAF 101 doc](https://github.com/colinxfleming/dcaf_case_management/wiki/DCAF-101) easy to read for people with very little context!

* **What feature or behavior is this required for?**
Different words, probably!

* **How could we solve this issue? (Not knowing is okay!)**
Editing!

* **Anything else?**
Here's what I've got! For context, I was working on the app at the Abortion Access Hackathon in SF, and was reading through the 101 to get context on how the app works and what the words in the app mean.

## DCAF 101 Questions/Notes

* What is the call list? (People who need to be called by someone, people who need to be called by a specific case manager? The one who is logged in?)
* What is pledging / what's a pledge?
  * Defining pledges in section 3 (Calling the Patients) might be useful, esp in the context of "talk the patient through intake, fundraising, or pledging"
* We're missing a word (under "Calling the Patients"):
  * "including confirming they will <call?> DCAF back before a pledge can be made."
* In section 6 (Appointment), who is "they" in this sentence?
  * If the patient does not make their appointment for whatever reason, they will call DCAF back and a new pledge will be made.
  * Maybe this is clearly the patient, but I'm not sure why they need a new pledge at that point?

**Comment by colinxfleming** [comment]
cc @lwaldsc

**Comment by mebates** [comment]
Awesome feedback @lilliealbert !!!

**Comment by lwaldsc** [comment]
These are great questions @lilliealbert! Give me a sec to run through them!

**Comment by lwaldsc** [comment]
So first off, I apologize for the very little explanation. Most of the people who have worked on this project have some basic working knowledge of DCAF, so it's so great to get this kind of feedback from those who don't know our procedures! Will be adding these to the readme.

**- What is the call list? (People who need to be called by someone, people who need to be called by a specific case manager? The one who is logged in?)**
Yes! Our case managers work either a one week or a half week shift where they are in charge of one of three lines (DC, VA, or MD/Nationwide). A call list is a list of patients to be called back by a single case manager per day. This list is created by the case manager from voicemails left by patients.

**- What is pledging / what's a pledge?**
A pledge is any amount of money sent to a clinic for use by a patient. These pledges are capped depending on how far along in a pregnancy the patient is.

**- Defining pledges in section 3 (Calling the Patients) might be useful, esp in the context of "talk the patient through intake, fundraising, or pledging"**
Yes, this was specifically brief for brevity's sake, but can flesh these procedures out a little more if you feel like that would be helpful!

**- We're missing a word (under "Calling the Patients"):**
**- "including confirming they will <call?> DCAF back before a pledge can be made."**
Good spot!

**- In section 6 (Appointment), who is "they" in this sentence?**
"They" is the patient.

**- If the patient does not make their appointment for whatever reason, they will call DCAF back and a new pledge will be made.
- Maybe this is clearly the patient, but I'm not sure why they need a new pledge at that point?**
The pledges are date stamped for their appointment, so at the very minimum, the date on the pledge will need to be changed. Often, however, the price of the appointment will increase, and if possible, DCAF will also raise the pledge to help the patient bridge that gap.

**Comment by colinxfleming** [comment]
Yeah, I think this is one of the most valuable pieces of feedback from this
weekend.

Lisa, can you make edits to the dcaf 101 doc to clarify these points? No
rush since we're unlikely to be doing a mass onboarding again anytime soon,
haha.
