### ISSUE TITLE
Add ability to easily verify a clinic/pledge amount when entering fulfillments

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#905]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Easily verify that the patient has the correct clinic/amount set when we're doing pledge reconciliation/fulfillments.

* **What feature or behavior is this required for?**
QA during pledge fulfillments.

* **How could we solve this issue? (Not knowing is okay!)**
We should make this as simple and straightforward as possible -- let's just add `@patient.clinic_name` and `@patient.dcaf_soft_pledge` and some boilerplate text about 'Please confirm that the clinic and pledge amounts are correct' or something to that effect in the `app/views/patients/_fulfillment.html.erb` partial, underneath the header.

![image](https://cloud.githubusercontent.com/assets/3866868/23582905/622e065e-00ea-11e7-956e-acdcd86da74a.png)

**Comment by lilliealbert** [comment]
Doing this!
