### ISSUE TITLE
Change the order of fields in fulfillment 

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#907]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
When clinics send us remit forms, we enter in data from them, and that data is in a standard order. This order is different from what's on the form, and we should get them in agreement so data entry for our fulfillments team is easier.

* **What feature or behavior is this required for?**
Enter fulfillment info faster!

* **How could we solve this issue? (Not knowing is okay!)**
The info we enter appears in the following order: money, clinic, weeks at date of procedure, date completed. Let's just straight up move the form elements around. (No need to worry about check # or date of check.)

* **Anything else?**
Nope!

**Comment by zorkian** [comment]
Claiming, maybe! (Probably. Yes? Okay.)

**Comment by saragilford** [comment]
@cschlessinger and I have dibs!

**Comment by colinxfleming** [comment]
Fixed via #919
