### ISSUE TITLE
Submit pledge button still says 'submit pledge', even if a pledge has been submitted already

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#922]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Make it clearer that a pledge has been sent!

* **What feature or behavior is this required for?**
Not confusing our case managers by making it super obvious when someone's received a pledge!

* **How could we solve this issue? (Not knowing is okay!)**
There are a few free baskets we can take here when a patient has a submitted pledge on record, all in the patient edit view:
* Change the color of the submit pledge button to green (probably set the class `btn-success` or something)
* Change the text to 'Withdraw pledge?' instead of 'Submit pledge'
* Instead of rendering the normal `app/views/patients/_pledge.html.erb`, render a different multimodal with a basic 'Uncheck this box to withdraw the pledge to patient.name' and a check box for patient.pregnancy.pledge_sent. See `app/views/patients/_pledge.html.erb` for what this currently looks like

In addition: If we could change the text 'submit pledge' to `I'm ready to submit a pledge` when a pledge **hasn't** been submitted, that would be awesome.

* **Anything else?**
Kind of a lot, so please let me know if anything (especially the multimodal thing, which is a little more confusing than it looks, promise)!

**Comment by yf6** [comment]
MINE!

**Comment by zorkian** [comment]
Hmmm I think this is a duplicate of #457 which I just submitted a PR for. If it's not, then I must have misunderstood the other one, but I basically implemented what was requested here I think?

**Comment by yf6** [comment]
oh oops @zorkian good thing i haven't done much with it yet :D

**Comment by colinxfleming** [comment]
Oh yeah this is totally a dupe of #457. Sorry @yf6 @zorkian !
