### ISSUE TITLE
PT INFO: Create partial for top bar / core case information

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#93]
Create a partial for the top bar of the design - The name, phone number, LMP, Status, Appt Date portion. 

See https://projects.invisionapp.com/share/6757W6WFJ#/screens/115983267 for relevant design/prototype.

**Comment by charleshuang80** [comment]
@colinxfleming I'll start on the partials

**Comment by colinxfleming** [comment]
I think the core of this is here and we can break the rest of it (appointment date as datepicker, last menstrual period as human readable thing) up into discrete issues. Will tag those issues in this and close.

**Comment by colinxfleming** [comment]
Datepicker: #132 
LMP display: #141

Closing as good to go!
