### ISSUE TITLE
Stop incrementing LMP after appointment date has passed

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#931]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Stop incrementing LMP after appointment date has passed

* **What feature or behavior is this required for?**
One of the nicer features for our case managers is a running calculator that lets them know how far along a patient is. This is getting called by `last_menstrual_period_display_short`. It continues to increment indefinitely currently. We should change the behavior so that it stops incrementing at appointment date.

* **How could we solve this issue? (Not knowing is okay!)**
We should pop into the `last_menstrual_period_helper`. Note that this behaves like a concern (we wrote it before I knew about concerns :( ), so you have Patient object methods and attributes available. Probably the easiest way is to alter the behavior of `last_menstrual_period_now` to account for appointment date as well.

* **Anything else?**
Nope!

**Comment by yf6** [comment]
Me!
