### ISSUE TITLE
PT INFO: Create partial for patient information subsection

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#95]
Create a partial for the patient information subsection. (Just the right side of the form!) 

See https://projects.invisionapp.com/share/6757W6WFJ#/screens/115983267 for the designs.

**Comment by charleshuang80** [comment]
making this one and https://github.com/colinxfleming/dcaf_case_management/issues/94 one big form, and then we can style and break out into partials. Does that work?

**Comment by colinxfleming** [comment]
Settling in on this now. @charleshuang80 built a super solid foundation out so it shouldn't take very long.
