### ISSUE TITLE
Develop automated backup system

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#967]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Twice a day, run a task that takes a db snapshot and securely stories it somewhere, encrypted.

* **What feature or behavior is this required for?**
Me sleeping at night; data recovery in case of catastrophic failure. (I'm taking backups manually now.)

* **How could we solve this issue? (Not knowing is okay!)**
No idea but I am highly suggestible!

* **Anything else?**

**Comment by DarthHater** [comment]
I think we can leverage mLab backups for this.

PROS:
- Uses our existing db provider
- Stores backup to secure container they provide
- Doesn't require much if any tribal knowledge to know how to mess with it

CONS:
- Costs money (but not much, and this might be unavoidable)
- Backup storage is with database provider

Cost looks to be around 2 dollars a month for weekly backups, which is likely a good place to start?

You can in theory do the backups yourself and send them to S3 but then you incur the cost of S3 storage, securing it, etc... plus a lot of configuration/tasks/etc... that may be less transparent in terms of how to work on.
