### ISSUE TITLE
Pledge modal popup not loading properly

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#968]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Hitting submit pledge on a patient pops up a modal but doesn't load the modal content, including the buttons which we need to ship a pledge. If you reload and then click submit pledge again, the modal seems to render fine.

* **What feature or behavior is this required for?**
Pretty core feature, submitting a pledge!

* **How could we solve this issue? (Not knowing is okay!)**
Not sure. I suspect that this is an asset delivery issue and probably involves something we did in #955 , since javascript console logs seem to be coming back cleanly. 

* **Anything else?**
This is reproducible in the sandbox env as follows:
- log in
- go to the patient 'Clinic and Appt - 2'
- hit submit pledge'
- observe the following, no working buttons

![screen shot 2017-03-29 at 10 23 19 am](https://cloud.githubusercontent.com/assets/3866868/24459614/0227b410-146a-11e7-8398-7aff8729f690.png)

- reload the page and click 'submit pledge' again, and then see the working buttons

**Comment by colinxfleming** [comment]
Cursory googling also hints at this: https://stackoverflow.com/questions/17317816/rails-javascript-only-works-after-reload

**Comment by colinxfleming** [comment]
Oh yeah, looks like turbolinks goes from 2.5.3 to 5 in #955 (see the Gemfile.lock diff) which I'd guess is the source of this.

**Comment by DarthHater** [comment]
I'll take a gander at this (being I caused it, hah)
