### ISSUE TITLE
"Your current line: DC" shouldn't be a link

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#980]
In the top navigation, "Your current line: DC" should not be styled as a link. It is just a statement and no action can be taken against it. Please make it dark gray type that doesn't have any interaction. Thanks!! 

<img width="1197" alt="screen shot 2017-04-04 at 8 02 30 pm" src="https://cloud.githubusercontent.com/assets/6223901/24684149/dd732804-1971-11e7-830d-8b4c98540a5b.png">

**Comment by SamuelLangenfeld** [comment]
I'll tackle this monster
